backend_native.c File Reference
CK ← Back to C-Kernel-Engine Docs Doxygen Source Documentation
backend_native.c File Reference
#include "ckernel_engine.h"
Functions
CKMathBackend ckernel_backend_native (void)
static void ckernel_sgemm_native (int M, int N, int K, const float *A, int lda, const float *B, int ldb, const float *bias, float *C, int ldc)
Function Documentation
ckernel_backend_native()
CKMathBackend ckernel_backend_native (void)
Obtain the built-in native backend (single-node CPU, C + intrinsics).
Definition at line 30 of file backend_native.c.
 {
     CKMathBackend b;
     b.sgemm = &ckernel_sgemm_native;
     return b;
 }
References ckernel_sgemm_native(), and CKMathBackend::sgemm.
ckernel_sgemm_native()
static void ckernel_sgemm_native (int M, int N, int K, const float * A, int lda, const float * B, int ldb, const float * bias, float * C, int ldc) static
Native GEMM backend that directly reuses the C-Transformer GEMM kernel.
Layout assumptions (identical to C-Transformer/main.c):
A: [M x K], row-major, A(i,k) = A[i*K + k]
B: [N x K], row-major, B(j,k) = B[j*K + k]
C: [M x N], row-major, C(i,j) = C[i*N + j]
This is a straight copy of gemm_blocked_serial with a thin wrapper to match the CKMathBackend.sgemm signature. It is intentionally minimal.
Definition at line 18 of file backend_native.c.
 {
     (void)lda;
     (void)ldb;
     (void)ldc;
     gemm_blocked_serial(A, B, bias, C, M, N, K);
 }
References gemm_blocked_serial().
Referenced by ckernel_backend_native().