ckernel_engine.h File Reference
CK ← Back to C-Kernel-Engine Docs Doxygen Source Documentation
ckernel_engine.h File Reference
#include <stddef.h>
#include <stdint.h>
#include "cpu_features.h"
Data Structures
struct CKMathBackend
Functions
void attention_backward_causal_head_major (const float *d_output, const float *q, const float *k, const float *v, const float *attn_weights, float *d_q, float *d_k, float *d_v, float *d_scores, int num_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
void attention_backward_causal_head_major_gqa (const float *d_output, const float *q, const float *k, const float *v, const float *attn_weights, float *d_q, float *d_k, float *d_v, float *d_scores, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
void attention_backward_causal_head_major_gqa_bf16 (const uint16_t *d_output, float *d_x, const uint16_t *q, const uint16_t *k, const uint16_t *v, const float *attn_weights, float *d_q, float *d_k, float *d_v, float *d_scores, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
void attention_forward_causal_head_major (const float *q, const float *k, const float *v, float *scores, float *output, int num_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
void attention_forward_causal_head_major_exact (const float *q, const float *k, const float *v, float *scores, float *output, int num_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
void attention_forward_causal_head_major_gqa (const float *q, const float *k, const float *v, float *scores, float *output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
void attention_forward_causal_head_major_gqa_bf16 (const uint16_t *q, const uint16_t *k, const uint16_t *v, float *scores, float *output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
void attention_forward_causal_head_major_gqa_exact (const float *q, const float *k, const float *v, float *scores, float *output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
void attention_forward_causal_head_major_gqa_flash (const float *q, const float *k, const float *v, float *output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim)
void attention_forward_decode_head_major_gqa_flash (const float *q_token, const float *k_cache, const float *v_cache, float *out_token, int num_heads, int num_kv_heads, int kv_tokens, int cache_capacity, int head_dim, int aligned_head_dim)
void backward_causal_softmax_head_major (float *d_scores, const float *weights, int num_heads, int num_tokens, int aligned_context_window)
void backward_causal_softmax_head_major_bf16 (uint16_t *d_scores, const uint16_t *weights, int num_heads, int num_tokens, int aligned_context_window)
void causal_softmax_head_major (float *scores, int num_heads, int num_tokens, int aligned_context_window)
void causal_softmax_head_major_bf16 (uint16_t *scores, int num_heads, int num_tokens, int aligned_context_window)
void causal_softmax_head_major_exact (float *scores, int num_heads, int num_tokens, int aligned_context_window)
int ck_get_num_threads (void)
int ck_get_physical_cores (void)
void ck_set_num_threads (int num_threads)
void ck_set_strict_parity (int enabled)
int ck_strict_parity_enabled (void)
CKMathBackend ckernel_backend_native (void)
void dequant_q4_k_row (const void *src, float *dst, size_t n_elements)
Dequantize Q4_K row (multiple blocks)
void dequant_q6_k_row (const void *src, float *dst, size_t n_elements)
Dequantize Q6_K row (multiple blocks)
void embedding_backward (const int32_t *token_ids, int token_count, const float *d_output, float *d_token_embeddings, float *d_pos_embeddings, int vocab_size, int embed_dim, int aligned_embed_dim, int context_window, int add_pos)
void embedding_backward_bf16 (const int32_t *token_ids, int token_count, const uint16_t *d_output, uint16_t *d_token_embeddings, uint16_t *d_pos_embeddings, int vocab_size, int embed_dim, int aligned_embed_dim, int context_window, int add_pos)
void embedding_forward (const int32_t *token_ids, int token_count, int vocab_size, const float *token_embeddings, const float *pos_embeddings, float *output, int embed_dim, int aligned_embed_dim, int context_window, int add_pos)
void embedding_forward_bf16 (const int32_t *token_ids, int token_count, int vocab_size, const uint16_t *token_embeddings, const uint16_t *pos_embeddings, uint16_t *output, int embed_dim, int aligned_embed_dim, int context_window, int add_pos)
void fc1_backward_kernel (const float *d_output, const float *fc1_input, const float *W_fc1, float *d_input, float *d_W_fc1, float *d_b_fc1, int T, int aligned_in, int aligned_out, int num_threads)
void fc2_backward_kernel (const float *d_output, const float *fc2_input, const float *W_fc2, float *d_input, float *d_W_fc2, float *d_b_fc2, int T, int aligned_in, int aligned_out, int num_threads)
void fused_mlp_swiglu_decode (const float *x, const float *W_gate, const float *W_up, const float *W_down, const float *b_gate, const float *b_up, const float *b_down, float *output, int D, int Hff)
void fused_mlp_swiglu_decode_tiled (const float *x, const float *W_gate, const float *W_up, const float *W_down, const float *b_gate, const float *b_up, const float *b_down, float *output, int D, int Hff)
void fused_mlp_swiglu_decode_v2 (const float *x, const float *W_gate, const float *W_up, const float *W_down, const float *b_gate, const float *b_up, const float *b_down, float *output, int D, int Hff)
void gelu_backward_exact (const float *input, const float *d_output, float *d_input, size_t n)
void gelu_backward_exact_bf16 (const uint16_t *input, const uint16_t *d_output, uint16_t *d_input, size_t n)
void gelu_backward_fast (const float *input, const float *d_output, float *d_input, size_t n)
void gelu_backward_fast_bf16 (const uint16_t *input, const uint16_t *d_output, uint16_t *d_input, size_t n)
void gelu_backward_scalar (const float *input, const float *d_output, float *d_input, size_t n)
void gelu_exact_inplace (float *data, size_t n)
void gelu_fast_inplace (float *data, size_t n)
void gelu_fast_inplace_bf16 (uint16_t *data, size_t n)
void gemm_avx512_parallel (const float *A, const float *B, const float *bias, float *C, int M, int N, int K)
void gemm_bias_gelu_fused (const float *A, const float *B, const float *bias, float *C, int M, int N, int K)
void gemm_bias_relu_fused (const float *A, const float *B, const float *bias, float *C, int M, int N, int K)
void gemm_bias_silu_fused (const float *A, const float *B, const float *bias, float *C, int M, int N, int K)
void gemm_blocked_serial (const float *A, const float *B, const float *bias, float *C, int M, int N, int K)
void gemm_blocked_serial_bf16 (const uint16_t *A, const uint16_t *B, const uint16_t *bias, uint16_t *C, int M, int N, int K)
void gemm_fine_grained_parallel (const float *A, const float *B, const float *bias, float *C, int M, int N, int K)
void gemm_microkernel (const float *A, const float *B, float *C, int M, int N, int K, int B_transposed)
void gemm_microkernel_blocked (const float *A, const float *B, float *C, int M, int N, int K)
void gemm_microkernel_blocked_bt (const float *A, const float *B, float *C, int M, int N, int K)
void gemm_microkernel_packed (const float *A, const float *B, float *C, int M, int N, int K)
void gemm_naive_parallel (const float *A, const float *B, const float *bias, float *C, int M, int N, int K)
void gemm_nn_avx512 (const float *A, const float *B, const float *bias, float *C, int M, int N, int K)
void gemm_nn_blocked (const float *A, const float *B, const float *bias, float *C, int M, int N, int K)
void gemm_nn_parallel (const float *A, const float *B, const float *bias, float *C, int M, int N, int K)
void gemm_nt_q4_k (const float *A, const void *B, const float *bias, float *C, int M, int N, int K)
void gemm_nt_q4_k_q8_k (const void *A_q8, const void *B, const float *bias, float *C, int M, int N, int K)
void gemm_nt_q6_k (const float *A, const void *B, const float *bias, float *C, int M, int N, int K)
void gemm_q4_k (float *Y, const void *W, const float *X, int M, int N, int K)
Auto-dispatch GEMM based on available SIMD.
void gemm_q4_k_q8_k (float *Y, const void *W, const void *X_q8, int M, int N, int K)
void gemm_q6_k (float *Y, const void *W, const float *X, int M, int N, int K)
void gemm_swiglu_fused (const float *x, const float *W_gate, const float *W_up, const float *b_gate, const float *b_up, float *output, int M, int N, int K)
void gemm_tn_avx512 (const float *A, const float *B, const float *bias, float *C, int M, int N, int K)
void gemm_tn_blocked (const float *A, const float *B, const float *bias, float *C, int M, int N, int K)
void gemm_tn_parallel (const float *A, const float *B, const float *bias, float *C, int M, int N, int K)
void gemv_q4_k (float *y, const void *W, const float *x, int M, int K)
Auto-dispatch GEMV based on available SIMD.
void gemv_q4_k_q8_k (float *y, const void *W, const void *x_q8, int M, int K)
void gemv_q6_k (float *y, const void *W, const float *x, int M, int K)
void im2patch (const float *image, float *patches, int C, int H, int W, int P)
void im2patch_bf16 (const uint16_t *image, uint16_t *patches, int C, int H, int W, int P)
void kv_cache_repack_head_major_inplace (float *buf, int num_heads, int tokens, int cache_capacity, int aligned_head_dim)
void kv_cache_write_head_major (const float *k_token, const float *v_token, float *k_cache, float *v_cache, int num_kv_heads, int token_index, int cache_capacity, int head_dim, int aligned_head_dim)
void layernorm_backward_kernel (const float *d_output, const float *input, const float *gamma, const float *mean, const float *rstd, float *d_input, float *d_gamma, float *d_beta, int tokens, int d_model, int aligned_embed_dim)
void layernorm_backward_kernel_bf16 (const uint16_t *d_output, const uint16_t *input, const float *gamma, const float *mean, const float *rstd, uint16_t *d_input, float *d_gamma, float *d_beta, int tokens, int d_model, int aligned_embed_dim)
void layernorm_forward_rolled_slice (const float *__restrict input_slice_base, const float *__restrict gamma, const float *__restrict beta, float *__restrict output_slice_base, float *__restrict mean_cache_slice, float *__restrict rstd_cache_slice, int num_tokens_in_slice, int d_model, int aligned_embed_dim, float eps)
void layernorm_forward_rolled_slice_bf16 (const uint16_t *__restrict input_slice_base, const float *__restrict gamma, const float *__restrict beta, uint16_t *__restrict output_slice_base, float *__restrict mean_cache_slice, float *__restrict rstd_cache_slice, int num_tokens_in_slice, int d_model, int aligned_embed_dim, float eps)
void layernorm_forward_unrolled_slice (const float *__restrict input_slice_base, const float *__restrict gamma, const float *__restrict beta, float *__restrict output_slice_base, float *__restrict mean_cache_slice, float *__restrict rstd_cache_slice, int num_tokens_in_slice, int d_model, float eps)
void layernorm_forward_unrolled_slice_bf16 (const uint16_t *__restrict input_slice_base, const float *__restrict gamma, const float *__restrict beta, uint16_t *__restrict output_slice_base, float *__restrict mean_cache_slice, float *__restrict rstd_cache_slice, int num_tokens_in_slice, int d_model, float eps)
void layernorm_naive_serial (const float *input, const float *gamma, const float *beta, float *output, float *mean_cache, float *rstd_cache, int tokens, int d_model, int aligned_embed_dim, float eps)
void layernorm_naive_serial_matched_precision (const float *input, const float *gamma, const float *beta, float *output, float *mean_cache, float *rstd_cache, int tokens, int d_model, float eps)
void mlp_token_parallel (const float *input, const float *W_fc1, const float *b_fc1, const float *W_fc2, const float *b_fc2, float *fc1_output, float *output, int T, int aligned_dim, int num_threads)
void mlp_token_parallel_bf16 (const uint16_t *input, const uint16_t *W_fc1, const uint16_t *b_fc1, const uint16_t *W_fc2, const uint16_t *b_fc2, float *fc1_output, float *output, int T, int aligned_dim, int num_threads)
void mlp_token_parallel_exact (const float *input, const float *W_fc1, const float *b_fc1, const float *W_fc2, const float *b_fc2, float *fc1_output, float *output, int T, int aligned_dim, int num_threads)
void patch2im (const float *d_patches, float *d_image, int C, int H, int W, int P)
void patch2im_bf16 (const uint16_t *d_patches, uint16_t *d_image, int C, int H, int W, int P)
void quantize_row_q8_k (const float *x, void *y, int k)
void relu_backward (const float *input, const float *d_output, float *d_input, size_t n)
void relu_backward_bf16 (const uint16_t *input, const uint16_t *d_output, uint16_t *d_input, size_t n)
void relu_forward (const float *input, float *output, size_t n)
void relu_forward_bf16 (const uint16_t *input, uint16_t *output, size_t n)
void relu_forward_inplace (float *data, size_t n)
void relu_forward_inplace_bf16 (uint16_t *data, size_t n)
void rmsnorm_backward (const float *d_output, const float *input, const float *gamma, const float *rstd_cache, float *d_input, float *d_gamma, int tokens, int d_model, int aligned_embed_dim)
void rmsnorm_backward_bf16 (const uint16_t *d_output, const uint16_t *input, const float *gamma, const float *rstd_cache, uint16_t *d_input, float *d_gamma, int tokens, int d_model, int aligned_embed_dim)
void rmsnorm_backward_int4 (const uint8_t *d_output, const uint8_t *input, const float *gamma, const float *rstd_cache, uint8_t *d_input, float *d_gamma, int tokens, int d_model, int aligned_embed_dim)
void rmsnorm_backward_int8 (const int8_t *d_output, const int8_t *input, const float *gamma, const float *rstd_cache, int8_t *d_input, float *d_gamma, int tokens, int d_model, int aligned_embed_dim)
void rmsnorm_forward (const float *input, const float *gamma, float *output, float *rstd_cache, int tokens, int d_model, int aligned_embed_dim, float eps)
void rmsnorm_forward_bf16 (const uint16_t *input, const float *gamma, uint16_t *output, float *rstd_cache, int tokens, int d_model, int aligned_embed_dim, float eps)
void rmsnorm_forward_int4 (const uint8_t *input, const float *gamma, uint8_t *output, float *rstd_cache, int tokens, int d_model, int aligned_embed_dim, float eps)
void rmsnorm_forward_int8 (const int8_t *input, const float *gamma, int8_t *output, float *rstd_cache, int tokens, int d_model, int aligned_embed_dim, float eps)
void rope_backward (const float *d_out, float *d_x, const float *cos_cache, const float *sin_cache, int num_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset)
void rope_backward_bf16 (const uint16_t *d_out, uint16_t *d_x, const float *cos_cache, const float *sin_cache, int num_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset)
void rope_backward_inplace (float *d_x, const float *cos_cache, const float *sin_cache, int num_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset)
void rope_backward_qk (const float *d_q_out, const float *d_k_out, float *d_q, float *d_k, const float *cos_cache, const float *sin_cache, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset)
void rope_backward_qk_bf16 (const uint16_t *d_q_out, const uint16_t *d_k_out, uint16_t *d_q, uint16_t *d_k, const float *cos_cache, const float *sin_cache, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset)
void rope_forward (float *x, const float *cos_cache, const float *sin_cache, int num_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset)
void rope_forward_bf16 (uint16_t *x, const float *cos_cache, const float *sin_cache, int num_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset)
void rope_forward_qk (float *q, float *k, const float *cos_cache, const float *sin_cache, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset)
void rope_forward_qk_bf16 (uint16_t *q, uint16_t *k, const float *cos_cache, const float *sin_cache, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset)
void rope_precompute_cache (float *cos_cache, float *sin_cache, int max_seq_len, int head_dim, float base)
void sigmoid_backward (const float *input, const float *d_output, float *d_input, size_t n)
void sigmoid_backward_bf16 (const uint16_t *input, const uint16_t *d_output, uint16_t *d_input, size_t n)
void sigmoid_forward (const float *input, float *output, size_t n)
void sigmoid_forward_bf16 (const uint16_t *input, uint16_t *output, size_t n)
float sigmoid_scalar (float x)
void softmax_cross_entropy_loss (const float *logits, const int32_t *targets, int tokens, int vocab_size, float *d_logits, float *loss_out)
void softmax_cross_entropy_loss_bf16 (const uint16_t *logits, const int32_t *targets, int tokens, int vocab_size, uint16_t *d_logits, float *loss_out)
void swiglu_backward (const float *input, const float *d_output, float *d_input, int tokens, int dim)
void swiglu_backward_bf16 (const uint16_t *input, const uint16_t *d_output, uint16_t *d_input, int tokens, int dim)
void swiglu_backward_exact (const float *input, const float *d_output, float *d_input, int tokens, int dim)
void swiglu_forward (const float *input, float *output, int tokens, int dim)
void swiglu_forward_bf16 (const uint16_t *input, uint16_t *output, int tokens, int dim)
void swiglu_forward_exact (const float *input, float *output, int tokens, int dim)
Function Documentation
attention_backward_causal_head_major()
void attention_backward_causal_head_major (const float * d_output, const float * q, const float * k, const float * v, const float * attn_weights, float * d_q, float * d_k, float * d_v, float * d_scores, int num_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
Definition at line 1071 of file attention_kernels.c.
 {
     attention_backward_causal_head_major_gqa(
         d_output, q, k, v, attn_weights,
         d_q, d_k, d_v, d_scores,
         num_heads, num_heads,  // num_kv_heads == num_heads
         num_tokens, head_dim, aligned_head_dim, aligned_context_window);
 }
References attention_backward_causal_head_major_gqa().
attention_backward_causal_head_major_gqa()
void attention_backward_causal_head_major_gqa (const float * d_output, const float * q, const float * k, const float * v, const float * attn_weights, float * d_q, float * d_k, float * d_v, float * d_scores, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
Definition at line 942 of file attention_kernels.c.
 {
     const float scale = 1.0f / sqrtf((float)head_dim);
     int T = num_tokens;
     int H = num_heads;
     int H_kv = num_kv_heads;
     int hd = head_dim;
     int ad = aligned_head_dim;
     int aw = aligned_context_window;
     const size_t d_q_elems = (size_t)H * (size_t)T * (size_t)ad;
     const size_t kv_elems = (size_t)H_kv * (size_t)T * (size_t)ad;
     /* Zero the aligned outputs so padded lanes never leak garbage to downstream GEMMs. */
     for (size_t idx = 0; idx < d_q_elems; ++idx) {
         d_q[idx] = 0.0f;
     }
     for (size_t idx = 0; idx < kv_elems; ++idx) {
         d_k[idx] = 0.0f;
         d_v[idx] = 0.0f;
     }
     // Process each query head
     for (int h = 0; h < H; ++h) {
         // Which KV head does this query head use?
         int kv_h = (int)((long long)h * (long long)H_kv / (long long)H);
         // ----------------------------------------------------------------
         // Step 1: d_weights = d_output @ V^T  and  d_v += weights^T @ d_output
         // ----------------------------------------------------------------
         // For each query position i, compute d_weights[i, j] for j <= i
         // and accumulate d_v[j] contributions
         for (int i = 0; i < T; ++i) {
             size_t d_out_base = qkv_index(h, i, 0, T, ad);
             for (int j = 0; j <= i; ++j) {
                 size_t v_base = qkv_index(kv_h, j, 0, T, ad);
                 size_t w_idx = score_index(h, i, j, aw);
                 float w = attn_weights[w_idx];
                 // d_weights[h, i, j] = d_output[h, i, :] @ v[kv_h, j, :]^T
                 float dot = 0.0f;
                 for (int dd = 0; dd < hd; ++dd) {
                     dot += d_output[d_out_base + dd] * v[v_base + dd];
                 }
                 d_scores[w_idx] = dot;
                 // d_v[kv_h, j, :] += weights[h, i, j] * d_output[h, i, :]
                 for (int dd = 0; dd < hd; ++dd) {
                     d_v[v_base + dd] += w * d_output[d_out_base + dd];
                 }
             }
             // Zero out upper triangle of d_scores
             for (int j = i + 1; j < T; ++j) {
                 d_scores[score_index(h, i, j, aw)] = 0.0f;
             }
             /* Scores scratch uses aligned_context_window, zero the padded columns. */
             for (int j = T; j < aw; ++j) {
                 d_scores[score_index(h, i, j, aw)] = 0.0f;
             }
         }
         // ----------------------------------------------------------------
         // Step 2: Backward through softmax (in-place on d_scores for this head)
         // ----------------------------------------------------------------
         // d_scores = softmax_backward(d_scores, attn_weights)
         // Formula: d_score[i,j] = w[i,j] * (d_w[i,j] - sum_k(w[i,k] * d_w[i,k]))
         for (int i = 0; i < T; ++i) {
             int base = h * aw * aw + i * aw;
             // Compute dot product: sum_j w[i,j] * d_w[i,j]
             float dot_product = 0.0f;
             for (int j = 0; j <= i; ++j) {
                 float wt = attn_weights[base + j];
                 float dw = d_scores[base + j];
                 dot_product += wt * dw;
             }
             // Apply softmax backward formula
             for (int j = 0; j <= i; ++j) {
                 float wt = attn_weights[base + j];
                 float dw = d_scores[base + j];
                 d_scores[base + j] = wt * (dw - dot_product);
             }
         }
         // ----------------------------------------------------------------
         // Step 3: d_q = d_scores @ K * scale
         //         d_k += d_scores^T @ Q * scale
         // ----------------------------------------------------------------
         for (int i = 0; i < T; ++i) {
             size_t d_q_base = qkv_index(h, i, 0, T, ad);
             size_t q_base = qkv_index(h, i, 0, T, ad);
             // d_q[h, i, :] = sum_j d_scores[h, i, j] * k[kv_h, j, :] * scale
             // d_k[kv_h, j, :] += d_scores[h, i, j] * q[h, i, :] * scale
             for (int j = 0; j <= i; ++j) {
                 size_t k_base = qkv_index(kv_h, j, 0, T, ad);
                 size_t d_k_base = qkv_index(kv_h, j, 0, T, ad);
                 float ds = d_scores[score_index(h, i, j, aw)] * scale;
                 for (int dd = 0; dd < hd; ++dd) {
                     d_q[d_q_base + dd] += ds * k[k_base + dd];
                     d_k[d_k_base + dd] += ds * q[q_base + dd];
                 }
             }
         }
     }
 }
References qkv_index(), and score_index().
Referenced by attention_backward_causal_head_major(), attention_backward_causal_head_major_gqa_bf16(), and ck_layer_backward_rmsnorm_swiglu().
attention_backward_causal_head_major_gqa_bf16()
void attention_backward_causal_head_major_gqa_bf16 (const uint16_t * d_output, float * d_x, const uint16_t * q, const uint16_t * k, const uint16_t * v, const float * attn_weights, float * d_q, float * d_k, float * d_v, float * d_scores, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
Definition at line 884 of file attention_kernels.c.
 {
     (void)d_x;
     const size_t head_elems = (size_t)num_heads * (size_t)num_tokens * (size_t)aligned_head_dim;
     const size_t kv_elems = (size_t)num_kv_heads * (size_t)num_tokens * (size_t)aligned_head_dim;
     float *d_output_f = convert_bf16_tensor(d_output, head_elems);
     if (!d_output_f) {
         return;
     }
     float *q_f = convert_bf16_tensor(q, head_elems);
     if (!q_f) {
         free(d_output_f);
         return;
     }
     float *k_f = convert_bf16_tensor(k, kv_elems);
     if (!k_f) {
         free(d_output_f);
         free(q_f);
         return;
     }
     float *v_f = convert_bf16_tensor(v, kv_elems);
     if (!v_f) {
         free(d_output_f);
         free(q_f);
         free(k_f);
         return;
     }
     attention_backward_causal_head_major_gqa(d_output_f, q_f, k_f, v_f,
                                              attn_weights,
                                              d_q, d_k, d_v, d_scores,
                                              num_heads, num_kv_heads,
                                              num_tokens, head_dim,
                                              aligned_head_dim, aligned_context_window);
     free(d_output_f);
     free(q_f);
     free(k_f);
     free(v_f);
 }
References attention_backward_causal_head_major_gqa(), and convert_bf16_tensor().
attention_forward_causal_head_major()
void attention_forward_causal_head_major (const float * q, const float * k, const float * v, float * scores, float * output, int num_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
Definition at line 59 of file attention_kernels.c.
 {
     const float scale = 1.0f / sqrtf((float)head_dim);
     // Phase 1: compute scaled dot-product scores Q·K^T / sqrt(d_k),
     // lower triangle only (j <= i).
     for (int h = 0; h < num_heads; ++h) {
         for (int i = 0; i < num_tokens; ++i) {
             for (int j = 0; j <= i; ++j) {
                 float dot = 0.0f;
                 size_t base_q = qkv_index(h, i, 0, num_tokens, aligned_head_dim);
                 size_t base_k = qkv_index(h, j, 0, num_tokens, aligned_head_dim);
                 for (int d = 0; d < head_dim; ++d) {
                     dot += q[base_q + d] * k[base_k + d];
                 }
                 scores[score_index(h, i, j, aligned_context_window)] = dot * scale;
             }
             // Ensure upper triangle is zeroed so there are no stale values
             // before the softmax kernel runs.
             for (int j = i + 1; j < num_tokens; ++j) {
                 scores[score_index(h, i, j, aligned_context_window)] = 0.0f;
             }
         }
     }
     // Phase 2: apply causal row-wise softmax in-place over j <= i.
     causal_softmax_head_major(scores,
                               num_heads,
                               num_tokens,
                               aligned_context_window);
     // Phase 3: attention weights · V.
     for (int h = 0; h < num_heads; ++h) {
         for (int i = 0; i < num_tokens; ++i) {
             size_t out_base = qkv_index(h, i, 0, num_tokens, aligned_head_dim);
             // Zero the full aligned head slice so padded dims stay clean.
             for (int d = 0; d < aligned_head_dim; ++d) {
                 output[out_base + d] = 0.0f;
             }
             // Weighted sum over causal positions.
             for (int j = 0; j <= i; ++j) {
                 float w = scores[score_index(h, i, j, aligned_context_window)];
                 size_t v_base = qkv_index(h, j, 0, num_tokens, aligned_head_dim);
                 for (int d = 0; d < head_dim; ++d) {
                     output[out_base + d] += w * v[v_base + d];
                 }
             }
         }
     }
 }
References causal_softmax_head_major(), qkv_index(), and score_index().
attention_forward_causal_head_major_exact()
void attention_forward_causal_head_major_exact (const float * q, const float * k, const float * v, float * scores, float * output, int num_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
Definition at line 127 of file attention_kernels.c.
 {
     const float scale = 1.0f / sqrtf((float)head_dim);
     // Phase 1: compute scaled dot-product scores Q·K^T / sqrt(d_k),
     // lower triangle only (j <= i).
     for (int h = 0; h < num_heads; ++h) {
         for (int i = 0; i < num_tokens; ++i) {
             for (int j = 0; j <= i; ++j) {
                 float dot = 0.0f;
                 size_t base_q = qkv_index(h, i, 0, num_tokens, aligned_head_dim);
                 size_t base_k = qkv_index(h, j, 0, num_tokens, aligned_head_dim);
                 for (int d = 0; d < head_dim; ++d) {
                     dot += q[base_q + d] * k[base_k + d];
                 }
                 scores[score_index(h, i, j, aligned_context_window)] = dot * scale;
             }
             // Ensure upper triangle is zeroed so there are no stale values
             // before the softmax kernel runs.
             for (int j = i + 1; j < num_tokens; ++j) {
                 scores[score_index(h, i, j, aligned_context_window)] = 0.0f;
             }
         }
     }
     // Phase 2: apply causal row-wise softmax using exact expf.
     causal_softmax_head_major_exact(scores,
                                      num_heads,
                                      num_tokens,
                                      aligned_context_window);
     // Phase 3: attention weights · V.
     for (int h = 0; h < num_heads; ++h) {
         for (int i = 0; i < num_tokens; ++i) {
             size_t out_base = qkv_index(h, i, 0, num_tokens, aligned_head_dim);
             // Zero the full aligned head slice so padded dims stay clean.
             for (int d = 0; d < aligned_head_dim; ++d) {
                 output[out_base + d] = 0.0f;
             }
             // Weighted sum over causal positions.
             for (int j = 0; j <= i; ++j) {
                 float w = scores[score_index(h, i, j, aligned_context_window)];
                 size_t v_base = qkv_index(h, j, 0, num_tokens, aligned_head_dim);
                 for (int d = 0; d < head_dim; ++d) {
                     output[out_base + d] += w * v[v_base + d];
                 }
             }
         }
     }
 }
References causal_softmax_head_major_exact(), qkv_index(), and score_index().
attention_forward_causal_head_major_gqa()
void attention_forward_causal_head_major_gqa (const float * q, const float * k, const float * v, float * scores, float * output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
Definition at line 195 of file attention_kernels.c.
 {
     const float scale = 1.0f / sqrtf((float)head_dim);
     for (int h = 0; h < num_heads; ++h) {
         int kv_head = (int)((long long)h * (long long)num_kv_heads / (long long)num_heads);
         for (int i = 0; i < num_tokens; ++i) {
             for (int j = 0; j <= i; ++j) {
                 float dot = 0.0f;
                 size_t base_q = qkv_index(h, i, 0, num_tokens, aligned_head_dim);
                 size_t base_k = qkv_index(kv_head, j, 0, num_tokens, aligned_head_dim);
                 for (int d = 0; d < head_dim; ++d) {
                     dot += q[base_q + d] * k[base_k + d];
                 }
                 scores[score_index(h, i, j, aligned_context_window)] = dot * scale;
             }
             for (int j = i + 1; j < num_tokens; ++j) {
                 scores[score_index(h, i, j, aligned_context_window)] = 0.0f;
             }
         }
     }
     causal_softmax_head_major(scores,
                               num_heads,
                               num_tokens,
                               aligned_context_window);
     for (int h = 0; h < num_heads; ++h) {
         int kv_head = (int)((long long)h * (long long)num_kv_heads / (long long)num_heads);
         for (int i = 0; i < num_tokens; ++i) {
             size_t out_base = qkv_index(h, i, 0, num_tokens, aligned_head_dim);
             for (int d = 0; d < aligned_head_dim; ++d) {
                 output[out_base + d] = 0.0f;
             }
             for (int j = 0; j <= i; ++j) {
                 float w = scores[score_index(h, i, j, aligned_context_window)];
                 size_t v_base = qkv_index(kv_head, j, 0, num_tokens, aligned_head_dim);
                 for (int d = 0; d < head_dim; ++d) {
                     output[out_base + d] += w * v[v_base + d];
                 }
             }
         }
     }
 }
References causal_softmax_head_major(), qkv_index(), and score_index().
Referenced by ck_layer_forward_rmsnorm_swiglu(), ck_layer_forward_rmsnorm_swiglu_q4_k(), ck_layer_forward_rmsnorm_swiglu_quant(), and ck_layer_forward_rmsnorm_swiglu_ref().
attention_forward_causal_head_major_gqa_bf16()
void attention_forward_causal_head_major_gqa_bf16 (const uint16_t * q, const uint16_t * k, const uint16_t * v, float * scores, float * output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
Definition at line 319 of file attention_kernels.c.
 {
     const size_t q_elems = (size_t)num_heads * (size_t)num_tokens * (size_t)aligned_head_dim;
     const size_t kv_elems = (size_t)num_kv_heads * (size_t)num_tokens * (size_t)aligned_head_dim;
     float *q_float = convert_bf16_tensor(q, q_elems);
     if (!q_float) return;
     float *k_float = convert_bf16_tensor(k, kv_elems);
     if (!k_float) {
         free(q_float);
         return;
     }
     float *v_float = convert_bf16_tensor(v, kv_elems);
     if (!v_float) {
         free(q_float);
         free(k_float);
         return;
     }
     // Use exact version to avoid fast exp approximation error accumulating
     // with BF16 precision loss.
     attention_forward_causal_head_major_gqa_exact(q_float, k_float, v_float,
                                                    scores, output,
                                                    num_heads, num_kv_heads,
                                                    num_tokens, head_dim,
                                                    aligned_head_dim, aligned_context_window);
     free(q_float);
     free(k_float);
     free(v_float);
 }
References attention_forward_causal_head_major_gqa_exact(), and convert_bf16_tensor().
attention_forward_causal_head_major_gqa_exact()
void attention_forward_causal_head_major_gqa_exact (const float * q, const float * k, const float * v, float * scores, float * output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
Definition at line 258 of file attention_kernels.c.
 {
     const float scale = 1.0f / sqrtf((float)head_dim);
     for (int h = 0; h < num_heads; ++h) {
         int kv_head = (int)((long long)h * (long long)num_kv_heads / (long long)num_heads);
         for (int i = 0; i < num_tokens; ++i) {
             for (int j = 0; j <= i; ++j) {
                 float dot = 0.0f;
                 size_t base_q = qkv_index(h, i, 0, num_tokens, aligned_head_dim);
                 size_t base_k = qkv_index(kv_head, j, 0, num_tokens, aligned_head_dim);
                 for (int d = 0; d < head_dim; ++d) {
                     dot += q[base_q + d] * k[base_k + d];
                 }
                 scores[score_index(h, i, j, aligned_context_window)] = dot * scale;
             }
             for (int j = i + 1; j < num_tokens; ++j) {
                 scores[score_index(h, i, j, aligned_context_window)] = 0.0f;
             }
         }
     }
     // Use exact softmax with standard library expf
     causal_softmax_head_major_exact(scores,
                                      num_heads,
                                      num_tokens,
                                      aligned_context_window);
     for (int h = 0; h < num_heads; ++h) {
         int kv_head = (int)((long long)h * (long long)num_kv_heads / (long long)num_heads);
         for (int i = 0; i < num_tokens; ++i) {
             size_t out_base = qkv_index(h, i, 0, num_tokens, aligned_head_dim);
             for (int d = 0; d < aligned_head_dim; ++d) {
                 output[out_base + d] = 0.0f;
             }
             for (int j = 0; j <= i; ++j) {
                 float w = scores[score_index(h, i, j, aligned_context_window)];
                 size_t v_base = qkv_index(kv_head, j, 0, num_tokens, aligned_head_dim);
                 for (int d = 0; d < head_dim; ++d) {
                     output[out_base + d] += w * v[v_base + d];
                 }
             }
         }
     }
 }
References causal_softmax_head_major_exact(), qkv_index(), and score_index().
Referenced by attention_forward_causal_head_major_gqa_bf16().
attention_forward_causal_head_major_gqa_flash()
void attention_forward_causal_head_major_gqa_flash (const float * q, const float * k, const float * v, float * output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim)
Definition at line 749 of file attention_kernels.c.
 {
     if (!q || !k || !v || !output) {
         return;
     }
     if (num_heads <= 0 || num_kv_heads <= 0 || num_tokens <= 0) {
         return;
     }
     const float scale = 1.0f / sqrtf((float)head_dim);
     const int T = num_tokens;
     // Select SIMD implementation based on compile-time CPU features
 #if defined(__AVX512F__)
     #define FLASH_QUERY_IMPL attention_flash_query_causal_avx512
 #elif defined(__AVX2__)
     #define FLASH_QUERY_IMPL attention_flash_query_causal_avx2
 #elif defined(__AVX__)
     #define FLASH_QUERY_IMPL attention_flash_query_causal_avx
 #else
     #define FLASH_QUERY_IMPL attention_flash_query_causal
 #endif
     for (int h = 0; h < num_heads; ++h) {
         int kv_head = (int)((long long)h * (long long)num_kv_heads / (long long)num_heads);
         const float *k_head = k + (size_t)kv_head * (size_t)T * (size_t)aligned_head_dim;
         const float *v_head = v + (size_t)kv_head * (size_t)T * (size_t)aligned_head_dim;
         for (int i = 0; i < T; ++i) {
             const float *q_vec = q + qkv_index(h, i, 0, T, aligned_head_dim);
             float *out_vec = output + qkv_index(h, i, 0, T, aligned_head_dim);
             FLASH_QUERY_IMPL(q_vec, k_head, v_head,
                              /*kv_tokens=*/i + 1,
                              head_dim, aligned_head_dim,
                              scale, out_vec);
         }
     }
 #undef FLASH_QUERY_IMPL
 }
References FLASH_QUERY_IMPL, and qkv_index().
Referenced by ck_layer_forward_rmsnorm_swiglu(), ck_layer_forward_rmsnorm_swiglu_q4_k(), ck_layer_forward_rmsnorm_swiglu_quant(), and ck_layer_forward_rmsnorm_swiglu_ref().
attention_forward_decode_head_major_gqa_flash()
void attention_forward_decode_head_major_gqa_flash (const float * q_token, const float * k_cache, const float * v_cache, float * out_token, int num_heads, int num_kv_heads, int kv_tokens, int cache_capacity, int head_dim, int aligned_head_dim)
Definition at line 798 of file attention_kernels.c.
 {
     if (!q_token || !k_cache || !v_cache || !out_token) {
         return;
     }
     if (num_heads <= 0 || num_kv_heads <= 0 || kv_tokens <= 0 || cache_capacity <= 0) {
         return;
     }
     if (kv_tokens > cache_capacity) {
         return;
     }
     const float scale = 1.0f / sqrtf((float)head_dim);
     const size_t head_stride = (size_t)cache_capacity * (size_t)aligned_head_dim;
     // Select SIMD implementation based on compile-time CPU features
 #if defined(__AVX512F__)
     #define FLASH_QUERY_IMPL_DECODE attention_flash_query_causal_avx512
 #elif defined(__AVX2__)
     #define FLASH_QUERY_IMPL_DECODE attention_flash_query_causal_avx2
 #elif defined(__AVX__)
     #define FLASH_QUERY_IMPL_DECODE attention_flash_query_causal_avx
 #else
     #define FLASH_QUERY_IMPL_DECODE attention_flash_query_causal
 #endif
 #pragma omp parallel for schedule(static) if(num_heads > 1)
     for (int h = 0; h < num_heads; ++h) {
         int kv_head = (int)((long long)h * (long long)num_kv_heads / (long long)num_heads);
         const float *q_vec = q_token + (size_t)h * (size_t)aligned_head_dim;
         const float *k_head = k_cache + (size_t)kv_head * head_stride;
         const float *v_head = v_cache + (size_t)kv_head * head_stride;
         float *out_vec = out_token + (size_t)h * (size_t)aligned_head_dim;
         FLASH_QUERY_IMPL_DECODE(q_vec, k_head, v_head,
                                  kv_tokens, head_dim, aligned_head_dim,
                                  scale, out_vec);
     }
 #undef FLASH_QUERY_IMPL_DECODE
 }
References FLASH_QUERY_IMPL_DECODE.
Referenced by ck_layer_forward_rmsnorm_swiglu_decode(), ck_layer_forward_rmsnorm_swiglu_decode_fused(), ck_layer_forward_rmsnorm_swiglu_decode_fused_attn_impl(), ck_layer_forward_rmsnorm_swiglu_decode_q4_k(), and ck_layer_forward_rmsnorm_swiglu_decode_quant().
backward_causal_softmax_head_major()
void backward_causal_softmax_head_major (float * d_scores, const float * weights, int num_heads, int num_tokens, int aligned_context_window)
Definition at line 345 of file softmax_kernels.c.
 {
     int H = num_heads;
     int T = num_tokens;
     for (int h = 0; h < H; ++h) {
         for (int i = 0; i < T; ++i) {
             int base = h * aligned_context_window * aligned_context_window
                      + i * aligned_context_window;
             float *drow = &d_scores[base];
             const float *wrow = &weights[base];
             int len = i + 1;
 #if defined(__AVX512F__)
             // Compute dot product (vectorized)
             __m512 dot_vec = _mm512_setzero_ps();
             int j = 0;
             for (; j + 16 <= len; j += 16) {
                 __m512 w = _mm512_loadu_ps(&wrow[j]);
                 __m512 dw = _mm512_loadu_ps(&drow[j]);
                 dot_vec = _mm512_fmadd_ps(w, dw, dot_vec);
             }
             float dot_product = _mm512_reduce_add_ps(dot_vec);
             for (; j < len; ++j) {
                 dot_product += wrow[j] * drow[j];
             }
             // Compute gradient: d_scores = w * (dw - dot_product)
             __m512 dot_broadcast = _mm512_set1_ps(dot_product);
             j = 0;
             for (; j + 16 <= len; j += 16) {
                 __m512 w = _mm512_loadu_ps(&wrow[j]);
                 __m512 dw = _mm512_loadu_ps(&drow[j]);
                 __m512 diff = _mm512_sub_ps(dw, dot_broadcast);
                 __m512 result = _mm512_mul_ps(w, diff);
                 _mm512_storeu_ps(&drow[j], result);
             }
             for (; j < len; ++j) {
                 drow[j] = wrow[j] * (drow[j] - dot_product);
             }
             // Zero out future tokens
             __m512 zero = _mm512_setzero_ps();
             for (; j + 16 <= T; j += 16) {
                 _mm512_storeu_ps(&drow[j], zero);
             }
             for (; j < T; ++j) {
                 drow[j] = 0.0f;
             }
 #elif defined(__AVX__)
             // Compute dot product (vectorized)
             __m256 dot_vec = _mm256_setzero_ps();
             int j = 0;
             for (; j + 8 <= len; j += 8) {
                 __m256 w = _mm256_loadu_ps(&wrow[j]);
                 __m256 dw = _mm256_loadu_ps(&drow[j]);
                 // No FMA in AVX1: use mul + add
                 __m256 prod = _mm256_mul_ps(w, dw);
                 dot_vec = _mm256_add_ps(dot_vec, prod);
             }
             float dot_product = hsum256_ps_softmax(dot_vec);
             for (; j < len; ++j) {
                 dot_product += wrow[j] * drow[j];
             }
             // Compute gradient: d_scores = w * (dw - dot_product)
             __m256 dot_broadcast = _mm256_set1_ps(dot_product);
             j = 0;
             for (; j + 8 <= len; j += 8) {
                 __m256 w = _mm256_loadu_ps(&wrow[j]);
                 __m256 dw = _mm256_loadu_ps(&drow[j]);
                 __m256 diff = _mm256_sub_ps(dw, dot_broadcast);
                 __m256 result = _mm256_mul_ps(w, diff);
                 _mm256_storeu_ps(&drow[j], result);
             }
             for (; j < len; ++j) {
                 drow[j] = wrow[j] * (drow[j] - dot_product);
             }
             // Zero out future tokens
             __m256 zero = _mm256_setzero_ps();
             for (; j + 8 <= T; j += 8) {
                 _mm256_storeu_ps(&drow[j], zero);
             }
             for (; j < T; ++j) {
                 drow[j] = 0.0f;
             }
 #else
             // Scalar fallback
             float dot_product = 0.0f;
             for (int j = 0; j < len; ++j) {
                 dot_product += wrow[j] * drow[j];
             }
             for (int j = 0; j < len; ++j) {
                 drow[j] = wrow[j] * (drow[j] - dot_product);
             }
             for (int j = len; j < T; ++j) {
                 drow[j] = 0.0f;
             }
 #endif
         }
     }
 }
Referenced by backward_causal_softmax_head_major_bf16().
backward_causal_softmax_head_major_bf16()
void backward_causal_softmax_head_major_bf16 (uint16_t * d_scores, const uint16_t * weights, int num_heads, int num_tokens, int aligned_context_window)
Definition at line 36 of file softmax_kernels_bf16.c.
 {
     if (!d_scores || !weights || num_heads <= 0 || num_tokens <= 0 || aligned_context_window <= 0) {
         return;
     }
     const size_t total = (size_t)num_heads *
                          (size_t)aligned_context_window *
                          (size_t)aligned_context_window;
     float *d_scores_f = (float *)malloc(total * sizeof(float));
     float *weights_f = (float *)malloc(total * sizeof(float));
     if (!d_scores_f || !weights_f) {
         free(d_scores_f);
         free(weights_f);
         return;
     }
     bf16_tensor_to_float(d_scores, d_scores_f, total);
     bf16_tensor_to_float(weights, weights_f, total);
     backward_causal_softmax_head_major(d_scores_f, weights_f, num_heads, num_tokens, aligned_context_window);
     float_tensor_to_bf16(d_scores_f, d_scores, total);
     free(d_scores_f);
     free(weights_f);
 }
References backward_causal_softmax_head_major(), bf16_tensor_to_float(), and float_tensor_to_bf16().
causal_softmax_head_major()
void causal_softmax_head_major (float * scores, int num_heads, int num_tokens, int aligned_context_window)
Definition at line 116 of file softmax_kernels.c.
 {
     for (int h = 0; h < num_heads; ++h) {
         for (int i = 0; i < num_tokens; ++i) {
             int base = h * aligned_context_window * aligned_context_window
                      + i * aligned_context_window;
             float *row = &scores[base];
             int len = i + 1;  // Number of valid elements (0..i inclusive)
 #if defined(__AVX512F__)
             // Find max (vectorized)
             __m512 max_vec = _mm512_set1_ps(-INFINITY);
             int j = 0;
             for (; j + 16 <= len; j += 16) {
                 __m512 v = _mm512_loadu_ps(&row[j]);
                 max_vec = _mm512_max_ps(max_vec, v);
             }
             float max_val = _mm512_reduce_max_ps(max_vec);
             for (; j < len; ++j) {
                 if (row[j] > max_val) max_val = row[j];
             }
             // Compute exp and sum (vectorized)
             __m512 max_broadcast = _mm512_set1_ps(max_val);
             __m512 sum_vec = _mm512_setzero_ps();
             j = 0;
             for (; j + 16 <= len; j += 16) {
                 __m512 v = _mm512_loadu_ps(&row[j]);
                 __m512 e = exp512_approx(_mm512_sub_ps(v, max_broadcast));
                 _mm512_storeu_ps(&row[j], e);
                 sum_vec = _mm512_add_ps(sum_vec, e);
             }
             float sum = _mm512_reduce_add_ps(sum_vec);
             for (; j < len; ++j) {
                 float e = expf(row[j] - max_val);
                 row[j] = e;
                 sum += e;
             }
             // Normalize (vectorized)
             float inv_sum = 1.0f / sum;
             __m512 inv_sum_vec = _mm512_set1_ps(inv_sum);
             j = 0;
             for (; j + 16 <= len; j += 16) {
                 __m512 v = _mm512_loadu_ps(&row[j]);
                 _mm512_storeu_ps(&row[j], _mm512_mul_ps(v, inv_sum_vec));
             }
             for (; j < len; ++j) {
                 row[j] *= inv_sum;
             }
             // Zero out future tokens (vectorized)
             __m512 zero = _mm512_setzero_ps();
             for (; j + 16 <= num_tokens; j += 16) {
                 _mm512_storeu_ps(&row[j], zero);
             }
             for (; j < num_tokens; ++j) {
                 row[j] = 0.0f;
             }
 #elif defined(__AVX2__)
             // AVX2: Find max (vectorized)
             __m256 max_vec = _mm256_set1_ps(-INFINITY);
             int j = 0;
             for (; j + 8 <= len; j += 8) {
                 __m256 v = _mm256_loadu_ps(&row[j]);
                 max_vec = _mm256_max_ps(max_vec, v);
             }
             float max_val = hmax256_ps(max_vec);
             for (; j < len; ++j) {
                 if (row[j] > max_val) max_val = row[j];
             }
             // Compute exp and sum (vectorized with fast exp)
             __m256 max_broadcast = _mm256_set1_ps(max_val);
             __m256 sum_vec = _mm256_setzero_ps();
             j = 0;
             for (; j + 8 <= len; j += 8) {
                 __m256 v = _mm256_loadu_ps(&row[j]);
                 __m256 e = exp256_approx(_mm256_sub_ps(v, max_broadcast));
                 _mm256_storeu_ps(&row[j], e);
                 sum_vec = _mm256_add_ps(sum_vec, e);
             }
             float sum = hsum256_ps_softmax(sum_vec);
             for (; j < len; ++j) {
                 float e = expf(row[j] - max_val);
                 row[j] = e;
                 sum += e;
             }
             // Normalize (vectorized)
             float inv_sum = 1.0f / sum;
             __m256 inv_sum_vec = _mm256_set1_ps(inv_sum);
             j = 0;
             for (; j + 8 <= len; j += 8) {
                 __m256 v = _mm256_loadu_ps(&row[j]);
                 _mm256_storeu_ps(&row[j], _mm256_mul_ps(v, inv_sum_vec));
             }
             for (; j < len; ++j) {
                 row[j] *= inv_sum;
             }
             // Zero out future tokens (vectorized)
             __m256 zero = _mm256_setzero_ps();
             for (; j + 8 <= num_tokens; j += 8) {
                 _mm256_storeu_ps(&row[j], zero);
             }
             for (; j < num_tokens; ++j) {
                 row[j] = 0.0f;
             }
 #elif defined(__AVX__)
             // AVX1: vectorized max/sum/normalize, scalar exp
             __m256 max_vec = _mm256_set1_ps(-INFINITY);
             int j = 0;
             for (; j + 8 <= len; j += 8) {
                 __m256 v = _mm256_loadu_ps(&row[j]);
                 max_vec = _mm256_max_ps(max_vec, v);
             }
             float max_val = hmax256_ps(max_vec);
             for (; j < len; ++j) {
                 if (row[j] > max_val) max_val = row[j];
             }
             // Compute exp and sum (scalar exp, no fast approx for AVX1)
             float sum = 0.0f;
             for (j = 0; j < len; ++j) {
                 float e = expf(row[j] - max_val);
                 row[j] = e;
                 sum += e;
             }
             // Normalize (vectorized)
             float inv_sum = 1.0f / sum;
             __m256 inv_sum_vec = _mm256_set1_ps(inv_sum);
             j = 0;
             for (; j + 8 <= len; j += 8) {
                 __m256 v = _mm256_loadu_ps(&row[j]);
                 _mm256_storeu_ps(&row[j], _mm256_mul_ps(v, inv_sum_vec));
             }
             for (; j < len; ++j) {
                 row[j] *= inv_sum;
             }
             // Zero out future tokens (vectorized)
             __m256 zero = _mm256_setzero_ps();
             for (; j + 8 <= num_tokens; j += 8) {
                 _mm256_storeu_ps(&row[j], zero);
             }
             for (; j < num_tokens; ++j) {
                 row[j] = 0.0f;
             }
 #else
             // Scalar fallback
             float max_val = row[0];
             for (int j = 1; j < len; ++j) {
                 if (row[j] > max_val) max_val = row[j];
             }
             float sum = 0.0f;
             for (int j = 0; j < len; ++j) {
                 float e = expf(row[j] - max_val);
                 row[j] = e;
                 sum += e;
             }
             float inv_sum = 1.0f / sum;
             for (int j = 0; j < len; ++j) {
                 row[j] *= inv_sum;
             }
             for (int j = len; j < num_tokens; ++j) {
                 row[j] = 0.0f;
             }
 #endif
         }
     }
 }
Referenced by attention_forward_causal_head_major(), attention_forward_causal_head_major_gqa(), and causal_softmax_head_major_bf16().
causal_softmax_head_major_bf16()
void causal_softmax_head_major_bf16 (uint16_t * scores, int num_heads, int num_tokens, int aligned_context_window)
Definition at line 12 of file softmax_kernels_bf16.c.
 {
     if (!scores || num_heads <= 0 || num_tokens <= 0 || aligned_context_window <= 0) {
         return;
     }
     const size_t total = (size_t)num_heads *
                          (size_t)aligned_context_window *
                          (size_t)aligned_context_window;
     float *tmp = (float *)malloc(total * sizeof(float));
     if (!tmp) {
         return;
     }
     bf16_tensor_to_float(scores, tmp, total);
     causal_softmax_head_major(tmp, num_heads, num_tokens, aligned_context_window);
     float_tensor_to_bf16(tmp, scores, total);
     free(tmp);
 }
References bf16_tensor_to_float(), causal_softmax_head_major(), and float_tensor_to_bf16().
causal_softmax_head_major_exact()
void causal_softmax_head_major_exact (float * scores, int num_heads, int num_tokens, int aligned_context_window)
Definition at line 302 of file softmax_kernels.c.
 {
     for (int h = 0; h < num_heads; ++h) {
         for (int i = 0; i < num_tokens; ++i) {
             int base = h * aligned_context_window * aligned_context_window
                      + i * aligned_context_window;
             float *row = &scores[base];
             int len = i + 1;
             // Find max
             float max_val = -INFINITY;
             for (int j = 0; j < len; ++j) {
                 if (row[j] > max_val) max_val = row[j];
             }
             // Compute exp and sum using standard library expf
             float sum = 0.0f;
             for (int j = 0; j < len; ++j) {
                 float e = expf(row[j] - max_val);
                 row[j] = e;
                 sum += e;
             }
             // Normalize
             float inv_sum = 1.0f / sum;
             for (int j = 0; j < len; ++j) {
                 row[j] *= inv_sum;
             }
             // Zero out future tokens
             for (int j = len; j < num_tokens; ++j) {
                 row[j] = 0.0f;
             }
         }
     }
 }
Referenced by attention_forward_causal_head_major_exact(), and attention_forward_causal_head_major_gqa_exact().
ck_get_num_threads()
int ck_get_num_threads (void)
Definition at line 177 of file ckernel_strict.c.
 {
     // Auto-initialize if not set
     if (!g_threads_initialized) {
         ck_set_num_threads(0);  // Auto-detect
     }
     return g_num_threads;
 }
References ck_set_num_threads(), g_num_threads, and g_threads_initialized.
Referenced by gemm_blocked_serial().
ck_get_physical_cores()
int ck_get_physical_cores (void)
Definition at line 61 of file ckernel_strict.c.
 {
     int physical_cores = 0;
     int logical_cores = (int)sysconf(_SC_NPROCESSORS_ONLN);
     if (logical_cores <= 0) {
         logical_cores = 1;
     }
     // Read from /proc/cpuinfo (Linux) and count unique (physical id, core id) pairs.
     FILE *f = fopen("/proc/cpuinfo", "r");
     if (f) {
         char line[256];
         int physical_id = -1;
         int core_id = -1;
         struct {
             int physical_id;
             int core_id;
         } seen[8192];
         int seen_count = 0;
         const int seen_cap = (int)(sizeof(seen) / sizeof(seen[0]));
         // Helper: add (pid,cid) to set if not present.
         #define CK_ADD_PAIR(pid, cid)                                            \
             do {                                                                 \
                 if ((pid) >= 0 && (cid) >= 0) {                                  \
                     int exists = 0;                                              \
                     for (int ii = 0; ii < seen_count; ++ii) {                    \
                         if (seen[ii].physical_id == (pid) &&                     \
                             seen[ii].core_id == (cid)) {                         \
                             exists = 1;                                          \
                             break;                                               \
                         }                                                        \
                     }                                                            \
                     if (!exists && seen_count < seen_cap) {                      \
                         seen[seen_count].physical_id = (pid);                    \
                         seen[seen_count].core_id = (cid);                        \
                         ++seen_count;                                            \
                     }                                                            \
                 }                                                                \
             } while (0)
         while (fgets(line, sizeof(line), f)) {
             int val;
             // Blank line separates processor blocks.
             if (line[0] == '\n' || line[0] == '\0') {
                 CK_ADD_PAIR(physical_id, core_id);
                 physical_id = -1;
                 core_id = -1;
                 continue;
             }
             if (sscanf(line, "physical id : %d", &val) == 1) {
                 physical_id = val;
                 continue;
             }
             if (sscanf(line, "core id : %d", &val) == 1) {
                 core_id = val;
                 continue;
             }
         }
         fclose(f);
         // Handle file without trailing blank line.
         CK_ADD_PAIR(physical_id, core_id);
         #undef CK_ADD_PAIR
         physical_cores = seen_count;
     }
     // If we couldn't reliably detect physical cores (common in containers),
     // fall back to logical CPUs instead of incorrectly forcing single-thread execution.
     if (physical_cores <= 1 && logical_cores > 1) {
         return logical_cores;
     }
     if (physical_cores > 1) {
         return physical_cores;
     }
     return logical_cores;
 }
References CK_ADD_PAIR.
Referenced by ck_set_num_threads().
ck_set_num_threads()
void ck_set_num_threads (int num_threads)
Definition at line 147 of file ckernel_strict.c.
 {
     // 0 = auto-detect
     if (num_threads <= 0) {
         // Prefer explicit env controls when present:
         // - CK_NUM_THREADS: engine-level override
         // - OMP_NUM_THREADS: standard OpenMP control (set by `ck run --threads`)
         int env_threads = ck_parse_env_int("CK_NUM_THREADS");
         if (env_threads <= 0) {
             env_threads = ck_parse_env_int("OMP_NUM_THREADS");
         }
         num_threads = env_threads > 0 ? env_threads : ck_get_physical_cores();
     }
     g_num_threads = num_threads;
     g_threads_initialized = 1;
 #ifdef _OPENMP
     omp_set_dynamic(0);  // Disable dynamic adjustment
     omp_set_num_threads(num_threads);
 #endif
 #if defined(USE_MKL)
     mkl_set_num_threads(num_threads);
 #endif
     fprintf(stderr, "[CK] Set %d threads (auto=%d)\n",
             num_threads, ck_get_physical_cores());
 }
References ck_get_physical_cores(), ck_parse_env_int(), g_num_threads, and g_threads_initialized.
Referenced by ck_get_num_threads().
ck_set_strict_parity()
void ck_set_strict_parity (int enabled)
Definition at line 21 of file ckernel_strict.c.
 {
     ck_strict_parity = enabled ? 1 : 0;
 #ifdef _OPENMP
     if (ck_strict_parity) {
         omp_set_dynamic(0);
         omp_set_num_threads(1);
     }
 #endif
 }
References ck_strict_parity.
ck_strict_parity_enabled()
int ck_strict_parity_enabled (void)
Definition at line 32 of file ckernel_strict.c.
 {
     return ck_strict_parity;
 }
References ck_strict_parity.
Referenced by ck_q8k_activations_enabled(), gemm_avx512_parallel(), gemm_blocked_serial(), gemm_fine_grained_parallel(), gemm_naive_parallel(), gemm_nn_avx512(), gemm_nn_blocked(), gemm_nn_parallel(), gemm_tn_avx512(), gemm_tn_blocked(), and gemm_tn_parallel().
ckernel_backend_native()
CKMathBackend ckernel_backend_native (void)
Obtain the built-in native backend (single-node CPU, C + intrinsics).
Definition at line 39 of file backend_native.c.
 {
     CKMathBackend b;
     b.sgemm = &ckernel_sgemm_native;
     return b;
 }
References ckernel_sgemm_native(), and CKMathBackend::sgemm.
dequant_q4_k_row()
void dequant_q4_k_row (const void * src, float * dst, size_t n_elements)
Dequantize Q4_K row (multiple blocks)
Definition at line 202 of file dequant_kernels.c.
 {
     const block_q4_K *blocks = (const block_q4_K *)src;
     const size_t n_blocks = n_elements / QK_K;
     for (size_t b = 0; b < n_blocks; b++) {
         dequant_q4_k_block(&blocks[b], &dst[b * QK_K]);
     }
 }
References dequant_q4_k_block(), and QK_K.
Referenced by dequant_row().
dequant_q6_k_row()
void dequant_q6_k_row (const void * src, float * dst, size_t n_elements)
Dequantize Q6_K row (multiple blocks)
Definition at line 252 of file dequant_kernels.c.
 {
     const block_q6_K *blocks = (const block_q6_K *)src;
     const size_t n_blocks = n_elements / QK_K;
     for (size_t b = 0; b < n_blocks; b++) {
         dequant_q6_k_block(&blocks[b], &dst[b * QK_K]);
     }
 }
References dequant_q6_k_block(), and QK_K.
Referenced by dequant_row().
embedding_backward()
void embedding_backward (const int32_t * token_ids, int token_count, const float * d_output, float * d_token_embeddings, float * d_pos_embeddings, int vocab_size, int embed_dim, int aligned_embed_dim, int context_window, int add_pos)
Definition at line 59 of file embedding_kernels.c.
 {
     if (!token_ids || !d_output || !d_token_embeddings) {
         return;
     }
     int tokens = token_count;
     if (tokens < 0) {
         tokens = 0;
     }
     if (tokens > context_window) {
         tokens = context_window;
     }
     for (int t = 0; t < tokens; ++t) {
         int id = token_ids[t];
         if (id < 0 || id >= vocab_size) {
             id = 0;
         }
         const float *d_out = d_output + (size_t)t * (size_t)aligned_embed_dim;
         float *d_tok = d_token_embeddings + (size_t)id * (size_t)aligned_embed_dim;
         float *d_pos = d_pos_embeddings ? (d_pos_embeddings + (size_t)t * (size_t)aligned_embed_dim) : NULL;
         for (int d = 0; d < embed_dim; ++d) {
             float grad = d_out[d];
             d_tok[d] += grad;
             if (add_pos && d_pos) {
                 d_pos[d] += grad;
             }
         }
     }
 }
embedding_backward_bf16()
void embedding_backward_bf16 (const int32_t * token_ids, int token_count, const uint16_t * d_output, uint16_t * d_token_embeddings, uint16_t * d_pos_embeddings, int vocab_size, int embed_dim, int aligned_embed_dim, int context_window, int add_pos)
Definition at line 58 of file embedding_kernels_bf16.c.
 {
     if (!token_ids || !d_output || !d_token_embeddings) {
         return;
     }
     int tokens = token_count;
     if (tokens < 0) tokens = 0;
     if (tokens > context_window) tokens = context_window;
     for (int t = 0; t < tokens; ++t) {
         int id = token_ids[t];
         if (id < 0 || id >= vocab_size) {
             id = 0;
         }
         const uint16_t *d_out = d_output + (size_t)t * (size_t)aligned_embed_dim;
         uint16_t *d_tok = d_token_embeddings + (size_t)id * (size_t)aligned_embed_dim;
         uint16_t *d_pos = d_pos_embeddings ? (d_pos_embeddings + (size_t)t * (size_t)aligned_embed_dim) : NULL;
         for (int d = 0; d < embed_dim; ++d) {
             float grad = bf16_to_float(d_out[d]);
             float cur_tok = bf16_to_float(d_tok[d]);
             d_tok[d] = float_to_bf16(cur_tok + grad);
             if (add_pos && d_pos) {
                 float cur_pos = bf16_to_float(d_pos[d]);
                 d_pos[d] = float_to_bf16(cur_pos + grad);
             }
         }
     }
 }
References bf16_to_float(), and float_to_bf16().
embedding_forward()
void embedding_forward (const int32_t * token_ids, int token_count, int vocab_size, const float * token_embeddings, const float * pos_embeddings, float * output, int embed_dim, int aligned_embed_dim, int context_window, int add_pos)
Definition at line 5 of file embedding_kernels.c.
 {
     if (!token_ids || !token_embeddings || !output) {
         return;
     }
     int tokens = token_count;
     if (tokens < 0) {
         tokens = 0;
     }
     if (tokens > context_window) {
         tokens = context_window;
     }
     for (int t = 0; t < tokens; ++t) {
         int id = token_ids[t];
         if (id < 0 || id >= vocab_size) {
             id = 0;
         }
         const float *tok = token_embeddings + (size_t)id * (size_t)aligned_embed_dim;
         const float *pos = pos_embeddings ? (pos_embeddings + (size_t)t * (size_t)aligned_embed_dim) : NULL;
         float *out = output + (size_t)t * (size_t)aligned_embed_dim;
         if (add_pos && pos) {
             for (int d = 0; d < embed_dim; ++d) {
                 out[d] = tok[d] + pos[d];
             }
         } else {
             for (int d = 0; d < embed_dim; ++d) {
                 out[d] = tok[d];
             }
         }
         for (int d = embed_dim; d < aligned_embed_dim; ++d) {
             out[d] = 0.0f;
         }
     }
     for (int t = tokens; t < context_window; ++t) {
         float *out = output + (size_t)t * (size_t)aligned_embed_dim;
         memset(out, 0, (size_t)aligned_embed_dim * sizeof(float));
     }
 }
embedding_forward_bf16()
void embedding_forward_bf16 (const int32_t * token_ids, int token_count, int vocab_size, const uint16_t * token_embeddings, const uint16_t * pos_embeddings, uint16_t * output, int embed_dim, int aligned_embed_dim, int context_window, int add_pos)
Definition at line 7 of file embedding_kernels_bf16.c.
 {
     if (!token_ids || !token_embeddings || !output) {
         return;
     }
     int tokens = token_count;
     if (tokens < 0) tokens = 0;
     if (tokens > context_window) tokens = context_window;
     for (int t = 0; t < tokens; ++t) {
         int id = token_ids[t];
         if (id < 0 || id >= vocab_size) {
             id = 0;
         }
         const uint16_t *tok = token_embeddings + (size_t)id * (size_t)aligned_embed_dim;
         const uint16_t *pos = pos_embeddings ? (pos_embeddings + (size_t)t * (size_t)aligned_embed_dim) : NULL;
         uint16_t *out = output + (size_t)t * (size_t)aligned_embed_dim;
         if (add_pos && pos) {
             for (int d = 0; d < embed_dim; ++d) {
                 float v = bf16_to_float(tok[d]) + bf16_to_float(pos[d]);
                 out[d] = float_to_bf16(v);
             }
         } else {
             for (int d = 0; d < embed_dim; ++d) {
                 out[d] = tok[d];
             }
         }
         for (int d = embed_dim; d < aligned_embed_dim; ++d) {
             out[d] = 0;
         }
     }
     for (int t = tokens; t < context_window; ++t) {
         uint16_t *out = output + (size_t)t * (size_t)aligned_embed_dim;
         memset(out, 0, (size_t)aligned_embed_dim * sizeof(uint16_t));
     }
 }
References bf16_to_float(), and float_to_bf16().
fc1_backward_kernel()
void fc1_backward_kernel (const float * d_output, const float * fc1_input, const float * W_fc1, float * d_input, float * d_W_fc1, float * d_b_fc1, int T, int aligned_in, int aligned_out, int num_threads)
Definition at line 148 of file mlp_kernels.c.
 {
     (void)num_threads;  // Threading handled by GEMM kernels
     // 1. d_input[T, in] = d_output[T, out] @ W[out, in]
     // Using gemm_nn: C[M,N] = A[M,K] @ B[K,N]
     // A = d_output [T, out], B = W [out, in], C = d_input [T, in]
     // M = T, N = aligned_in, K = aligned_out
     gemm_nn_avx512(d_output, W_fc1, NULL, d_input,
                    T, aligned_in, aligned_out);
     // 2. d_W[out, in] = d_output[T, out].T @ fc1_input[T, in]
     // Using gemm_tn: C[M,N] = A[K,M].T @ B[K,N]
     // A = d_output [T, out] (stored as [K=T, M=out]), B = fc1_input [T, in]
     // C = d_W [out, in], M = aligned_out, N = aligned_in, K = T
     gemm_tn_avx512(d_output, fc1_input, NULL, d_W_fc1,
                    aligned_out, aligned_in, T);
     // 3. d_b_fc1 = sum_over_T(d_output)
 #pragma omp parallel for schedule(static)
     for (int out_idx = 0; out_idx < aligned_out; ++out_idx) {
         float bias_grad = 0.0f;
         for (int t = 0; t < T; ++t) {
             bias_grad += d_output[(size_t)t * aligned_out + out_idx];
         }
         d_b_fc1[out_idx] += bias_grad;
     }
 }
References gemm_nn_avx512(), and gemm_tn_avx512().
Referenced by ck_layer_backward_rmsnorm_swiglu().
fc2_backward_kernel()
void fc2_backward_kernel (const float * d_output, const float * fc2_input, const float * W_fc2, float * d_input, float * d_W_fc2, float * d_b_fc2, int T, int aligned_in, int aligned_out, int num_threads)
Definition at line 99 of file mlp_kernels.c.
 {
     (void)num_threads;  // Threading handled by GEMM kernels
     // 1. d_input[T, in] = d_output[T, out] @ W[out, in]
     // Using gemm_nn: C[M,N] = A[M,K] @ B[K,N]
     // A = d_output [T, out], B = W [out, in], C = d_input [T, in]
     // M = T, N = aligned_in, K = aligned_out
     gemm_nn_avx512(d_output, W_fc2, NULL, d_input,
                    T, aligned_in, aligned_out);
     // 2. d_W[out, in] = d_output[T, out].T @ fc2_input[T, in]
     // Using gemm_tn: C[M,N] = A[K,M].T @ B[K,N]
     // A = d_output [T, out] (stored as [K=T, M=out]), B = fc2_input [T, in]
     // C = d_W [out, in], M = aligned_out, N = aligned_in, K = T
     // Note: gemm_tn overwrites, so we need to save and add if accumulating
     // For now, assume d_W starts zeroed (gradient accumulation handled at higher level)
     gemm_tn_avx512(d_output, fc2_input, NULL, d_W_fc2,
                    aligned_out, aligned_in, T);
     // 3. d_b_fc2 = sum_over_T(d_output)
 #pragma omp parallel for schedule(static)
     for (int out_idx = 0; out_idx < aligned_out; ++out_idx) {
         float bias_grad = 0.0f;
         for (int t = 0; t < T; ++t) {
             bias_grad += d_output[(size_t)t * aligned_out + out_idx];
         }
         d_b_fc2[out_idx] += bias_grad;
     }
 }
References gemm_nn_avx512(), and gemm_tn_avx512().
Referenced by ck_attention_project_head_major_backward(), ck_layer_backward_rmsnorm_swiglu(), and ck_qkv_project_head_major_backward().
fused_mlp_swiglu_decode()
void fused_mlp_swiglu_decode (const float * x, const float * W_gate, const float * W_up, const float * W_down, const float * b_gate, const float * b_up, const float * b_down, float * output, int D, int Hff)
Definition at line 142 of file mlp_fused_decode.c.
 {
 #if defined(__AVX512F__)
     // Initialize output with bias or zero
     if (b_down) {
         memcpy(output, b_down, D * sizeof(float));
     } else {
         memset(output, 0, D * sizeof(float));
     }
     // Process intermediate dimension in tiles
     // Each tile computes MLP_TILE_SIZE swiglu values and immediately
     // accumulates them into the output
     #pragma omp parallel
     {
         // Thread-local accumulator for output
         float *local_output = (float *)aligned_alloc(64, D * sizeof(float));
         memset(local_output, 0, D * sizeof(float));
         #pragma omp for schedule(static)
         for (int t = 0; t < Hff; t += MLP_TILE_SIZE) {
             int tile_end = (t + MLP_TILE_SIZE < Hff) ? t + MLP_TILE_SIZE : Hff;
             int tile_size = tile_end - t;
             // Compute SwiGLU for this tile (stays in L1 cache)
             float swiglu_tile[MLP_TILE_SIZE] __attribute__((aligned(64)));
             for (int j = t; j < tile_end; j++) {
                 const float *wg_row = &W_gate[j * D];
                 const float *wu_row = &W_up[j * D];
                 // Compute gate = x @ W_gate[j] using AVX-512
                 __m512 gate_acc = _mm512_setzero_ps();
                 __m512 up_acc = _mm512_setzero_ps();
                 int k = 0;
                 for (; k <= D - 16; k += 16) {
                     __m512 x_vec = _mm512_loadu_ps(&x[k]);
                     __m512 wg_vec = _mm512_loadu_ps(&wg_row[k]);
                     __m512 wu_vec = _mm512_loadu_ps(&wu_row[k]);
                     gate_acc = _mm512_fmadd_ps(x_vec, wg_vec, gate_acc);
                     up_acc = _mm512_fmadd_ps(x_vec, wu_vec, up_acc);
                 }
                 float gate = hsum512_ps(gate_acc);
                 float up = hsum512_ps(up_acc);
                 // Scalar remainder
                 for (; k < D; k++) {
                     gate += x[k] * wg_row[k];
                     up += x[k] * wu_row[k];
                 }
                 // Add biases
                 if (b_gate) gate += b_gate[j];
                 if (b_up) up += b_up[j];
                 // SwiGLU: SiLU(gate) * up
                 swiglu_tile[j - t] = silu_scalar(gate) * up;
             }
             // Accumulate into output via W_down
             // output[i] += sum_j(swiglu_tile[j] * W_down[i, t+j])
             for (int i = 0; i < D; i++) {
                 const float *wd_row = &W_down[i * Hff + t];
                 __m512 acc = _mm512_setzero_ps();
                 int j = 0;
                 for (; j <= tile_size - 16; j += 16) {
                     __m512 sw_vec = _mm512_loadu_ps(&swiglu_tile[j]);
                     __m512 wd_vec = _mm512_loadu_ps(&wd_row[j]);
                     acc = _mm512_fmadd_ps(sw_vec, wd_vec, acc);
                 }
                 float sum = hsum512_ps(acc);
                 for (; j < tile_size; j++) {
                     sum += swiglu_tile[j] * wd_row[j];
                 }
                 local_output[i] += sum;
             }
         }
         // Reduce thread-local outputs
         #pragma omp critical
         {
             for (int i = 0; i < D; i++) {
                 output[i] += local_output[i];
             }
         }
         free(local_output);
     }
 #else
     // Scalar fallback (same algorithm, no SIMD)
     if (b_down) {
         memcpy(output, b_down, D * sizeof(float));
     } else {
         memset(output, 0, D * sizeof(float));
     }
     for (int t = 0; t < Hff; t += MLP_TILE_SIZE) {
         int tile_end = (t + MLP_TILE_SIZE < Hff) ? t + MLP_TILE_SIZE : Hff;
         int tile_size = tile_end - t;
         float swiglu_tile[MLP_TILE_SIZE];
         for (int j = t; j < tile_end; j++) {
             float gate = 0.0f;
             float up = 0.0f;
             for (int k = 0; k < D; k++) {
                 gate += x[k] * W_gate[j * D + k];
                 up += x[k] * W_up[j * D + k];
             }
             if (b_gate) gate += b_gate[j];
             if (b_up) up += b_up[j];
             swiglu_tile[j - t] = silu_scalar(gate) * up;
         }
         for (int i = 0; i < D; i++) {
             for (int j = 0; j < tile_size; j++) {
                 output[i] += swiglu_tile[j] * W_down[i * Hff + t + j];
             }
         }
     }
 #endif
 }
References __attribute__(), MLP_TILE_SIZE, and silu_scalar().
fused_mlp_swiglu_decode_tiled()
void fused_mlp_swiglu_decode_tiled (const float * x, const float * W_gate, const float * W_up, const float * W_down, const float * b_gate, const float * b_up, const float * b_down, float * output, int D, int Hff)
Definition at line 415 of file mlp_fused_decode.c.
 {
     // Tile size chosen to fit in L2 with W_down tile
     // Tile of swiglu: 256 floats = 1KB
     // Tile of W_down: 256 * D floats = 256 * 896 * 4 = 896KB
     // Fits in 2MB L2 with room for x and prefetch
     const int TILE = 256;
 #if defined(__AVX512F__)
     // Initialize output
     #pragma omp parallel for schedule(static)
     for (int i = 0; i < D; i++) {
         output[i] = b_down ? b_down[i] : 0.0f;
     }
     // Process tiles of intermediate dimension
     for (int t = 0; t < Hff; t += TILE) {
         int tile_end = (t + TILE < Hff) ? t + TILE : Hff;
         int tile_size = tile_end - t;
         // Compute swiglu tile
         float swiglu_tile[256] __attribute__((aligned(64)));
         #pragma omp parallel for schedule(static)
         for (int jj = 0; jj < tile_size; jj++) {
             int j = t + jj;
             const float *wg_row = &W_gate[j * D];
             const float *wu_row = &W_up[j * D];
             __m512 gate_acc = _mm512_setzero_ps();
             __m512 up_acc = _mm512_setzero_ps();
             int k = 0;
             for (; k <= D - 16; k += 16) {
                 __m512 x_vec = _mm512_loadu_ps(&x[k]);
                 __m512 wg_vec = _mm512_loadu_ps(&wg_row[k]);
                 __m512 wu_vec = _mm512_loadu_ps(&wu_row[k]);
                 gate_acc = _mm512_fmadd_ps(x_vec, wg_vec, gate_acc);
                 up_acc = _mm512_fmadd_ps(x_vec, wu_vec, up_acc);
             }
             float gate = hsum512_ps(gate_acc);
             float up = hsum512_ps(up_acc);
             for (; k < D; k++) {
                 gate += x[k] * wg_row[k];
                 up += x[k] * wu_row[k];
             }
             if (b_gate) gate += b_gate[j];
             if (b_up) up += b_up[j];
             swiglu_tile[jj] = silu_scalar(gate) * up;
         }
         // Accumulate into output (parallelize over D)
         #pragma omp parallel for schedule(static)
         for (int i = 0; i < D; i++) {
             const float *wd_row = &W_down[i * Hff + t];
             __m512 acc = _mm512_setzero_ps();
             int j = 0;
             for (; j <= tile_size - 16; j += 16) {
                 __m512 sw_vec = _mm512_loadu_ps(&swiglu_tile[j]);
                 __m512 wd_vec = _mm512_loadu_ps(&wd_row[j]);
                 acc = _mm512_fmadd_ps(sw_vec, wd_vec, acc);
             }
             float sum = hsum512_ps(acc);
             for (; j < tile_size; j++) {
                 sum += swiglu_tile[j] * wd_row[j];
             }
             // Atomic add (or use thread-local buffers for better perf)
             #pragma omp atomic
             output[i] += sum;
         }
     }
 #else
     // Scalar fallback
     for (int i = 0; i < D; i++) {
         output[i] = b_down ? b_down[i] : 0.0f;
     }
     for (int t = 0; t < Hff; t += TILE) {
         int tile_end = (t + TILE < Hff) ? t + TILE : Hff;
         float swiglu_tile[256];
         for (int j = t; j < tile_end; j++) {
             float gate = 0.0f, up = 0.0f;
             for (int k = 0; k < D; k++) {
                 gate += x[k] * W_gate[j * D + k];
                 up += x[k] * W_up[j * D + k];
             }
             if (b_gate) gate += b_gate[j];
             if (b_up) up += b_up[j];
             swiglu_tile[j - t] = silu_scalar(gate) * up;
         }
         for (int i = 0; i < D; i++) {
             for (int j = t; j < tile_end; j++) {
                 output[i] += swiglu_tile[j - t] * W_down[i * Hff + j];
             }
         }
     }
 #endif
 }
References __attribute__(), and silu_scalar().
Referenced by fused_mlp_swiglu_decode_v2().
fused_mlp_swiglu_decode_v2()
void fused_mlp_swiglu_decode_v2 (const float * x, const float * W_gate, const float * W_up, const float * W_down, const float * b_gate, const float * b_up, const float * b_down, float * output, int D, int Hff)
Definition at line 304 of file mlp_fused_decode.c.
 {
     // For large Hff, use tiled version to avoid stack overflow
     if (Hff > MAX_SWIGLU_STACK) {
         fused_mlp_swiglu_decode_tiled(x, W_gate, W_up, W_down,
                                       b_gate, b_up, b_down, output, D, Hff);
         return;
     }
 #if defined(__AVX512F__)
     // Stack-allocated swiglu buffer (max 32KB)
     float swiglu[MAX_SWIGLU_STACK] __attribute__((aligned(64)));
     // Phase 1: Compute all swiglu values (parallelize over Hff)
     #pragma omp parallel for schedule(static)
     for (int j = 0; j < Hff; j++) {
         const float *wg_row = &W_gate[j * D];
         const float *wu_row = &W_up[j * D];
         __m512 gate_acc = _mm512_setzero_ps();
         __m512 up_acc = _mm512_setzero_ps();
         int k = 0;
         for (; k <= D - 16; k += 16) {
             __m512 x_vec = _mm512_loadu_ps(&x[k]);
             __m512 wg_vec = _mm512_loadu_ps(&wg_row[k]);
             __m512 wu_vec = _mm512_loadu_ps(&wu_row[k]);
             gate_acc = _mm512_fmadd_ps(x_vec, wg_vec, gate_acc);
             up_acc = _mm512_fmadd_ps(x_vec, wu_vec, up_acc);
         }
         float gate = hsum512_ps(gate_acc);
         float up = hsum512_ps(up_acc);
         for (; k < D; k++) {
             gate += x[k] * wg_row[k];
             up += x[k] * wu_row[k];
         }
         if (b_gate) gate += b_gate[j];
         if (b_up) up += b_up[j];
         swiglu[j] = silu_scalar(gate) * up;
     }
     // Phase 2: Down projection (parallelize over D)
     #pragma omp parallel for schedule(static)
     for (int i = 0; i < D; i++) {
         const float *wd_row = &W_down[i * Hff];
         __m512 acc = _mm512_setzero_ps();
         int j = 0;
         for (; j <= Hff - 16; j += 16) {
             __m512 sw_vec = _mm512_loadu_ps(&swiglu[j]);
             __m512 wd_vec = _mm512_loadu_ps(&wd_row[j]);
             acc = _mm512_fmadd_ps(sw_vec, wd_vec, acc);
         }
         float sum = hsum512_ps(acc);
         for (; j < Hff; j++) {
             sum += swiglu[j] * wd_row[j];
         }
         output[i] = sum + (b_down ? b_down[i] : 0.0f);
     }
 #else
     // Scalar fallback with stack buffer
     float swiglu[MAX_SWIGLU_STACK];
     for (int j = 0; j < Hff; j++) {
         float gate = 0.0f, up = 0.0f;
         for (int k = 0; k < D; k++) {
             gate += x[k] * W_gate[j * D + k];
             up += x[k] * W_up[j * D + k];
         }
         if (b_gate) gate += b_gate[j];
         if (b_up) up += b_up[j];
         swiglu[j] = silu_scalar(gate) * up;
     }
     for (int i = 0; i < D; i++) {
         float sum = 0.0f;
         for (int j = 0; j < Hff; j++) {
             sum += swiglu[j] * W_down[i * Hff + j];
         }
         output[i] = sum + (b_down ? b_down[i] : 0.0f);
     }
 #endif
 }
References __attribute__(), fused_mlp_swiglu_decode_tiled(), MAX_SWIGLU_STACK, and silu_scalar().
Referenced by ck_mlp_swiglu_forward_fully_fused_token().
gelu_backward_exact()
void gelu_backward_exact (const float * input, const float * d_output, float * d_input, size_t n)
Definition at line 228 of file gelu_kernels.c.
 {
     const float sqrt_2_over_pi = 0.7978845608f;
     const float coeff = 0.044715f;
 #if defined(__AVX512F__)
     const __m512 sqrt_2_pi_vec = _mm512_set1_ps(sqrt_2_over_pi);
     const __m512 coeff_vec = _mm512_set1_ps(coeff);
     const __m512 coeff3_vec = _mm512_set1_ps(3.0f * coeff);
     const __m512 half_vec = _mm512_set1_ps(0.5f);
     const __m512 one_vec = _mm512_set1_ps(1.0f);
     size_t i = 0;
     for (; i + 16 <= n; i += 16) {
         __m512 x = _mm512_loadu_ps(&input[i]);
         __m512 dy = _mm512_loadu_ps(&d_output[i]);
         __m512 x2 = _mm512_mul_ps(x, x);
         __m512 x3 = _mm512_mul_ps(x2, x);
         // g = sqrt(2/pi) * (x + 0.044715 * x^3)
         __m512 g = _mm512_fmadd_ps(coeff_vec, x3, x);
         g = _mm512_mul_ps(sqrt_2_pi_vec, g);
         __m512 tanh_g = tanh512_fast(g);
         // g' = sqrt(2/pi) * (1 + 3 * 0.044715 * x^2)
         __m512 g_prime = _mm512_fmadd_ps(coeff3_vec, x2, one_vec);
         g_prime = _mm512_mul_ps(sqrt_2_pi_vec, g_prime);
         // sech^2(g) = 1 - tanh^2(g)
         __m512 sech2_g = _mm512_fnmadd_ps(tanh_g, tanh_g, one_vec);
         // gelu_derivative = 0.5 * (1 + tanh_g) + 0.5 * x * sech2_g * g_prime
         __m512 term1 = _mm512_mul_ps(half_vec, _mm512_add_ps(one_vec, tanh_g));
         __m512 term2 = _mm512_mul_ps(half_vec, _mm512_mul_ps(x, _mm512_mul_ps(sech2_g, g_prime)));
         __m512 gelu_deriv = _mm512_add_ps(term1, term2);
         __m512 result = _mm512_mul_ps(dy, gelu_deriv);
         _mm512_storeu_ps(&d_input[i], result);
     }
     // Handle remaining elements
     for (; i < n; ++i) {
         float x = input[i];
         float x3 = x * x * x;
         float g = sqrt_2_over_pi * (x + coeff * x3);
         float tanh_g = tanhf(g);
         float x2 = x * x;
         float g_prime = sqrt_2_over_pi * (1.0f + 3.0f * coeff * x2);
         float sech2_g = 1.0f - tanh_g * tanh_g;
         float gelu_derivative = 0.5f * (1.0f + tanh_g) + 0.5f * x * sech2_g * g_prime;
         d_input[i] = d_output[i] * gelu_derivative;
     }
 #elif defined(__AVX2__)
     const __m256 sqrt_2_pi_vec = _mm256_set1_ps(sqrt_2_over_pi);
     const __m256 coeff_vec = _mm256_set1_ps(coeff);
     const __m256 coeff3_vec = _mm256_set1_ps(3.0f * coeff);
     const __m256 half_vec = _mm256_set1_ps(0.5f);
     const __m256 one_vec = _mm256_set1_ps(1.0f);
     size_t i = 0;
     for (; i + 8 <= n; i += 8) {
         __m256 x = _mm256_loadu_ps(&input[i]);
         __m256 dy = _mm256_loadu_ps(&d_output[i]);
         __m256 x2 = _mm256_mul_ps(x, x);
         __m256 x3 = _mm256_mul_ps(x2, x);
         // g = sqrt(2/pi) * (x + 0.044715 * x^3)
         __m256 g = _mm256_fmadd_ps(coeff_vec, x3, x);
         g = _mm256_mul_ps(sqrt_2_pi_vec, g);
         __m256 tanh_g = tanh256_fast(g);
         // g' = sqrt(2/pi) * (1 + 3 * 0.044715 * x^2)
         __m256 g_prime = _mm256_fmadd_ps(coeff3_vec, x2, one_vec);
         g_prime = _mm256_mul_ps(sqrt_2_pi_vec, g_prime);
         // sech^2(g) = 1 - tanh^2(g)
         __m256 sech2_g = _mm256_fnmadd_ps(tanh_g, tanh_g, one_vec);
         // gelu_derivative = 0.5 * (1 + tanh_g) + 0.5 * x * sech2_g * g_prime
         __m256 term1 = _mm256_mul_ps(half_vec, _mm256_add_ps(one_vec, tanh_g));
         __m256 term2 = _mm256_mul_ps(half_vec, _mm256_mul_ps(x, _mm256_mul_ps(sech2_g, g_prime)));
         __m256 gelu_deriv = _mm256_add_ps(term1, term2);
         __m256 result = _mm256_mul_ps(dy, gelu_deriv);
         _mm256_storeu_ps(&d_input[i], result);
     }
     // Handle remaining elements
     for (; i < n; ++i) {
         float x = input[i];
         float x3 = x * x * x;
         float g = sqrt_2_over_pi * (x + coeff * x3);
         float tanh_g = tanhf(g);
         float x2 = x * x;
         float g_prime = sqrt_2_over_pi * (1.0f + 3.0f * coeff * x2);
         float sech2_g = 1.0f - tanh_g * tanh_g;
         float gelu_derivative = 0.5f * (1.0f + tanh_g) + 0.5f * x * sech2_g * g_prime;
         d_input[i] = d_output[i] * gelu_derivative;
     }
 #elif defined(__AVX__)
     // AVX1: Vectorize arithmetic, use scalar tanh
     const __m256 sqrt_2_pi_vec = _mm256_set1_ps(sqrt_2_over_pi);
     const __m256 coeff_vec = _mm256_set1_ps(coeff);
     const __m256 coeff3_vec = _mm256_set1_ps(3.0f * coeff);
     const __m256 half_vec = _mm256_set1_ps(0.5f);
     const __m256 one_vec = _mm256_set1_ps(1.0f);
     size_t i = 0;
     float g_arr[8] __attribute__((aligned(32)));
     float tanh_arr[8] __attribute__((aligned(32)));
     for (; i + 8 <= n; i += 8) {
         __m256 x = _mm256_loadu_ps(&input[i]);
         __m256 dy = _mm256_loadu_ps(&d_output[i]);
         __m256 x2 = _mm256_mul_ps(x, x);
         __m256 x3 = _mm256_mul_ps(x2, x);
         // g = sqrt(2/pi) * (x + 0.044715 * x^3)
         __m256 coeff_x3 = _mm256_mul_ps(coeff_vec, x3);
         __m256 g = _mm256_mul_ps(sqrt_2_pi_vec, _mm256_add_ps(x, coeff_x3));
         // Compute tanh scalarly
         _mm256_store_ps(g_arr, g);
         for (int j = 0; j < 8; ++j) {
             tanh_arr[j] = tanhf(g_arr[j]);
         }
         __m256 tanh_g = _mm256_load_ps(tanh_arr);
         // g' = sqrt(2/pi) * (1 + 3 * 0.044715 * x^2)
         __m256 coeff3_x2 = _mm256_mul_ps(coeff3_vec, x2);
         __m256 g_prime = _mm256_mul_ps(sqrt_2_pi_vec, _mm256_add_ps(one_vec, coeff3_x2));
         // sech^2(g) = 1 - tanh^2(g)
         __m256 tanh_g_sq = _mm256_mul_ps(tanh_g, tanh_g);
         __m256 sech2_g = _mm256_sub_ps(one_vec, tanh_g_sq);
         // gelu_derivative = 0.5 * (1 + tanh_g) + 0.5 * x * sech2_g * g_prime
         __m256 term1 = _mm256_mul_ps(half_vec, _mm256_add_ps(one_vec, tanh_g));
         __m256 term2 = _mm256_mul_ps(half_vec, _mm256_mul_ps(x, _mm256_mul_ps(sech2_g, g_prime)));
         __m256 gelu_deriv = _mm256_add_ps(term1, term2);
         __m256 result = _mm256_mul_ps(dy, gelu_deriv);
         _mm256_storeu_ps(&d_input[i], result);
     }
     // Handle remaining elements
     for (; i < n; ++i) {
         float x = input[i];
         float x3 = x * x * x;
         float g = sqrt_2_over_pi * (x + coeff * x3);
         float tanh_g = tanhf(g);
         float x2 = x * x;
         float g_prime = sqrt_2_over_pi * (1.0f + 3.0f * coeff * x2);
         float sech2_g = 1.0f - tanh_g * tanh_g;
         float gelu_derivative = 0.5f * (1.0f + tanh_g) + 0.5f * x * sech2_g * g_prime;
         d_input[i] = d_output[i] * gelu_derivative;
     }
 #else
     // Scalar fallback
     for (size_t i = 0; i < n; ++i) {
         float x = input[i];
         float x3 = x * x * x;
         float g = sqrt_2_over_pi * (x + coeff * x3);
         float tanh_g = tanhf(g);
         float x2 = x * x;
         float g_prime = sqrt_2_over_pi * (1.0f + 3.0f * coeff * x2);
         float sech2_g = 1.0f - tanh_g * tanh_g;
         float gelu_derivative =
             0.5f * (1.0f + tanh_g) + 0.5f * x * sech2_g * g_prime;
         d_input[i] = d_output[i] * gelu_derivative;
     }
 #endif
 }
References __attribute__().
gelu_backward_exact_bf16()
void gelu_backward_exact_bf16 (const uint16_t * input, const uint16_t * d_output, uint16_t * d_input, size_t n)
Definition at line 37 of file gelu_kernels_bf16.c.
 {
     float *input_f = alloc_float_buffer(n);
     float *d_output_f = alloc_float_buffer(n);
     float *d_input_f = alloc_float_buffer(n);
     if (!input_f || !d_output_f || !d_input_f) {
         free_float_buffer(input_f);
         free_float_buffer(d_output_f);
         free_float_buffer(d_input_f);
         return;
     }
     bf16_tensor_to_float(input, input_f, n);
     bf16_tensor_to_float(d_output, d_output_f, n);
     // Use scalar exact version to avoid fast tanh approximation error
     // accumulating with BF16 precision loss.
     gelu_backward_scalar(input_f, d_output_f, d_input_f, n);
     float_tensor_to_bf16(d_input_f, d_input, n);
     free_float_buffer(input_f);
     free_float_buffer(d_output_f);
     free_float_buffer(d_input_f);
 }
References alloc_float_buffer(), bf16_tensor_to_float(), float_tensor_to_bf16(), free_float_buffer(), and gelu_backward_scalar().
gelu_backward_fast()
void gelu_backward_fast (const float * input, const float * d_output, float * d_input, size_t n)
Definition at line 457 of file gelu_kernels.c.
 {
     const float beta = 1.702f;
 #if defined(__AVX512F__)
     const __m512 beta_vec = _mm512_set1_ps(beta);
     const __m512 one_vec = _mm512_set1_ps(1.0f);
     const __m512 neg_beta_vec = _mm512_set1_ps(-beta);
     size_t i = 0;
     for (; i + 16 <= n; i += 16) {
         __m512 x = _mm512_loadu_ps(&input[i]);
         __m512 dy = _mm512_loadu_ps(&d_output[i]);
         // s = sigmoid(beta * x) = 1 / (1 + exp(-beta * x))
         __m512 neg_beta_x = _mm512_mul_ps(neg_beta_vec, x);
         __m512 exp_neg = exp512_fast(neg_beta_x);
         __m512 s = _mm512_div_ps(one_vec, _mm512_add_ps(one_vec, exp_neg));
         // gelu_derivative = s * (1 + x * (1 - s) * beta)
         __m512 one_minus_s = _mm512_sub_ps(one_vec, s);
         __m512 inner = _mm512_fmadd_ps(_mm512_mul_ps(x, one_minus_s), beta_vec, one_vec);
         __m512 gelu_deriv = _mm512_mul_ps(s, inner);
         __m512 result = _mm512_mul_ps(dy, gelu_deriv);
         _mm512_storeu_ps(&d_input[i], result);
     }
     // Handle remaining elements
     for (; i < n; ++i) {
         float x = input[i];
         float s = 1.0f / (1.0f + expf(-beta * x));
         float gelu_derivative = s * (1.0f + x * (1.0f - s) * beta);
         d_input[i] = d_output[i] * gelu_derivative;
     }
 #elif defined(__AVX2__)
     const __m256 beta_vec = _mm256_set1_ps(beta);
     const __m256 one_vec = _mm256_set1_ps(1.0f);
     const __m256 neg_beta_vec = _mm256_set1_ps(-beta);
     size_t i = 0;
     for (; i + 8 <= n; i += 8) {
         __m256 x = _mm256_loadu_ps(&input[i]);
         __m256 dy = _mm256_loadu_ps(&d_output[i]);
         // s = sigmoid(beta * x) = 1 / (1 + exp(-beta * x))
         __m256 neg_beta_x = _mm256_mul_ps(neg_beta_vec, x);
         __m256 exp_neg = exp256_fast(neg_beta_x);
         __m256 s = _mm256_div_ps(one_vec, _mm256_add_ps(one_vec, exp_neg));
         // gelu_derivative = s * (1 + x * (1 - s) * beta)
         __m256 one_minus_s = _mm256_sub_ps(one_vec, s);
         __m256 inner = _mm256_fmadd_ps(_mm256_mul_ps(x, one_minus_s), beta_vec, one_vec);
         __m256 gelu_deriv = _mm256_mul_ps(s, inner);
         __m256 result = _mm256_mul_ps(dy, gelu_deriv);
         _mm256_storeu_ps(&d_input[i], result);
     }
     // Handle remaining elements
     for (; i < n; ++i) {
         float x = input[i];
         float s = 1.0f / (1.0f + expf(-beta * x));
         float gelu_derivative = s * (1.0f + x * (1.0f - s) * beta);
         d_input[i] = d_output[i] * gelu_derivative;
     }
 #elif defined(__AVX__)
     // AVX1: Vectorize arithmetic, use scalar exp
     const __m256 beta_vec = _mm256_set1_ps(beta);
     const __m256 one_vec = _mm256_set1_ps(1.0f);
     const __m256 neg_beta_vec = _mm256_set1_ps(-beta);
     size_t i = 0;
     float neg_beta_x_arr[8] __attribute__((aligned(32)));
     float exp_arr[8] __attribute__((aligned(32)));
     for (; i + 8 <= n; i += 8) {
         __m256 x = _mm256_loadu_ps(&input[i]);
         __m256 dy = _mm256_loadu_ps(&d_output[i]);
         // s = sigmoid(beta * x) = 1 / (1 + exp(-beta * x))
         __m256 neg_beta_x = _mm256_mul_ps(neg_beta_vec, x);
         // Compute exp scalarly
         _mm256_store_ps(neg_beta_x_arr, neg_beta_x);
         for (int j = 0; j < 8; ++j) {
             exp_arr[j] = expf(neg_beta_x_arr[j]);
         }
         __m256 exp_neg = _mm256_load_ps(exp_arr);
         __m256 s = _mm256_div_ps(one_vec, _mm256_add_ps(one_vec, exp_neg));
         // gelu_derivative = s * (1 + x * (1 - s) * beta)
         __m256 one_minus_s = _mm256_sub_ps(one_vec, s);
         __m256 x_one_minus_s = _mm256_mul_ps(x, one_minus_s);
         __m256 x_one_minus_s_beta = _mm256_mul_ps(x_one_minus_s, beta_vec);
         __m256 inner = _mm256_add_ps(one_vec, x_one_minus_s_beta);
         __m256 gelu_deriv = _mm256_mul_ps(s, inner);
         __m256 result = _mm256_mul_ps(dy, gelu_deriv);
         _mm256_storeu_ps(&d_input[i], result);
     }
     // Handle remaining elements
     for (; i < n; ++i) {
         float x = input[i];
         float s = 1.0f / (1.0f + expf(-beta * x));
         float gelu_derivative = s * (1.0f + x * (1.0f - s) * beta);
         d_input[i] = d_output[i] * gelu_derivative;
     }
 #else
     // Scalar fallback
     for (size_t i = 0; i < n; ++i) {
         float x = input[i];
         float s = 1.0f / (1.0f + expf(-beta * x));
         float gelu_derivative = s * (1.0f + x * (1.0f - s) * beta);
         d_input[i] = d_output[i] * gelu_derivative;
     }
 #endif
 }
References __attribute__().
Referenced by gelu_backward_fast_bf16().
gelu_backward_fast_bf16()
void gelu_backward_fast_bf16 (const uint16_t * input, const uint16_t * d_output, uint16_t * d_input, size_t n)
Definition at line 66 of file gelu_kernels_bf16.c.
 {
     float *input_f = alloc_float_buffer(n);
     float *d_output_f = alloc_float_buffer(n);
     float *d_input_f = alloc_float_buffer(n);
     if (!input_f || !d_output_f || !d_input_f) {
         free_float_buffer(input_f);
         free_float_buffer(d_output_f);
         free_float_buffer(d_input_f);
         return;
     }
     bf16_tensor_to_float(input, input_f, n);
     bf16_tensor_to_float(d_output, d_output_f, n);
     gelu_backward_fast(input_f, d_output_f, d_input_f, n);
     float_tensor_to_bf16(d_input_f, d_input, n);
     free_float_buffer(input_f);
     free_float_buffer(d_output_f);
     free_float_buffer(d_input_f);
 }
References alloc_float_buffer(), bf16_tensor_to_float(), float_tensor_to_bf16(), free_float_buffer(), and gelu_backward_fast().
gelu_backward_scalar()
void gelu_backward_scalar (const float * input, const float * d_output, float * d_input, size_t n)
Definition at line 433 of file gelu_kernels.c.
 {
     const float sqrt_2_over_pi = 0.7978845608f;
     const float coeff = 0.044715f;
     for (size_t i = 0; i < n; ++i) {
         float x = input[i];
         float x3 = x * x * x;
         float g = sqrt_2_over_pi * (x + coeff * x3);
         float tanh_g = tanhf(g);
         float x2 = x * x;
         float g_prime = sqrt_2_over_pi * (1.0f + 3.0f * coeff * x2);
         float sech2_g = 1.0f - tanh_g * tanh_g;
         float gelu_derivative = 0.5f * (1.0f + tanh_g) + 0.5f * x * sech2_g * g_prime;
         d_input[i] = d_output[i] * gelu_derivative;
     }
 }
Referenced by gelu_backward_exact_bf16().
gelu_exact_inplace()
void gelu_exact_inplace (float * data, size_t n)
Definition at line 417 of file gelu_kernels.c.
 {
     const float sqrt_2_over_pi = 0.7978845608f;
     const float coeff = 0.044715f;
     for (size_t i = 0; i < n; ++i) {
         float x = data[i];
         float x3 = x * x * x;
         float inner = sqrt_2_over_pi * (x + coeff * x3);
         data[i] = 0.5f * x * (1.0f + tanhf(inner));
     }
 }
Referenced by gelu_fast_inplace_bf16(), and mlp_token_parallel_exact().
gelu_fast_inplace()
void gelu_fast_inplace (float * data, size_t n)
Definition at line 103 of file gelu_kernels.c.
 {
     const float sqrt_2_over_pi = 0.7978845608f;
     const float coeff = 0.044715f;
 #if defined(__AVX512F__)
     const __m512 sqrt_2_pi_vec = _mm512_set1_ps(sqrt_2_over_pi);
     const __m512 coeff_vec = _mm512_set1_ps(coeff);
     const __m512 half_vec = _mm512_set1_ps(0.5f);
     const __m512 one_vec = _mm512_set1_ps(1.0f);
     size_t i = 0;
     for (; i + 16 <= n; i += 16) {
         __m512 x = _mm512_loadu_ps(&data[i]);
         __m512 x2 = _mm512_mul_ps(x, x);
         __m512 x3 = _mm512_mul_ps(x2, x);
         // inner = sqrt(2/pi) * (x + 0.044715 * x^3)
         __m512 inner = _mm512_fmadd_ps(coeff_vec, x3, x);
         inner = _mm512_mul_ps(sqrt_2_pi_vec, inner);
         // result = 0.5 * x * (1 + tanh(inner))
         __m512 tanh_val = tanh512_fast(inner);
         __m512 one_plus_tanh = _mm512_add_ps(one_vec, tanh_val);
         __m512 result = _mm512_mul_ps(half_vec, _mm512_mul_ps(x, one_plus_tanh));
         _mm512_storeu_ps(&data[i], result);
     }
     // Handle remaining elements
     for (; i < n; ++i) {
         float x = data[i];
         float x3 = x * x * x;
         float inner = sqrt_2_over_pi * (x + coeff * x3);
         data[i] = 0.5f * x * (1.0f + tanhf(inner));
     }
 #elif defined(__AVX2__)
     const __m256 sqrt_2_pi_vec = _mm256_set1_ps(sqrt_2_over_pi);
     const __m256 coeff_vec = _mm256_set1_ps(coeff);
     const __m256 half_vec = _mm256_set1_ps(0.5f);
     const __m256 one_vec = _mm256_set1_ps(1.0f);
     size_t i = 0;
     for (; i + 8 <= n; i += 8) {
         __m256 x = _mm256_loadu_ps(&data[i]);
         __m256 x2 = _mm256_mul_ps(x, x);
         __m256 x3 = _mm256_mul_ps(x2, x);
         // inner = sqrt(2/pi) * (x + 0.044715 * x^3)
         __m256 inner = _mm256_fmadd_ps(coeff_vec, x3, x);
         inner = _mm256_mul_ps(sqrt_2_pi_vec, inner);
         // result = 0.5 * x * (1 + tanh(inner))
         __m256 tanh_val = tanh256_fast(inner);
         __m256 one_plus_tanh = _mm256_add_ps(one_vec, tanh_val);
         __m256 result = _mm256_mul_ps(half_vec, _mm256_mul_ps(x, one_plus_tanh));
         _mm256_storeu_ps(&data[i], result);
     }
     // Handle remaining elements
     for (; i < n; ++i) {
         float x = data[i];
         float x3 = x * x * x;
         float inner = sqrt_2_over_pi * (x + coeff * x3);
         data[i] = 0.5f * x * (1.0f + tanhf(inner));
     }
 #elif defined(__AVX__)
     // AVX1: Vectorize arithmetic, use scalar tanh
     const __m256 sqrt_2_pi_vec = _mm256_set1_ps(sqrt_2_over_pi);
     const __m256 coeff_vec = _mm256_set1_ps(coeff);
     const __m256 half_vec = _mm256_set1_ps(0.5f);
     const __m256 one_vec = _mm256_set1_ps(1.0f);
     size_t i = 0;
     float inner_arr[8] __attribute__((aligned(32)));
     float tanh_arr[8] __attribute__((aligned(32)));
     for (; i + 8 <= n; i += 8) {
         __m256 x = _mm256_loadu_ps(&data[i]);
         __m256 x2 = _mm256_mul_ps(x, x);
         __m256 x3 = _mm256_mul_ps(x2, x);
         // inner = sqrt(2/pi) * (x + 0.044715 * x^3)
         __m256 coeff_x3 = _mm256_mul_ps(coeff_vec, x3);
         __m256 inner = _mm256_mul_ps(sqrt_2_pi_vec, _mm256_add_ps(x, coeff_x3));
         // Compute tanh scalarly
         _mm256_store_ps(inner_arr, inner);
         for (int j = 0; j < 8; ++j) {
             tanh_arr[j] = tanhf(inner_arr[j]);
         }
         __m256 tanh_val = _mm256_load_ps(tanh_arr);
         // result = 0.5 * x * (1 + tanh(inner))
         __m256 one_plus_tanh = _mm256_add_ps(one_vec, tanh_val);
         __m256 result = _mm256_mul_ps(half_vec, _mm256_mul_ps(x, one_plus_tanh));
         _mm256_storeu_ps(&data[i], result);
     }
     // Handle remaining elements
     for (; i < n; ++i) {
         float x = data[i];
         float x3 = x * x * x;
         float inner = sqrt_2_over_pi * (x + coeff * x3);
         data[i] = 0.5f * x * (1.0f + tanhf(inner));
     }
 #else
     // Scalar fallback
     for (size_t i = 0; i < n; ++i) {
         float x = data[i];
         float x3 = x * x * x;
         float inner = sqrt_2_over_pi * (x + coeff * x3);
         data[i] = 0.5f * x * (1.0f + tanhf(inner));
     }
 #endif
 }
References __attribute__().
Referenced by mlp_token_parallel().
gelu_fast_inplace_bf16()
void gelu_fast_inplace_bf16 (uint16_t * data, size_t n)
Definition at line 21 of file gelu_kernels_bf16.c.
 {
     float *tmp = alloc_float_buffer(n);
     if (!tmp) {
         return;
     }
     bf16_tensor_to_float(data, tmp, n);
     // Use exact version to avoid fast tanh approximation error accumulating
     // with BF16 precision loss. Conversion overhead dominates anyway.
     gelu_exact_inplace(tmp, n);
     float_tensor_to_bf16(tmp, data, n);
     free_float_buffer(tmp);
 }
References alloc_float_buffer(), bf16_tensor_to_float(), float_tensor_to_bf16(), free_float_buffer(), and gelu_exact_inplace().
gemm_avx512_parallel()
void gemm_avx512_parallel (const float * A, const float * B, const float * bias, float * C, int M, int N, int K)
Definition at line 130 of file gemm_kernels.c.
 {
     if (ck_strict_parity_enabled()) {
         gemm_naive_serial_double(A, B, bias, C, M, N, K);
         return;
     }
 #if defined(__AVX512F__)
 #pragma omp parallel for
     for (int i = 0; i < M; i++) {
         for (int j = 0; j < N; j++) {
             __m512 sum_vec = _mm512_setzero_ps();
             int k;
             for (k = 0; k <= K - 16; k += 16) {
                 __m512 a_vec = _mm512_loadu_ps(&A[i * K + k]);
                 __m512 b_vec = _mm512_loadu_ps(&B[j * K + k]);
                 sum_vec = _mm512_fmadd_ps(a_vec, b_vec, sum_vec);
             }
             float sum = _mm512_reduce_add_ps(sum_vec);
             for (; k < K; k++) {
                 sum += A[i * K + k] * B[j * K + k];
             }
             float bias_val = bias ? bias[j] : 0.0f;
             C[i * N + j] = sum + bias_val;
         }
     }
 #elif defined(__AVX__)
     // AVX1 path: 256-bit vectors, no FMA (use mul + add)
 #pragma omp parallel for
     for (int i = 0; i < M; i++) {
         for (int j = 0; j < N; j++) {
             __m256 sum_vec = _mm256_setzero_ps();
             int k;
             for (k = 0; k <= K - 8; k += 8) {
                 __m256 a_vec = _mm256_loadu_ps(&A[i * K + k]);
                 __m256 b_vec = _mm256_loadu_ps(&B[j * K + k]);
                 __m256 prod = _mm256_mul_ps(a_vec, b_vec);
                 sum_vec = _mm256_add_ps(sum_vec, prod);
             }
             float sum = hsum256_ps(sum_vec);
             for (; k < K; k++) {
                 sum += A[i * K + k] * B[j * K + k];
             }
             float bias_val = bias ? bias[j] : 0.0f;
             C[i * N + j] = sum + bias_val;
         }
     }
 #else
     gemm_naive_parallel(A, B, bias, C, M, N, K);
 #endif
 }
References C, ck_strict_parity_enabled(), gemm_naive_parallel(), and gemm_naive_serial_double().
gemm_bias_gelu_fused()
void gemm_bias_gelu_fused (const float * A, const float * B, const float * bias, float * C, int M, int N, int K)
Definition at line 121 of file gemm_fused_kernels.c.
 {
 #if defined(__AVX__)
 #pragma omp parallel for
     for (int i = 0; i < M; i++) {
         for (int j = 0; j < N; j++) {
             __m256 sum_vec = _mm256_setzero_ps();
             int k;
             for (k = 0; k <= K - 8; k += 8) {
                 __m256 a_vec = _mm256_loadu_ps(&A[i * K + k]);
                 __m256 b_vec = _mm256_loadu_ps(&B[j * K + k]);
                 __m256 prod = _mm256_mul_ps(a_vec, b_vec);
                 sum_vec = _mm256_add_ps(sum_vec, prod);
             }
             float sum = hsum256_ps_fused(sum_vec);
             for (; k < K; k++) {
                 sum += A[i * K + k] * B[j * K + k];
             }
             sum += bias[j];
             C[i * N + j] = fast_gelu_scalar(sum);
         }
     }
 #else
 #pragma omp parallel for
     for (int i = 0; i < M; i++) {
         for (int j = 0; j < N; j++) {
             float sum = 0.0f;
             for (int k = 0; k < K; k++) {
                 sum += A[i * K + k] * B[j * K + k];
             }
             sum += bias[j];
             C[i * N + j] = fast_gelu_scalar(sum);
         }
     }
 #endif
 }
References C, and fast_gelu_scalar().
gemm_bias_relu_fused()
void gemm_bias_relu_fused (const float * A, const float * B, const float * bias, float * C, int M, int N, int K)
Definition at line 74 of file gemm_fused_kernels.c.
 {
 #if defined(__AVX__)
 #pragma omp parallel for
     for (int i = 0; i < M; i++) {
         for (int j = 0; j < N; j++) {
             __m256 sum_vec = _mm256_setzero_ps();
             int k;
             for (k = 0; k <= K - 8; k += 8) {
                 __m256 a_vec = _mm256_loadu_ps(&A[i * K + k]);
                 __m256 b_vec = _mm256_loadu_ps(&B[j * K + k]);
                 __m256 prod = _mm256_mul_ps(a_vec, b_vec);
                 sum_vec = _mm256_add_ps(sum_vec, prod);
             }
             float sum = hsum256_ps_fused(sum_vec);
             for (; k < K; k++) {
                 sum += A[i * K + k] * B[j * K + k];
             }
             // Fused: add bias and ReLU while still in register
             sum += bias[j];
             C[i * N + j] = sum > 0.0f ? sum : 0.0f;
         }
     }
 #else
 #pragma omp parallel for
     for (int i = 0; i < M; i++) {
         for (int j = 0; j < N; j++) {
             float sum = 0.0f;
             for (int k = 0; k < K; k++) {
                 sum += A[i * K + k] * B[j * K + k];
             }
             sum += bias[j];
             C[i * N + j] = sum > 0.0f ? sum : 0.0f;
         }
     }
 #endif
 }
References C.
gemm_bias_silu_fused()
void gemm_bias_silu_fused (const float * A, const float * B, const float * bias, float * C, int M, int N, int K)
Definition at line 167 of file gemm_fused_kernels.c.
 {
 #if defined(__AVX__)
 #pragma omp parallel for
     for (int i = 0; i < M; i++) {
         for (int j = 0; j < N; j++) {
             __m256 sum_vec = _mm256_setzero_ps();
             int k;
             for (k = 0; k <= K - 8; k += 8) {
                 __m256 a_vec = _mm256_loadu_ps(&A[i * K + k]);
                 __m256 b_vec = _mm256_loadu_ps(&B[j * K + k]);
                 __m256 prod = _mm256_mul_ps(a_vec, b_vec);
                 sum_vec = _mm256_add_ps(sum_vec, prod);
             }
             float sum = hsum256_ps_fused(sum_vec);
             for (; k < K; k++) {
                 sum += A[i * K + k] * B[j * K + k];
             }
             sum += bias[j];
             // SiLU: x * sigmoid(x)
             float sig = 1.0f / (1.0f + expf(-sum));
             C[i * N + j] = sum * sig;
         }
     }
 #else
 #pragma omp parallel for
     for (int i = 0; i < M; i++) {
         for (int j = 0; j < N; j++) {
             float sum = 0.0f;
             for (int k = 0; k < K; k++) {
                 sum += A[i * K + k] * B[j * K + k];
             }
             sum += bias[j];
             float sig = 1.0f / (1.0f + expf(-sum));
             C[i * N + j] = sum * sig;
         }
     }
 #endif
 }
References C.
gemm_blocked_serial()
void gemm_blocked_serial (const float * A, const float * B, const float * bias, float * C, int M, int N, int K)
Definition at line 642 of file gemm_kernels.c.
 {
     // Ensure threads are initialized (auto-detects on first call)
     (void)ck_get_num_threads();
     if (ck_strict_parity_enabled()) {
         gemm_naive_serial_double(A, B, bias, C, M, N, K);
         return;
     }
     // Decode-time matvec (M=1) is extremely common and benefits from parallelism over N.
     // Lower threshold to parallelize more ops; OpenMP overhead is ~1-2μs per barrier.
     // For N*K >= 64K elements, parallel is worthwhile.
     if (M == 1 && (size_t)N * (size_t)K >= 65536) {
         gemm_nt_matvec_parallel(A, B, bias, C, N, K);
         return;
     }
     /*
      * Use gemm_microkernel for large matrices - it uses MKL/oneDNN when available,
      * which is substantially faster than our hand-written SIMD kernels.
      * B is stored as [N x K] (transposed), so we pass B_transposed=1.
      * Note: Use threshold of 32 to avoid numerical precision issues with small matrices.
      */
     if (M >= 32 && N >= 32 && K >= 32) {
         gemm_microkernel(A, B, C, M, N, K, 1);  // B_transposed=1
         ck_gemm_add_bias(C, bias, M, N);
         return;
     }
 #if defined(__AVX512F__)
     const int block_size = 64;
 #elif defined(__AVX__)
     const int block_size = 32;
 #else
     const int block_size = 32;
 #endif
     for (int i = 0; i < M; i++) {
         for (int j = 0; j < N; j++) {
             C[i * N + j] = bias ? bias[j] : 0.0f;
         }
     }
     for (int ii = 0; ii < M; ii += block_size) {
         for (int jj = 0; jj < N; jj += block_size) {
             for (int kk = 0; kk < K; kk += block_size) {
                 int i_end = ck_min(ii + block_size, M);
                 int j_end = ck_min(jj + block_size, N);
                 int k_end = ck_min(kk + block_size, K);
                 for (int i = ii; i < i_end; i++) {
                     for (int j = jj; j < j_end; j++) {
 #if defined(__AVX512F__)
                         __m512 sum_vec = _mm512_setzero_ps();
                         int k;
                         for (k = kk; k <= k_end - 16; k += 16) {
                             __m512 a_vec = _mm512_loadu_ps(&A[i * K + k]);
                             __m512 b_vec = _mm512_loadu_ps(&B[j * K + k]);
                             sum_vec = _mm512_fmadd_ps(a_vec, b_vec, sum_vec);
                         }
                         float partial_sum = _mm512_reduce_add_ps(sum_vec);
                         for (; k < k_end; k++) {
                             partial_sum += A[i * K + k] * B[j * K + k];
                         }
 #elif defined(__AVX__)
                         __m256 sum_vec = _mm256_setzero_ps();
                         int k;
                         for (k = kk; k <= k_end - 8; k += 8) {
                             __m256 a_vec = _mm256_loadu_ps(&A[i * K + k]);
                             __m256 b_vec = _mm256_loadu_ps(&B[j * K + k]);
                             __m256 prod = _mm256_mul_ps(a_vec, b_vec);
                             sum_vec = _mm256_add_ps(sum_vec, prod);
                         }
                         float partial_sum = hsum256_ps(sum_vec);
                         for (; k < k_end; k++) {
                             partial_sum += A[i * K + k] * B[j * K + k];
                         }
 #else
                         float partial_sum = 0.0f;
                         for (int k = kk; k < k_end; k++) {
                             partial_sum += A[i * K + k] * B[j * K + k];
                         }
 #endif
                         C[i * N + j] += partial_sum;
                     }
                 }
             }
         }
     }
 }
References C, ck_gemm_add_bias(), ck_get_num_threads(), ck_min(), ck_strict_parity_enabled(), gemm_microkernel(), gemm_naive_serial_double(), and gemm_nt_matvec_parallel().
Referenced by ck_attention_project_head_major(), ck_gemm_nt_quant(), ck_mlp_swiglu_forward(), ck_mlp_swiglu_forward_fused_token(), ck_qkv_project_head_major(), ck_qkv_project_head_major_token(), mlp_token_parallel(), and mlp_token_parallel_exact().
gemm_blocked_serial_bf16()
void gemm_blocked_serial_bf16 (const uint16_t * A, const uint16_t * B, const uint16_t * bias, uint16_t * C, int M, int N, int K)
Definition at line 262 of file gemm_kernels_bf16.c.
 {
     if (!A || !B || !C || M <= 0 || N <= 0 || K <= 0) {
         return;
     }
 #if HAVE_NATIVE_BF16
     /* Native BF16 instructions available (Ice Lake / Sapphire Rapids+) */
     gemm_bf16_native(A, B, bias, C, M, N, K);
 #elif defined(__AVX512F__)
     /* Use AVX-512F with software BF16 conversion */
     if (M * N > 4096) {
         gemm_bf16_blocked_avx512(A, B, bias, C, M, N, K);
     } else {
         gemm_bf16_avx512(A, B, bias, C, M, N, K);
     }
 #else
     /* Scalar fallback */
     gemm_bf16_scalar(A, B, bias, C, M, N, K);
 #endif
 }
References C.
gemm_fine_grained_parallel()
void gemm_fine_grained_parallel (const float * A, const float * B, const float * bias, float * C, int M, int N, int K)
Definition at line 186 of file gemm_kernels.c.
 {
     if (ck_strict_parity_enabled()) {
         gemm_naive_serial_double(A, B, bias, C, M, N, K);
         return;
     }
 #if defined(__AVX512F__)
     const int block_size = 64;
 #pragma omp parallel for
     for (int i = 0; i < M; i++) {
         for (int j = 0; j < N; j++) {
             C[i * N + j] = bias ? bias[j] : 0.0f;
         }
     }
 #pragma omp parallel for collapse(3)
     for (int ii = 0; ii < M; ii += block_size) {
         for (int jj = 0; jj < N; jj += block_size) {
             for (int kk = 0; kk < K; kk += block_size) {
                 int i_end = ck_min(ii + block_size, M);
                 int j_end = ck_min(jj + block_size, N);
                 int k_end = ck_min(kk + block_size, K);
                 for (int i = ii; i < i_end; i++) {
                     for (int j = jj; j < j_end; j++) {
                         __m512 sum_vec = _mm512_setzero_ps();
                         int k;
                         for (k = kk; k <= k_end - 16; k += 16) {
                             __m512 a_vec = _mm512_loadu_ps(&A[i * K + k]);
                             __m512 b_vec = _mm512_loadu_ps(&B[j * K + k]);
                             sum_vec = _mm512_fmadd_ps(a_vec, b_vec, sum_vec);
                         }
                         float partial_sum = _mm512_reduce_add_ps(sum_vec);
                         for (; k < k_end; k++) {
                             partial_sum += A[i * K + k] * B[j * K + k];
                         }
 #pragma omp atomic
                         C[i * N + j] += partial_sum;
                     }
                 }
             }
         }
     }
 #elif defined(__AVX__)
     // AVX1 cache-blocked version
     const int block_size = 32;  // Smaller block for L1 cache
 #pragma omp parallel for
     for (int i = 0; i < M; i++) {
         for (int j = 0; j < N; j++) {
             C[i * N + j] = bias ? bias[j] : 0.0f;
         }
     }
 #pragma omp parallel for collapse(3)
     for (int ii = 0; ii < M; ii += block_size) {
         for (int jj = 0; jj < N; jj += block_size) {
             for (int kk = 0; kk < K; kk += block_size) {
                 int i_end = ck_min(ii + block_size, M);
                 int j_end = ck_min(jj + block_size, N);
                 int k_end = ck_min(kk + block_size, K);
                 for (int i = ii; i < i_end; i++) {
                     for (int j = jj; j < j_end; j++) {
                         __m256 sum_vec = _mm256_setzero_ps();
                         int k;
                         for (k = kk; k <= k_end - 8; k += 8) {
                             __m256 a_vec = _mm256_loadu_ps(&A[i * K + k]);
                             __m256 b_vec = _mm256_loadu_ps(&B[j * K + k]);
                             __m256 prod = _mm256_mul_ps(a_vec, b_vec);
                             sum_vec = _mm256_add_ps(sum_vec, prod);
                         }
                         float partial_sum = hsum256_ps(sum_vec);
                         for (; k < k_end; k++) {
                             partial_sum += A[i * K + k] * B[j * K + k];
                         }
 #pragma omp atomic
                         C[i * N + j] += partial_sum;
                     }
                 }
             }
         }
     }
 #else
     gemm_naive_parallel(A, B, bias, C, M, N, K);
 #endif
 }
References C, ck_min(), ck_strict_parity_enabled(), gemm_naive_parallel(), and gemm_naive_serial_double().
gemm_microkernel()
void gemm_microkernel (const float * A, const float * B, float * C, int M, int N, int K, int B_transposed)
Definition at line 1124 of file gemm_microkernel.c.
 {
     if (B_transposed) {
         gemm_microkernel_blocked_bt(A, B, C, M, N, K);
     } else {
         // Use packed version for large matrices
         if (M >= PACK_THRESHOLD && N >= PACK_THRESHOLD && K >= PACK_THRESHOLD) {
             gemm_microkernel_packed(A, B, C, M, N, K);
         } else {
             gemm_microkernel_blocked(A, B, C, M, N, K);
         }
     }
 }
References C, gemm_microkernel_blocked(), gemm_microkernel_blocked_bt(), gemm_microkernel_packed(), and PACK_THRESHOLD.
Referenced by gemm_blocked_serial().
gemm_microkernel_blocked()
void gemm_microkernel_blocked (const float * A, const float * B, float * C, int M, int N, int K)
Definition at line 924 of file gemm_microkernel.c.
 {
     const int mr = MR;
     const int nr = NR;
     // Use sequential version for small matrices to avoid OpenMP overhead
     // Threshold tuned for typical 4-8 core systems
     if ((size_t)M * N * K <= 512ULL * 512 * 512) {
         gemm_microkernel_sequential(A, B, C, M, N, K);
         return;
     }
     // Initialize thread count to physical cores (once)
     gemm_init_threads();
     // Zero output first
     #pragma omp parallel for schedule(static)
     for (int i = 0; i < M; i++) {
         memset(&C[i * N], 0, N * sizeof(float));
     }
     // Block over K (outermost - for accumulation across all threads)
     for (int k0 = 0; k0 < K; k0 += KC) {
         int kb = (k0 + KC <= K) ? KC : (K - k0);
         int first_k = (k0 == 0);
         // Parallelize over M rows - each thread gets a chunk of M
         // This gives better cache locality than tile-level parallelism
         #pragma omp parallel for schedule(static)
         for (int m0 = 0; m0 < M; m0 += mr) {
             int mr_actual = (m0 + mr <= M) ? mr : (M - m0);
             // Each thread processes all N tiles for its M rows
             for (int n0 = 0; n0 < N; n0 += nr) {
                 int nr_actual = (n0 + nr <= N) ? nr : (N - n0);
                 const float *A_tile = &A[m0 * K + k0];
                 const float *B_tile = &B[k0 * N + n0];
                 float *C_tile = &C[m0 * N + n0];
                 if (mr_actual == mr && nr_actual == nr) {
 #if defined(__AVX512F__)
                     gemm_microkernel_6x32_avx512(kb, A_tile, K, B_tile, N, C_tile, N, first_k);
 #elif defined(__FMA__)
                     gemm_microkernel_6x16_avx(kb, A_tile, K, B_tile, N, C_tile, N, first_k);
 #elif defined(__AVX__)
                     gemm_microkernel_4x16_avx(kb, A_tile, K, B_tile, N, C_tile, N, first_k);
 #else
                     gemm_microkernel_edge(mr_actual, nr_actual, kb, A_tile, K, B_tile, N, C_tile, N, first_k);
 #endif
                 } else {
                     gemm_microkernel_edge(mr_actual, nr_actual, kb, A_tile, K, B_tile, N, C_tile, N, first_k);
                 }
             }
         }
     }
 }
References C, gemm_init_threads(), gemm_microkernel_edge(), gemm_microkernel_sequential(), KC, MR, and NR.
Referenced by gemm_microkernel(), and gemm_microkernel_packed().
gemm_microkernel_blocked_bt()
void gemm_microkernel_blocked_bt (const float * A, const float * B, float * C, int M, int N, int K)
Definition at line 1048 of file gemm_microkernel.c.
 {
     // Zero output first
     #pragma omp parallel for schedule(static)
     for (int i = 0; i < M; i++) {
         memset(&C[i * N], 0, N * sizeof(float));
     }
     const int mr = MR;
     const int nr = NR;
     #pragma omp parallel for schedule(dynamic) collapse(2)
     for (int m0 = 0; m0 < M; m0 += MC) {
         for (int n0 = 0; n0 < N; n0 += NC) {
             int mb = (m0 + MC <= M) ? MC : (M - m0);
             int nb = (n0 + NC <= N) ? NC : (N - n0);
             for (int k0 = 0; k0 < K; k0 += KC) {
                 int kb = (k0 + KC <= K) ? KC : (K - k0);
                 int first_k = (k0 == 0);
                 for (int m1 = 0; m1 < mb; m1 += mr) {
                     int mr_actual = (m1 + mr <= mb) ? mr : (mb - m1);
                     for (int n1 = 0; n1 < nb; n1 += nr) {
                         int nr_actual = (n1 + nr <= nb) ? nr : (nb - n1);
                         const float *A_tile = &A[(m0 + m1) * K + k0];
                         const float *B_tile = &B[(n0 + n1) * K + k0];
                         float *C_tile = &C[(m0 + m1) * N + (n0 + n1)];
                         if (mr_actual == mr && nr_actual == nr) {
 #if defined(__AVX512F__)
                             gemm_microkernel_6x32_bt_avx512(kb, A_tile, K, B_tile, K, C_tile, N, first_k);
 #else
                             // Scalar fallback for B-transposed
                             for (int i = 0; i < mr; i++) {
                                 for (int j = 0; j < nr; j++) {
                                     float sum = first_k ? 0.0f : C_tile[i * N + j];
                                     for (int kk = 0; kk < kb; kk++) {
                                         sum += A_tile[i * K + kk] * B_tile[j * K + kk];
                                     }
                                     C_tile[i * N + j] = sum;
                                 }
                             }
 #endif
                         } else {
                             // Edge case
                             for (int i = 0; i < mr_actual; i++) {
                                 for (int j = 0; j < nr_actual; j++) {
                                     float sum = first_k ? 0.0f : C_tile[i * N + j];
                                     for (int kk = 0; kk < kb; kk++) {
                                         sum += A_tile[i * K + kk] * B_tile[j * K + kk];
                                     }
                                     C_tile[i * N + j] = sum;
                                 }
                             }
                         }
                     }
                 }
             }
         }
     }
 }
References C, KC, MC, MR, NC, and NR.
Referenced by gemm_microkernel().
gemm_microkernel_packed()
void gemm_microkernel_packed (const float * A, const float * B, float * C, int M, int N, int K)
Definition at line 830 of file gemm_microkernel.c.
 {
     // Use tile-parallel blocked version - scales better on many-core systems
     gemm_microkernel_blocked(A, B, C, M, N, K);
 }
References C, and gemm_microkernel_blocked().
Referenced by gemm_microkernel().
gemm_naive_parallel()
void gemm_naive_parallel (const float * A, const float * B, const float * bias, float * C, int M, int N, int K)
Definition at line 106 of file gemm_kernels.c.
 {
     if (ck_strict_parity_enabled()) {
         gemm_naive_serial_double(A, B, bias, C, M, N, K);
         return;
     }
 #pragma omp parallel for
     for (int i = 0; i < M; i++) {
         for (int j = 0; j < N; j++) {
             float sum = 0.0f;
             for (int k = 0; k < K; k++) {
                 sum += A[i * K + k] * B[j * K + k];
             }
             float bias_val = bias ? bias[j] : 0.0f;
             C[i * N + j] = sum + bias_val;
         }
     }
 }
References C, ck_strict_parity_enabled(), and gemm_naive_serial_double().
Referenced by ck_attention_project_head_major_ref(), ck_mlp_swiglu_forward_ref(), ck_qkv_project_head_major_ref(), gemm_avx512_parallel(), and gemm_fine_grained_parallel().
gemm_nn_avx512()
void gemm_nn_avx512 (const float * A, const float * B, const float * bias, float * C, int M, int N, int K)
Definition at line 320 of file gemm_kernels.c.
 {
     if (ck_strict_parity_enabled()) {
         gemm_nn_serial_double(A, B, bias, C, M, N, K);
         return;
     }
 #if defined(__AVX512F__)
     // For gemm_nn, we can't vectorize over K easily since B[k,j] has stride N.
     // Instead, vectorize over N (output columns) when N >= 16.
 #pragma omp parallel for
     for (int i = 0; i < M; i++) {
         int j = 0;
         // Process 16 output columns at a time
         for (; j <= N - 16; j += 16) {
             __m512 sum_vec = bias ? _mm512_loadu_ps(&bias[j]) : _mm512_setzero_ps();
             for (int k = 0; k < K; k++) {
                 __m512 a_broadcast = _mm512_set1_ps(A[i * K + k]);
                 __m512 b_vec = _mm512_loadu_ps(&B[k * N + j]);
                 sum_vec = _mm512_fmadd_ps(a_broadcast, b_vec, sum_vec);
             }
             _mm512_storeu_ps(&C[i * N + j], sum_vec);
         }
         // Handle remaining columns
         for (; j < N; j++) {
             float sum = bias ? bias[j] : 0.0f;
             for (int k = 0; k < K; k++) {
                 sum += A[i * K + k] * B[k * N + j];
             }
             C[i * N + j] = sum;
         }
     }
 #elif defined(__AVX__)
     // AVX1: vectorize over N (8 columns at a time)
 #pragma omp parallel for
     for (int i = 0; i < M; i++) {
         int j = 0;
         for (; j <= N - 8; j += 8) {
             __m256 sum_vec = bias ? _mm256_loadu_ps(&bias[j]) : _mm256_setzero_ps();
             for (int k = 0; k < K; k++) {
                 __m256 a_broadcast = _mm256_set1_ps(A[i * K + k]);
                 __m256 b_vec = _mm256_loadu_ps(&B[k * N + j]);
                 __m256 prod = _mm256_mul_ps(a_broadcast, b_vec);
                 sum_vec = _mm256_add_ps(sum_vec, prod);
             }
             _mm256_storeu_ps(&C[i * N + j], sum_vec);
         }
         for (; j < N; j++) {
             float sum = bias ? bias[j] : 0.0f;
             for (int k = 0; k < K; k++) {
                 sum += A[i * K + k] * B[k * N + j];
             }
             C[i * N + j] = sum;
         }
     }
 #else
     gemm_nn_parallel(A, B, bias, C, M, N, K);
 #endif
 }
References C, ck_strict_parity_enabled(), gemm_nn_parallel(), and gemm_nn_serial_double().
Referenced by fc1_backward_kernel(), and fc2_backward_kernel().
gemm_nn_blocked()
void gemm_nn_blocked (const float * A, const float * B, const float * bias, float * C, int M, int N, int K)
Definition at line 383 of file gemm_kernels.c.
 {
     if (ck_strict_parity_enabled()) {
         gemm_nn_serial_double(A, B, bias, C, M, N, K);
         return;
     }
 #if defined(__AVX512F__)
     const int block_size = 64;
 #elif defined(__AVX__)
     const int block_size = 32;
 #else
     const int block_size = 32;
 #endif
     // Initialize C with bias (parallelized)
 #pragma omp parallel for
     for (int i = 0; i < M; i++) {
         for (int j = 0; j < N; j++) {
             C[i * N + j] = bias ? bias[j] : 0.0f;
         }
     }
     // Blocked multiply-accumulate (parallelized over M blocks)
 #pragma omp parallel for
     for (int ii = 0; ii < M; ii += block_size) {
         for (int kk = 0; kk < K; kk += block_size) {
             for (int jj = 0; jj < N; jj += block_size) {
                 int i_end = ck_min(ii + block_size, M);
                 int k_end = ck_min(kk + block_size, K);
                 int j_end = ck_min(jj + block_size, N);
                 for (int i = ii; i < i_end; i++) {
                     for (int k = kk; k < k_end; k++) {
                         float a_val = A[i * K + k];
 #if defined(__AVX512F__)
                         __m512 a_broadcast = _mm512_set1_ps(a_val);
                         int j;
                         for (j = jj; j <= j_end - 16; j += 16) {
                             __m512 b_vec = _mm512_loadu_ps(&B[k * N + j]);
                             __m512 c_vec = _mm512_loadu_ps(&C[i * N + j]);
                             c_vec = _mm512_fmadd_ps(a_broadcast, b_vec, c_vec);
                             _mm512_storeu_ps(&C[i * N + j], c_vec);
                         }
                         for (; j < j_end; j++) {
                             C[i * N + j] += a_val * B[k * N + j];
                         }
 #elif defined(__AVX__)
                         __m256 a_broadcast = _mm256_set1_ps(a_val);
                         int j;
                         for (j = jj; j <= j_end - 8; j += 8) {
                             __m256 b_vec = _mm256_loadu_ps(&B[k * N + j]);
                             __m256 c_vec = _mm256_loadu_ps(&C[i * N + j]);
                             __m256 prod = _mm256_mul_ps(a_broadcast, b_vec);
                             c_vec = _mm256_add_ps(c_vec, prod);
                             _mm256_storeu_ps(&C[i * N + j], c_vec);
                         }
                         for (; j < j_end; j++) {
                             C[i * N + j] += a_val * B[k * N + j];
                         }
 #else
                         for (int j = jj; j < j_end; j++) {
                             C[i * N + j] += a_val * B[k * N + j];
                         }
 #endif
                     }
                 }
             }
         }
     }
 }
References C, ck_min(), ck_strict_parity_enabled(), and gemm_nn_serial_double().
gemm_nn_parallel()
void gemm_nn_parallel (const float * A, const float * B, const float * bias, float * C, int M, int N, int K)
Definition at line 298 of file gemm_kernels.c.
 {
     if (ck_strict_parity_enabled()) {
         gemm_nn_serial_double(A, B, bias, C, M, N, K);
         return;
     }
 #pragma omp parallel for
     for (int i = 0; i < M; i++) {
         for (int j = 0; j < N; j++) {
             float sum = bias ? bias[j] : 0.0f;
             for (int k = 0; k < K; k++) {
                 sum += A[i * K + k] * B[k * N + j];
             }
             C[i * N + j] = sum;
         }
     }
 }
References C, ck_strict_parity_enabled(), and gemm_nn_serial_double().
Referenced by gemm_nn_avx512().
gemm_nt_q4_k()
void gemm_nt_q4_k (const float * A, const void * B, const float * bias, float * C, int M, int N, int K)
Definition at line 545 of file gemm_kernels_q4k.c.
 {
     if (!A || !B || !C) {
         return;
     }
     if (M <= 0 || N <= 0 || K <= 0) {
         return;
     }
     /* gemm_q4_k produces Y as [batch x M_out]. Here:
      *   batch = M (tokens)
      *   M_out = N (output channels) */
     gemm_q4_k(C, B, A, /*M_out=*/N, /*N_batch=*/M, K);
     if (!bias) {
         return;
     }
     for (int i = 0; i < M; ++i) {
         float *row = C + (size_t)i * (size_t)N;
         for (int j = 0; j < N; ++j) {
             row[j] += bias[j];
         }
     }
 }
References C, and gemm_q4_k().
Referenced by ck_attention_project_head_major_q4_k(), ck_attention_project_head_major_quant(), ck_gemm_nt_quant(), ck_layer_forward_rmsnorm_swiglu_decode_q4_k(), ck_layer_forward_rmsnorm_swiglu_decode_quant(), ck_mlp_swiglu_forward_q4_k(), ck_qkv_project_head_major_q4_k(), and ck_qkv_project_head_major_token_q4_k().
gemm_nt_q4_k_q8_k()
void gemm_nt_q4_k_q8_k (const void * A_q8, const void * B, const float * bias, float * C, int M, int N, int K)
Definition at line 197 of file gemm_kernels_q4k_q8k.c.
 {
     if (!A_q8 || !B || !C) {
         return;
     }
     if (M <= 0 || N <= 0 || K <= 0) {
         return;
     }
     gemm_q4_k_q8_k(C, B, A_q8, /*M_out=*/N, /*N_batch=*/M, K);
     if (!bias) {
         return;
     }
     for (int i = 0; i < M; ++i) {
         float *row = C + (size_t)i * (size_t)N;
         for (int j = 0; j < N; ++j) {
             row[j] += bias[j];
         }
     }
 }
References C, and gemm_q4_k_q8_k().
Referenced by ck_layer_forward_rmsnorm_swiglu_decode_q4_k(), ck_mlp_swiglu_forward_q4_k_q8_k(), and ck_qkv_project_head_major_token_q4_k_q8_k().
gemm_nt_q6_k()
void gemm_nt_q6_k (const float * A, const void * B, const float * bias, float * C, int M, int N, int K)
Definition at line 98 of file gemm_kernels_q6k.c.
 {
     if (!A || !B || !C) {
         return;
     }
     if (M <= 0 || N <= 0 || K <= 0) {
         return;
     }
     /* gemm_q6_k produces Y as [batch x M_out] where:
      *   batch = M (tokens)
      *   M_out = N (output channels) */
     gemm_q6_k(C, B, A, /*M_out=*/N, /*N_batch=*/M, K);
     if (!bias) {
         return;
     }
     for (int i = 0; i < M; ++i) {
         float *row = C + (size_t)i * (size_t)N;
         for (int j = 0; j < N; ++j) {
             row[j] += bias[j];
         }
     }
 }
References C, and gemm_q6_k().
Referenced by ck_attention_project_head_major_quant(), ck_gemm_nt_quant(), and ck_layer_forward_rmsnorm_swiglu_decode_quant().
gemm_q4_k()
void gemm_q4_k (float * Y, const void * W, const float * X, int M, int N, int K)
Auto-dispatch GEMM based on available SIMD.
Definition at line 337 of file gemm_kernels_q4k.c.
 {
 #ifdef __AVX512F__
     gemm_q4_k_avx512(Y, W, X, M, N, K);
 #else
     gemm_q4_k_ref(Y, W, X, M, N, K);
 #endif
 }
References gemm_q4_k_ref().
Referenced by gemm_nt_q4_k().
gemm_q4_k_q8_k()
void gemm_q4_k_q8_k (float * Y, const void * W, const void * X_q8, int M, int N, int K)
Definition at line 179 of file gemm_kernels_q4k_q8k.c.
 {
     if (!Y || !W || !X_q8 || M <= 0 || N <= 0 || K <= 0) {
         return;
     }
     const block_q8_K *X = (const block_q8_K *)X_q8;
     const int blocks_per_vec = K / QK_K;
     for (int n = 0; n < N; ++n) {
         const block_q8_K *x_row = X + (size_t)n * (size_t)blocks_per_vec;
         gemv_q4_k_q8_k(&Y[n * M], W, x_row, M, K);
     }
 }
References gemv_q4_k_q8_k(), and QK_K.
Referenced by gemm_nt_q4_k_q8_k().
gemm_q6_k()
void gemm_q6_k (float * Y, const void * W, const float * X, int M, int N, int K)
Definition at line 81 of file gemm_kernels_q6k.c.
 {
     if (!Y || !W || !X) {
         return;
     }
     if (M <= 0 || N <= 0 || K <= 0) {
         return;
     }
     for (int n = 0; n < N; ++n) {
         gemv_q6_k(&Y[n * M], W, &X[n * K], M, K);
     }
 }
References gemv_q6_k().
Referenced by gemm_nt_q6_k().
gemm_swiglu_fused()
void gemm_swiglu_fused (const float * x, const float * W_gate, const float * W_up, const float * b_gate, const float * b_up, float * output, int M, int N, int K)
Definition at line 231 of file gemm_fused_kernels.c.
 {
 #if defined(__AVX__)
 #pragma omp parallel for
     for (int i = 0; i < M; i++) {
         const float *x_row = &x[i * K];
         float *out_row = &output[i * N];
         for (int j = 0; j < N; j++) {
             const float *w_gate_row = &W_gate[j * K];
             const float *w_up_row = &W_up[j * K];
             // Compute both dot products in parallel using SIMD
             __m256 gate_vec = _mm256_setzero_ps();
             __m256 up_vec = _mm256_setzero_ps();
             int k;
             for (k = 0; k <= K - 8; k += 8) {
                 __m256 x_vec = _mm256_loadu_ps(&x_row[k]);
                 __m256 wg_vec = _mm256_loadu_ps(&w_gate_row[k]);
                 __m256 wu_vec = _mm256_loadu_ps(&w_up_row[k]);
                 // gate += x * W_gate
                 gate_vec = _mm256_add_ps(gate_vec, _mm256_mul_ps(x_vec, wg_vec));
                 // up += x * W_up
                 up_vec = _mm256_add_ps(up_vec, _mm256_mul_ps(x_vec, wu_vec));
             }
             // Horizontal sum
             float gate = hsum256_ps_fused(gate_vec);
             float up = hsum256_ps_fused(up_vec);
             // Scalar remainder
             for (; k < K; k++) {
                 gate += x_row[k] * w_gate_row[k];
                 up += x_row[k] * w_up_row[k];
             }
             // Add biases
             if (b_gate) gate += b_gate[j];
             if (b_up) up += b_up[j];
             // SwiGLU: SiLU(gate) * up = gate * sigmoid(gate) * up
             float sig = 1.0f / (1.0f + expf(-gate));
             out_row[j] = gate * sig * up;
         }
     }
 #else
     // Scalar fallback
 #pragma omp parallel for
     for (int i = 0; i < M; i++) {
         for (int j = 0; j < N; j++) {
             float gate = 0.0f;
             float up = 0.0f;
             for (int k = 0; k < K; k++) {
                 gate += x[i * K + k] * W_gate[j * K + k];
                 up += x[i * K + k] * W_up[j * K + k];
             }
             if (b_gate) gate += b_gate[j];
             if (b_up) up += b_up[j];
             // SwiGLU: SiLU(gate) * up
             float sig = 1.0f / (1.0f + expf(-gate));
             output[i * N + j] = gate * sig * up;
         }
     }
 #endif
 }
Referenced by ck_mlp_swiglu_forward_fused_token().
gemm_tn_avx512()
void gemm_tn_avx512 (const float * A, const float * B, const float * bias, float * C, int M, int N, int K)
Definition at line 502 of file gemm_kernels.c.
 {
     if (ck_strict_parity_enabled()) {
         gemm_tn_serial_double(A, B, bias, C, M, N, K);
         return;
     }
 #if defined(__AVX512F__)
     // Vectorize over N (output columns)
 #pragma omp parallel for
     for (int i = 0; i < M; i++) {
         int j = 0;
         for (; j <= N - 16; j += 16) {
             __m512 sum_vec = bias ? _mm512_loadu_ps(&bias[j]) : _mm512_setzero_ps();
             for (int k = 0; k < K; k++) {
                 __m512 a_broadcast = _mm512_set1_ps(A[k * M + i]);
                 __m512 b_vec = _mm512_loadu_ps(&B[k * N + j]);
                 sum_vec = _mm512_fmadd_ps(a_broadcast, b_vec, sum_vec);
             }
             _mm512_storeu_ps(&C[i * N + j], sum_vec);
         }
         for (; j < N; j++) {
             float sum = bias ? bias[j] : 0.0f;
             for (int k = 0; k < K; k++) {
                 sum += A[k * M + i] * B[k * N + j];
             }
             C[i * N + j] = sum;
         }
     }
 #elif defined(__AVX__)
     // AVX1: vectorize over N (8 columns at a time)
 #pragma omp parallel for
     for (int i = 0; i < M; i++) {
         int j = 0;
         for (; j <= N - 8; j += 8) {
             __m256 sum_vec = bias ? _mm256_loadu_ps(&bias[j]) : _mm256_setzero_ps();
             for (int k = 0; k < K; k++) {
                 __m256 a_broadcast = _mm256_set1_ps(A[k * M + i]);
                 __m256 b_vec = _mm256_loadu_ps(&B[k * N + j]);
                 __m256 prod = _mm256_mul_ps(a_broadcast, b_vec);
                 sum_vec = _mm256_add_ps(sum_vec, prod);
             }
             _mm256_storeu_ps(&C[i * N + j], sum_vec);
         }
         for (; j < N; j++) {
             float sum = bias ? bias[j] : 0.0f;
             for (int k = 0; k < K; k++) {
                 sum += A[k * M + i] * B[k * N + j];
             }
             C[i * N + j] = sum;
         }
     }
 #else
     gemm_tn_parallel(A, B, bias, C, M, N, K);
 #endif
 }
References C, ck_strict_parity_enabled(), gemm_tn_parallel(), and gemm_tn_serial_double().
Referenced by fc1_backward_kernel(), and fc2_backward_kernel().
gemm_tn_blocked()
void gemm_tn_blocked (const float * A, const float * B, const float * bias, float * C, int M, int N, int K)
Definition at line 562 of file gemm_kernels.c.
 {
     if (ck_strict_parity_enabled()) {
         gemm_tn_serial_double(A, B, bias, C, M, N, K);
         return;
     }
 #if defined(__AVX512F__)
     const int block_size = 64;
 #elif defined(__AVX__)
     const int block_size = 32;
 #else
     const int block_size = 32;
 #endif
     // Initialize C with bias (parallelized)
 #pragma omp parallel for
     for (int i = 0; i < M; i++) {
         for (int j = 0; j < N; j++) {
             C[i * N + j] = bias ? bias[j] : 0.0f;
         }
     }
     // Blocked multiply-accumulate (parallelized over M blocks)
 #pragma omp parallel for
     for (int ii = 0; ii < M; ii += block_size) {
         for (int kk = 0; kk < K; kk += block_size) {
             for (int jj = 0; jj < N; jj += block_size) {
                 int i_end = ck_min(ii + block_size, M);
                 int k_end = ck_min(kk + block_size, K);
                 int j_end = ck_min(jj + block_size, N);
                 for (int k = kk; k < k_end; k++) {
                     for (int i = ii; i < i_end; i++) {
                         float a_val = A[k * M + i];
 #if defined(__AVX512F__)
                         __m512 a_broadcast = _mm512_set1_ps(a_val);
                         int j;
                         for (j = jj; j <= j_end - 16; j += 16) {
                             __m512 b_vec = _mm512_loadu_ps(&B[k * N + j]);
                             __m512 c_vec = _mm512_loadu_ps(&C[i * N + j]);
                             c_vec = _mm512_fmadd_ps(a_broadcast, b_vec, c_vec);
                             _mm512_storeu_ps(&C[i * N + j], c_vec);
                         }
                         for (; j < j_end; j++) {
                             C[i * N + j] += a_val * B[k * N + j];
                         }
 #elif defined(__AVX__)
                         __m256 a_broadcast = _mm256_set1_ps(a_val);
                         int j;
                         for (j = jj; j <= j_end - 8; j += 8) {
                             __m256 b_vec = _mm256_loadu_ps(&B[k * N + j]);
                             __m256 c_vec = _mm256_loadu_ps(&C[i * N + j]);
                             __m256 prod = _mm256_mul_ps(a_broadcast, b_vec);
                             c_vec = _mm256_add_ps(c_vec, prod);
                             _mm256_storeu_ps(&C[i * N + j], c_vec);
                         }
                         for (; j < j_end; j++) {
                             C[i * N + j] += a_val * B[k * N + j];
                         }
 #else
                         for (int j = jj; j < j_end; j++) {
                             C[i * N + j] += a_val * B[k * N + j];
                         }
 #endif
                     }
                 }
             }
         }
     }
 }
References C, ck_min(), ck_strict_parity_enabled(), and gemm_tn_serial_double().
gemm_tn_parallel()
void gemm_tn_parallel (const float * A, const float * B, const float * bias, float * C, int M, int N, int K)
Definition at line 480 of file gemm_kernels.c.
 {
     if (ck_strict_parity_enabled()) {
         gemm_tn_serial_double(A, B, bias, C, M, N, K);
         return;
     }
 #pragma omp parallel for
     for (int i = 0; i < M; i++) {
         for (int j = 0; j < N; j++) {
             float sum = bias ? bias[j] : 0.0f;
             for (int k = 0; k < K; k++) {
                 sum += A[k * M + i] * B[k * N + j];
             }
             C[i * N + j] = sum;
         }
     }
 }
References C, ck_strict_parity_enabled(), and gemm_tn_serial_double().
Referenced by gemm_tn_avx512().
gemv_q4_k()
void gemv_q4_k (float * y, const void * W, const float * x, int M, int K)
Auto-dispatch GEMV based on available SIMD.
Definition at line 164 of file gemm_kernels_q4k.c.
 {
 #ifdef __AVX512F__
     gemv_q4_k_avx512(y, W, x, M, K);
 #else
     gemv_q4_k_ref(y, W, x, M, K);
 #endif
 }
References gemv_q4_k_ref().
Referenced by dot_q4_k().
gemv_q4_k_q8_k()
void gemv_q4_k_q8_k (float * y, const void * W, const void * x_q8, int M, int K)
Definition at line 147 of file gemm_kernels_q4k_q8k.c.
 {
 #if defined(__AVX512VNNI__) && defined(__AVX512VL__)
     gemv_q4_k_q8_k_vnni(y, W, x_q8, M, K);
 #elif defined(__AVX2__)
     gemv_q4_k_q8_k_avx2(y, W, x_q8, M, K);
 #else
     gemv_q4_k_q8_k_ref(y, W, x_q8, M, K);
 #endif
 }
References gemv_q4_k_q8_k_avx2(), gemv_q4_k_q8_k_ref(), and gemv_q4_k_q8_k_vnni().
Referenced by gemm_q4_k_q8_k().
gemv_q6_k()
void gemv_q6_k (float * y, const void * W, const float * x, int M, int K)
Definition at line 60 of file gemm_kernels_q6k.c.
 {
     if (!y || !W || !x) {
         return;
     }
     if (M <= 0 || K <= 0) {
         return;
     }
     const block_q6_K *blocks = (const block_q6_K *)W;
     const int blocks_per_row = K / QK_K;
     for (int row = 0; row < M; ++row) {
         const block_q6_K *w_row = blocks + (size_t)row * (size_t)blocks_per_row;
         y[row] = dot_q6_k_ref(w_row, x, K);
     }
 }
References dot_q6_k_ref(), and QK_K.
Referenced by gemm_q6_k().
im2patch()
void im2patch (const float * image, float * patches, int C, int H, int W, int P)
im2patch: Transforms an image into a sequence of flattened patches.
Image Layout: [C, H, W] (Row-major: W is fastest moving) Output Layout: [num_patches, C * P * P]
num_patches = (H/P) * (W/P) P = patch_size
Definition at line 14 of file vision_kernels.c.
 {
     int num_patches_h = H / P;
     int num_patches_w = W / P;
     int patch_dim = C * P * P;
     // ph, pw: patch grid coordinates
     for (int ph = 0; ph < num_patches_h; ++ph) {
         for (int pw = 0; pw < num_patches_w; ++pw) {
             int patch_idx = ph * num_patches_w + pw;
             float *dst_patch = patches + (size_t)patch_idx * patch_dim;
             // For each patch, grab pixels from all channels
             for (int c = 0; c < C; ++c) {
                 for (int py = 0; py < P; ++py) {
                     int y = ph * P + py;
                     int x = pw * P;
                     // Input row start in the image
                     const float *src_row = image + (size_t)c * H * W + (size_t)y * W + x;
                     // Destination row in the flattened patch sequence
                     float *dst_row = dst_patch + (size_t)c * P * P + (size_t)py * P;
                     // Copy P pixels (one row of the patch)
                     memcpy(dst_row, src_row, P * sizeof(float));
                 }
             }
         }
     }
 }
References C.
im2patch_bf16()
void im2patch_bf16 (const uint16_t * image, uint16_t * patches, int C, int H, int W, int P)
Definition at line 8 of file vision_kernels_bf16.c.
 {
     if (!image || !patches || C <= 0 || H <= 0 || W <= 0 || P <= 0) {
         return;
     }
     int num_patches_h = H / P;
     int num_patches_w = W / P;
     int patch_dim = C * P * P;
     for (int ph = 0; ph < num_patches_h; ++ph) {
         for (int pw = 0; pw < num_patches_w; ++pw) {
             int patch_idx = ph * num_patches_w + pw;
             uint16_t *dst_patch = patches + (size_t)patch_idx * (size_t)patch_dim;
             for (int c = 0; c < C; ++c) {
                 for (int py = 0; py < P; ++py) {
                     int y = ph * P + py;
                     int x = pw * P;
                     const uint16_t *src_row = image + (size_t)c * (size_t)H * (size_t)W + (size_t)y * (size_t)W + (size_t)x;
                     uint16_t *dst_row = dst_patch + (size_t)c * (size_t)P * (size_t)P + (size_t)py * (size_t)P;
                     memcpy(dst_row, src_row, (size_t)P * sizeof(uint16_t));
                 }
             }
         }
     }
 }
References C.
kv_cache_repack_head_major_inplace()
void kv_cache_repack_head_major_inplace (float * buf, int num_heads, int tokens, int cache_capacity, int aligned_head_dim)
Definition at line 16 of file kv_cache_kernels.c.
 {
     if (!buf) {
         return;
     }
     if (num_heads <= 0 || tokens <= 0 || cache_capacity <= 0 || aligned_head_dim <= 0) {
         return;
     }
     if (tokens > cache_capacity) {
         tokens = cache_capacity;
     }
     if (tokens == cache_capacity) {
         return;
     }
     const size_t old_head_stride = (size_t)tokens * (size_t)aligned_head_dim;
     const size_t new_head_stride = (size_t)cache_capacity * (size_t)aligned_head_dim;
     const size_t bytes = (size_t)tokens * (size_t)aligned_head_dim * sizeof(float);
     // Move head blocks from high to low to avoid overwriting source data
     // for heads that have not yet been moved.
     for (int h = num_heads - 1; h >= 0; --h) {
         float *src = buf + (size_t)h * old_head_stride;
         float *dst = buf + (size_t)h * new_head_stride;
         memmove(dst, src, bytes);
     }
 }
kv_cache_write_head_major()
void kv_cache_write_head_major (const float * k_token, const float * v_token, float * k_cache, float * v_cache, int num_kv_heads, int token_index, int cache_capacity, int head_dim, int aligned_head_dim)
Definition at line 48 of file kv_cache_kernels.c.
 {
     if (!k_token || !v_token || !k_cache || !v_cache) {
         return;
     }
     if (num_kv_heads <= 0 || token_index < 0 || cache_capacity <= 0) {
         return;
     }
     if (token_index >= cache_capacity || head_dim <= 0 || aligned_head_dim <= 0) {
         return;
     }
     const size_t head_stride = (size_t)cache_capacity * (size_t)aligned_head_dim;
     const size_t token_stride = (size_t)aligned_head_dim;
     for (int h = 0; h < num_kv_heads; ++h) {
         const float *k_src = k_token + (size_t)h * token_stride;
         const float *v_src = v_token + (size_t)h * token_stride;
         float *k_dst = k_cache + (size_t)h * head_stride + (size_t)token_index * token_stride;
         float *v_dst = v_cache + (size_t)h * head_stride + (size_t)token_index * token_stride;
         if (head_dim == aligned_head_dim) {
             memcpy(k_dst, k_src, (size_t)aligned_head_dim * sizeof(float));
             memcpy(v_dst, v_src, (size_t)aligned_head_dim * sizeof(float));
         } else {
             for (int d = 0; d < head_dim; ++d) {
                 k_dst[d] = k_src[d];
                 v_dst[d] = v_src[d];
             }
             for (int d = head_dim; d < aligned_head_dim; ++d) {
                 k_dst[d] = 0.0f;
                 v_dst[d] = 0.0f;
             }
         }
     }
 }
Referenced by ck_layer_forward_rmsnorm_swiglu_decode(), ck_layer_forward_rmsnorm_swiglu_decode_fused(), ck_layer_forward_rmsnorm_swiglu_decode_fused_attn_impl(), ck_layer_forward_rmsnorm_swiglu_decode_q4_k(), and ck_layer_forward_rmsnorm_swiglu_decode_quant().
layernorm_backward_kernel()
void layernorm_backward_kernel (const float * d_output, const float * input, const float * gamma, const float * mean, const float * rstd, float * d_input, float * d_gamma, float * d_beta, int tokens, int d_model, int aligned_embed_dim)
Definition at line 652 of file layernorm_kernels.c.
 {
     int T = tokens;
     int D = d_model;
     int aligned_D = aligned_embed_dim;
     // Per-token input gradients
     for (int t = 0; t < T; ++t) {
         float mean_t = mean[t];
         float rstd_t = rstd[t];
         float d_y_gamma_sum = 0.0f;
         float d_y_gamma_xhat_sum = 0.0f;
         // First pass: compute sums
         for (int d = 0; d < D; ++d) {
             float x = input[t * aligned_D + d];
             float x_hat = (x - mean_t) * rstd_t;
             float d_y = d_output[t * aligned_D + d];
             float d_y_gamma = d_y * gamma[d];
             d_y_gamma_sum += d_y_gamma;
             d_y_gamma_xhat_sum += d_y_gamma * x_hat;
         }
         // Second pass: compute input gradients
         float scale = rstd_t / (float)D;
         for (int d = 0; d < D; ++d) {
             float x = input[t * aligned_D + d];
             float x_hat = (x - mean_t) * rstd_t;
             float d_y = d_output[t * aligned_D + d];
             d_input[t * aligned_D + d] =
                 scale * ((float)D * d_y * gamma[d] - d_y_gamma_sum - x_hat * d_y_gamma_xhat_sum);
         }
         // Zero padding for aligned dimension beyond D
         for (int d = D; d < aligned_D; ++d) {
             d_input[t * aligned_D + d] = 0.0f;
         }
     }
     // Parameter gradients (gamma, beta)
     for (int d = 0; d < D; ++d) {
         float gamma_grad = 0.0f;
         float beta_grad = 0.0f;
         for (int t = 0; t < T; ++t) {
             float x = input[t * aligned_D + d];
             float x_hat = (x - mean[t]) * rstd[t];
             float d_y = d_output[t * aligned_D + d];
             gamma_grad += d_y * x_hat;
             beta_grad += d_y;
         }
         d_gamma[d] += gamma_grad;
         d_beta[d] += beta_grad;
     }
 }
Referenced by layernorm_backward_kernel_bf16().
layernorm_backward_kernel_bf16()
void layernorm_backward_kernel_bf16 (const uint16_t * d_output, const uint16_t * input, const float * gamma, const float * mean, const float * rstd, uint16_t * d_input, float * d_gamma, float * d_beta, int tokens, int d_model, int aligned_embed_dim)
Definition at line 83 of file layernorm_kernels_bf16.c.
 {
     size_t total = (size_t)tokens * (size_t)aligned_embed_dim;
     float *d_output_f = alloc_float_buffer(total);
     float *input_f = alloc_float_buffer(total);
     float *d_input_f = alloc_float_buffer(total);
     if (!d_output_f || !input_f || !d_input_f) {
         free_float_buffer(d_output_f);
         free_float_buffer(input_f);
         free_float_buffer(d_input_f);
         return;
     }
     bf16_tensor_to_float(d_output, d_output_f, total);
     bf16_tensor_to_float(input, input_f, total);
     layernorm_backward_kernel(d_output_f, input_f, gamma, mean, rstd,
                               d_input_f, d_gamma, d_beta,
                               tokens, d_model, aligned_embed_dim);
     float_tensor_to_bf16(d_input_f, d_input, total);
     free_float_buffer(d_output_f);
     free_float_buffer(input_f);
     free_float_buffer(d_input_f);
 }
References alloc_float_buffer(), bf16_tensor_to_float(), float_tensor_to_bf16(), free_float_buffer(), and layernorm_backward_kernel().
layernorm_forward_rolled_slice()
void layernorm_forward_rolled_slice (const float *__restrict input_slice_base, const float *__restrict gamma, const float *__restrict beta, float *__restrict output_slice_base, float *__restrict mean_cache_slice, float *__restrict rstd_cache_slice, int num_tokens_in_slice, int d_model, int aligned_embed_dim, float eps)
Definition at line 258 of file layernorm_kernels.c.
 {
 #if defined(__AVX512F__)
     layernorm_forward_rolled_slice_avx512(input_slice_base, gamma, beta,
                                            output_slice_base, mean_cache_slice, rstd_cache_slice,
                                            num_tokens_in_slice, d_model, aligned_embed_dim, eps);
 #elif defined(__AVX2__) || defined(__AVX__)
     layernorm_forward_rolled_slice_avx256(input_slice_base, gamma, beta,
                                            output_slice_base, mean_cache_slice, rstd_cache_slice,
                                            num_tokens_in_slice, d_model, aligned_embed_dim, eps);
 #else
     layernorm_naive_serial(input_slice_base, gamma, beta,
                            output_slice_base, mean_cache_slice, rstd_cache_slice,
                            num_tokens_in_slice, d_model, aligned_embed_dim, eps);
 #endif
 }
References layernorm_naive_serial().
Referenced by layernorm_forward_rolled_slice_bf16().
layernorm_forward_rolled_slice_bf16()
void layernorm_forward_rolled_slice_bf16 (const uint16_t *__restrict input_slice_base, const float *__restrict gamma, const float *__restrict beta, uint16_t *__restrict output_slice_base, float *__restrict mean_cache_slice, float *__restrict rstd_cache_slice, int num_tokens_in_slice, int d_model, int aligned_embed_dim, float eps)
Definition at line 22 of file layernorm_kernels_bf16.c.
 {
     size_t total = (size_t)num_tokens_in_slice * (size_t)aligned_embed_dim;
     float *input_f = alloc_float_buffer(total);
     float *output_f = alloc_float_buffer(total);
     if (!input_f || !output_f) {
         free_float_buffer(input_f);
         free_float_buffer(output_f);
         return;
     }
     bf16_tensor_to_float(input_slice_base, input_f, total);
     layernorm_forward_rolled_slice(input_f, gamma, beta,
                                    output_f, mean_cache_slice, rstd_cache_slice,
                                    num_tokens_in_slice, d_model, aligned_embed_dim, eps);
     float_tensor_to_bf16(output_f, output_slice_base, total);
     free_float_buffer(input_f);
     free_float_buffer(output_f);
 }
References alloc_float_buffer(), bf16_tensor_to_float(), float_tensor_to_bf16(), free_float_buffer(), and layernorm_forward_rolled_slice().
layernorm_forward_unrolled_slice()
void layernorm_forward_unrolled_slice (const float *__restrict input_slice_base, const float *__restrict gamma, const float *__restrict beta, float *__restrict output_slice_base, float *__restrict mean_cache_slice, float *__restrict rstd_cache_slice, int num_tokens_in_slice, int d_model, float eps)
Definition at line 582 of file layernorm_kernels.c.
 {
 #if defined(__AVX512F__)
     layernorm_forward_unrolled_slice_avx512(input_slice_base, gamma, beta,
                                              output_slice_base, mean_cache_slice, rstd_cache_slice,
                                              num_tokens_in_slice, d_model, eps);
 #elif defined(__AVX2__) || defined(__AVX__)
     layernorm_forward_unrolled_slice_avx256(input_slice_base, gamma, beta,
                                              output_slice_base, mean_cache_slice, rstd_cache_slice,
                                              num_tokens_in_slice, d_model, eps);
 #else
     layernorm_forward_unrolled_slice_scalar(input_slice_base, gamma, beta,
                                             output_slice_base, mean_cache_slice, rstd_cache_slice,
                                             num_tokens_in_slice, d_model, eps);
 #endif
 }
References layernorm_forward_unrolled_slice_scalar().
Referenced by layernorm_forward_unrolled_slice_bf16().
layernorm_forward_unrolled_slice_bf16()
void layernorm_forward_unrolled_slice_bf16 (const uint16_t *__restrict input_slice_base, const float *__restrict gamma, const float *__restrict beta, uint16_t *__restrict output_slice_base, float *__restrict mean_cache_slice, float *__restrict rstd_cache_slice, int num_tokens_in_slice, int d_model, float eps)
Definition at line 53 of file layernorm_kernels_bf16.c.
 {
     size_t total = (size_t)num_tokens_in_slice * (size_t)d_model;
     float *input_f = alloc_float_buffer(total);
     float *output_f = alloc_float_buffer(total);
     if (!input_f || !output_f) {
         free_float_buffer(input_f);
         free_float_buffer(output_f);
         return;
     }
     bf16_tensor_to_float(input_slice_base, input_f, total);
     layernorm_forward_unrolled_slice(input_f, gamma, beta,
                                      output_f, mean_cache_slice, rstd_cache_slice,
                                      num_tokens_in_slice, d_model, eps);
     float_tensor_to_bf16(output_f, output_slice_base, total);
     free_float_buffer(input_f);
     free_float_buffer(output_f);
 }
References alloc_float_buffer(), bf16_tensor_to_float(), float_tensor_to_bf16(), free_float_buffer(), and layernorm_forward_unrolled_slice().
layernorm_naive_serial()
void layernorm_naive_serial (const float * input, const float * gamma, const float * beta, float * output, float * mean_cache, float * rstd_cache, int tokens, int d_model, int aligned_embed_dim, float eps)
Definition at line 35 of file layernorm_kernels.c.
 {
     for (int t = 0; t < tokens; ++t) {
         const float *in_ptr = input + t * aligned_embed_dim;
         float *out_ptr = output + t * aligned_embed_dim;
         float sum_val = 0.0f;
         for (int i = 0; i < d_model; ++i) {
             sum_val += in_ptr[i];
         }
         float mean = sum_val / (float)d_model;
         float sum_sq_diff = 0.0f;
         for (int i = 0; i < d_model; ++i) {
             float diff = in_ptr[i] - mean;
             sum_sq_diff += diff * diff;
         }
         float variance = sum_sq_diff / (float)d_model + eps;
         double var_double = (double)variance;
         float inv_std = (float)(1.0 / sqrt(var_double));
         for (int i = 0; i < d_model; ++i) {
             float normalized_val = (in_ptr[i] - mean) * inv_std;
             out_ptr[i] = normalized_val * gamma[i] + beta[i];
         }
         if (mean_cache) {
             mean_cache[t] = mean;
         }
         if (rstd_cache) {
             rstd_cache[t] = inv_std;
         }
         /* Keep aligned padding quiet so future GEMMs see deterministic memory. */
         if (aligned_embed_dim > d_model) {
             /* Keep padded lanes zeroed so subsequent GEMMs never read stale data. */
             for (int i = d_model; i < aligned_embed_dim; ++i) {
                 out_ptr[i] = 0.0f;
             }
         }
     }
 }
Referenced by layernorm_forward_rolled_slice().
layernorm_naive_serial_matched_precision()
void layernorm_naive_serial_matched_precision (const float * input, const float * gamma, const float * beta, float * output, float * mean_cache, float * rstd_cache, int tokens, int d_model, float eps)
Definition at line 608 of file layernorm_kernels.c.
 {
     for (int t = 0; t < tokens; ++t) {
         const float *in_ptr = input + t * d_model;
         float *out_ptr = output + t * d_model;
         float sum_val = 0.0f;
         for (int i = 0; i < d_model; ++i) {
             sum_val += in_ptr[i];
         }
         float mean = sum_val / (float)d_model;
         float sum_sq_diff = 0.0f;
         for (int i = 0; i < d_model; ++i) {
             float diff = in_ptr[i] - mean;
             sum_sq_diff += diff * diff;
         }
         float variance = sum_sq_diff / (float)d_model + eps;
         double var_double = (double)variance;
         float inv_std = (float)(1.0 / sqrt(var_double));
         for (int i = 0; i < d_model; ++i) {
             float normalized_val = (in_ptr[i] - mean) * inv_std;
             out_ptr[i] = normalized_val * gamma[i] + beta[i];
         }
         if (mean_cache) {
             mean_cache[t] = mean;
         }
         if (rstd_cache) {
             rstd_cache[t] = inv_std;
         }
     }
 }
Referenced by layernorm_forward_unrolled_slice_scalar().
mlp_token_parallel()
void mlp_token_parallel (const float * input, const float * W_fc1, const float * b_fc1, const float * W_fc2, const float * b_fc2, float * fc1_output, float * output, int T, int aligned_dim, int num_threads)
Definition at line 22 of file mlp_kernels.c.
 {
     int D = aligned_dim;
     int fourD = 4 * D;
     // FC1: [T × D] · [D × 4D] -> [T × 4D]
     // Our GEMM layout: A[M×K], B[N×K], so B is [4D × D].
     gemm_blocked_serial(input, W_fc1, b_fc1,
                         fc1_output,
                         T,      // M
                         fourD,  // N
                         D);     // K
     // GELU in-place on FC1 output
     gelu_fast_inplace(fc1_output, (size_t)T * (size_t)fourD);
     // FC2: [T × 4D] · [4D × D] -> [T × D]
     gemm_blocked_serial(fc1_output, W_fc2, b_fc2,
                         output,
                         T,  // M
                         D,  // N
                         fourD); // K
 }
References gelu_fast_inplace(), and gemm_blocked_serial().
mlp_token_parallel_bf16()
void mlp_token_parallel_bf16 (const uint16_t * input, const uint16_t * W_fc1, const uint16_t * b_fc1, const uint16_t * W_fc2, const uint16_t * b_fc2, float * fc1_output, float * output, int T, int aligned_dim, int num_threads)
Optimized MLP Forward (BF16 weights, FP32 activations)
This version:
Uses optimized BF16 GEMM directly (no bulk conversion)
Keeps activations in FP32 for GELU accuracy
Vectorized GELU with AVX-512
Definition at line 85 of file mlp_kernels_bf16.c.
 {
     if (!input || !W_fc1 || !b_fc1 || !W_fc2 || !b_fc2 || !fc1_output || !output) {
         return;
     }
     const int D = aligned_dim;
     const int fourD = 4 * D;
     /* Convert biases to FP32 (small, one-time cost) */
     float *bias1_f = (float *)malloc(fourD * sizeof(float));
     float *bias2_f = (float *)malloc(D * sizeof(float));
     if (!bias1_f || !bias2_f) {
         free(bias1_f);
         free(bias2_f);
         return;
     }
     for (int i = 0; i < fourD; ++i) {
         bias1_f[i] = bf16_to_float(b_fc1[i]);
     }
     for (int i = 0; i < D; ++i) {
         bias2_f[i] = bf16_to_float(b_fc2[i]);
     }
     /* FC1: [T, D] x [4D, D].T -> [T, 4D] with FP32 output */
     gemm_bf16_fp32out(input, W_fc1, bias1_f, fc1_output, T, fourD, D);
     /* GELU activation (in-place on FP32) */
 #if defined(__AVX512F__)
     #pragma omp parallel for
     for (int t = 0; t < T; ++t) {
         float *row = fc1_output + (size_t)t * fourD;
         int j = 0;
         for (; j <= fourD - 16; j += 16) {
             __m512 x = _mm512_loadu_ps(row + j);
             __m512 y = gelu_avx512(x);
             _mm512_storeu_ps(row + j, y);
         }
         for (; j < fourD; ++j) {
             row[j] = gelu_scalar(row[j]);
         }
     }
 #else
     for (int t = 0; t < T; ++t) {
         for (int j = 0; j < fourD; ++j) {
             fc1_output[t * fourD + j] = gelu_scalar(fc1_output[t * fourD + j]);
         }
     }
 #endif
     /* FC2: [T, 4D] x [D, 4D].T -> [T, D]
      * Need to convert fc1_output to BF16 for BF16 GEMM, or use FP32 GEMM
      * For now, use a hybrid approach: convert fc1_output to BF16 temp buffer
      */
     uint16_t *fc1_bf16 = (uint16_t *)malloc((size_t)T * fourD * sizeof(uint16_t));
     if (!fc1_bf16) {
         free(bias1_f);
         free(bias2_f);
         return;
     }
     /* Convert FP32 activations back to BF16 */
 #if defined(__AVX512F__)
     #pragma omp parallel for
     for (int t = 0; t < T; ++t) {
         float *src = fc1_output + (size_t)t * fourD;
         uint16_t *dst = fc1_bf16 + (size_t)t * fourD;
         int j = 0;
         for (; j <= fourD - 16; j += 16) {
             __m512 fp32 = _mm512_loadu_ps(src + j);
             /* Round to nearest even */
             __m512i as_int = _mm512_castps_si512(fp32);
             __m512i lsb = _mm512_srli_epi32(as_int, 16);
             lsb = _mm512_and_si512(lsb, _mm512_set1_epi32(1));
             __m512i rounding = _mm512_add_epi32(_mm512_set1_epi32(0x7FFF), lsb);
             __m512i rounded = _mm512_add_epi32(as_int, rounding);
             __m512i shifted = _mm512_srli_epi32(rounded, 16);
             __m256i bf16 = _mm512_cvtepi32_epi16(shifted);
             _mm256_storeu_si256((__m256i *)(dst + j), bf16);
         }
         for (; j < fourD; ++j) {
             dst[j] = float_to_bf16(src[j]);
         }
     }
 #else
     for (size_t i = 0; i < (size_t)T * fourD; ++i) {
         fc1_bf16[i] = float_to_bf16(fc1_output[i]);
     }
 #endif
     /* FC2: BF16 GEMM with FP32 output */
     gemm_bf16_fp32out(fc1_bf16, W_fc2, bias2_f, output, T, D, fourD);
     free(fc1_bf16);
     free(bias1_f);
     free(bias2_f);
 }
References bf16_to_float(), float_to_bf16(), gelu_scalar(), and gemm_bf16_fp32out().
mlp_token_parallel_exact()
void mlp_token_parallel_exact (const float * input, const float * W_fc1, const float * b_fc1, const float * W_fc2, const float * b_fc2, float * fc1_output, float * output, int T, int aligned_dim, int num_threads)
Definition at line 57 of file mlp_kernels.c.
 {
     (void)num_threads;
     int D = aligned_dim;
     int fourD = 4 * D;
     // FC1: [T × D] · [D × 4D] -> [T × 4D]
     gemm_blocked_serial(input, W_fc1, b_fc1,
                         fc1_output,
                         T,      // M
                         fourD,  // N
                         D);     // K
     // Exact GELU using standard library tanhf
     gelu_exact_inplace(fc1_output, (size_t)T * (size_t)fourD);
     // FC2: [T × 4D] · [4D × D] -> [T × D]
     gemm_blocked_serial(fc1_output, W_fc2, b_fc2,
                         output,
                         T,  // M
                         D,  // N
                         fourD); // K
 }
References gelu_exact_inplace(), and gemm_blocked_serial().
patch2im()
void patch2im (const float * d_patches, float * d_image, int C, int H, int W, int P)
patch2im: Accumulates gradients from patches back into the image. (Backward pass)
d_patches: [num_patches, C * P * P] d_image: [C, H, W] (Accumulated)
Definition at line 55 of file vision_kernels.c.
 {
     int num_patches_h = H / P;
     int num_patches_w = W / P;
     int patch_dim = C * P * P;
     // Zero out the image first as we are accumulating gradients
     memset(d_image, 0, (size_t)C * H * W * sizeof(float));
     for (int ph = 0; ph < num_patches_h; ++ph) {
         for (int pw = 0; pw < num_patches_w; ++pw) {
             int patch_idx = ph * num_patches_w + pw;
             const float *src_patch = d_patches + (size_t)patch_idx * patch_dim;
             for (int c = 0; c < C; ++c) {
                 for (int py = 0; py < P; ++py) {
                     int y = ph * P + py;
                     int x = pw * P;
                     float *dst_row = d_image + (size_t)c * H * W + (size_t)y * W + x;
                     const float *src_row = src_patch + (size_t)c * P * P + (size_t)py * P;
                     // Add the patch gradient to the image gradient
                     for (int px = 0; px < P; ++px) {
                         dst_row[px] += src_row[px];
                     }
                 }
             }
         }
     }
 }
References C.
patch2im_bf16()
void patch2im_bf16 (const uint16_t * d_patches, uint16_t * d_image, int C, int H, int W, int P)
Definition at line 43 of file vision_kernels_bf16.c.
 {
     if (!d_patches || !d_image || C <= 0 || H <= 0 || W <= 0 || P <= 0) {
         return;
     }
     int num_patches_h = H / P;
     int num_patches_w = W / P;
     int patch_dim = C * P * P;
     memset(d_image, 0, (size_t)C * (size_t)H * (size_t)W * sizeof(uint16_t));
     for (int ph = 0; ph < num_patches_h; ++ph) {
         for (int pw = 0; pw < num_patches_w; ++pw) {
             int patch_idx = ph * num_patches_w + pw;
             const uint16_t *src_patch = d_patches + (size_t)patch_idx * (size_t)patch_dim;
             for (int c = 0; c < C; ++c) {
                 for (int py = 0; py < P; ++py) {
                     int y = ph * P + py;
                     int x = pw * P;
                     uint16_t *dst_row = d_image + (size_t)c * (size_t)H * (size_t)W + (size_t)y * (size_t)W + (size_t)x;
                     const uint16_t *src_row = src_patch + (size_t)c * (size_t)P * (size_t)P + (size_t)py * (size_t)P;
                     for (int px = 0; px < P; ++px) {
                         float acc = bf16_to_float(dst_row[px]) + bf16_to_float(src_row[px]);
                         dst_row[px] = float_to_bf16(acc);
                     }
                 }
             }
         }
     }
 }
References bf16_to_float(), C, and float_to_bf16().
quantize_row_q8_k()
void quantize_row_q8_k (const float * x, void * y, int k)
Definition at line 34 of file gemm_kernels_q4k_q8k.c.
{
     if (!x || !vy || k <= 0) {
         return;
     }
     assert(k % QK_K == 0);
     const int nb = k / QK_K;
     block_q8_K *y = (block_q8_K *)vy;
     for (int i = 0; i < nb; ++i) {
         float max = 0.0f;
         float amax = 0.0f;
         for (int j = 0; j < QK_K; ++j) {
             float ax = fabsf(x[j]);
             if (ax > amax) {
                 amax = ax;
                 max = x[j];
             }
         }
         if (!amax) {
             y[i].d = 0.0f;
             memset(y[i].qs, 0, sizeof(y[i].qs));
             memset(y[i].bsums, 0, sizeof(y[i].bsums));
             x += QK_K;
             continue;
         }
         const float iscale = -127.0f / max;
         for (int j = 0; j < QK_K; ++j) {
             int v = ck_nearest_int(iscale * x[j]);
             if (v > 127) {
                 v = 127;
             }
             if (v < -128) {
                 v = -128;
             }
             y[i].qs[j] = (int8_t)v;
         }
         for (int j = 0; j < QK_K / 16; ++j) {
             int sum = 0;
             const int8_t *qs = &y[i].qs[j * 16];
             for (int ii = 0; ii < 16; ++ii) {
                 sum += qs[ii];
             }
             y[i].bsums[j] = (int16_t)sum;
         }
         y[i].d = 1.0f / iscale;
         x += QK_K;
     }
 }
References block_q8_K::bsums, ck_nearest_int(), block_q8_K::d, QK_K, and block_q8_K::qs.
Referenced by ck_layer_forward_rmsnorm_swiglu_decode_q4_k(), and ck_mlp_swiglu_forward_q4_k_q8_k().
relu_backward()
void relu_backward (const float * input, const float * d_output, float * d_input, size_t n)
Definition at line 68 of file relu_kernels.c.
 {
     size_t i = 0;
 #if defined(__AVX512F__)
     __m512 vzero = _mm512_setzero_ps();
     for (; i + 15 < n; i += 16) {
         __m512 vx = _mm512_loadu_ps(input + i);
         __m512 vdy = _mm512_loadu_ps(d_output + i);
         __mmask16 mask = _mm512_cmp_ps_mask(vx, vzero, _CMP_GT_OQ);
         __m512 vdx = _mm512_maskz_mov_ps(mask, vdy);
         _mm512_storeu_ps(d_input + i, vdx);
     }
 #elif defined(__AVX2__) || defined(__AVX__)
     __m256 vzero = _mm256_setzero_ps();
     for (; i + 7 < n; i += 8) {
         __m256 vx = _mm256_loadu_ps(input + i);
         __m256 vdy = _mm256_loadu_ps(d_output + i);
         // Result is all 1s (0xFFFFFFFF) if true, 0 if false.
         __m256 mask = _mm256_cmp_ps(vx, vzero, _CMP_GT_OQ);
         __m256 vdx = _mm256_and_ps(mask, vdy);
         _mm256_storeu_ps(d_input + i, vdx);
     }
 #endif
     // Scalar fallback
     for (; i < n; ++i) {
         d_input[i] = (input[i] > 0.0f) ? d_output[i] : 0.0f;
     }
 }
relu_backward_bf16()
void relu_backward_bf16 (const uint16_t * input, const uint16_t * d_output, uint16_t * d_input, size_t n)
Definition at line 29 of file relu_kernels_bf16.c.
 {
     if (!input || !d_output || !d_input) {
         return;
     }
     for (size_t i = 0; i < n; ++i) {
         float x = bf16_to_float(input[i]);
         float dy = bf16_to_float(d_output[i]);
         d_input[i] = float_to_bf16(x > 0.0f ? dy : 0.0f);
     }
 }
References bf16_to_float(), and float_to_bf16().
relu_forward()
void relu_forward (const float * input, float * output, size_t n)
Definition at line 10 of file relu_kernels.c.
 {
     size_t i = 0;
 #if defined(__AVX512F__)
     __m512 vzero = _mm512_setzero_ps();
     for (; i + 15 < n; i += 16) {
         __m512 vx = _mm512_loadu_ps(input + i);
         __m512 vy = _mm512_max_ps(vx, vzero);
         _mm512_storeu_ps(output + i, vy);
     }
 #elif defined(__AVX2__) || defined(__AVX__)
     __m256 vzero = _mm256_setzero_ps();
     for (; i + 7 < n; i += 8) {
         __m256 vx = _mm256_loadu_ps(input + i);
         __m256 vy = _mm256_max_ps(vx, vzero);
         _mm256_storeu_ps(output + i, vy);
     }
 #endif
     // Scalar fallback
     for (; i < n; ++i) {
         float x = input[i];
         output[i] = (x > 0.0f) ? x : 0.0f;
     }
 }
relu_forward_bf16()
void relu_forward_bf16 (const uint16_t * input, uint16_t * output, size_t n)
Definition at line 7 of file relu_kernels_bf16.c.
 {
     if (!input || !output) {
         return;
     }
     for (size_t i = 0; i < n; ++i) {
         float x = bf16_to_float(input[i]);
         output[i] = float_to_bf16(x > 0.0f ? x : 0.0f);
     }
 }
References bf16_to_float(), and float_to_bf16().
relu_forward_inplace()
void relu_forward_inplace (float * data, size_t n)
Definition at line 38 of file relu_kernels.c.
 {
     size_t i = 0;
 #if defined(__AVX512F__)
     __m512 vzero = _mm512_setzero_ps();
     for (; i + 15 < n; i += 16) {
         __m512 vx = _mm512_loadu_ps(data + i);
         __m512 vy = _mm512_max_ps(vx, vzero);
         _mm512_storeu_ps(data + i, vy);
     }
 #elif defined(__AVX2__) || defined(__AVX__)
     __m256 vzero = _mm256_setzero_ps();
     for (; i + 7 < n; i += 8) {
         __m256 vx = _mm256_loadu_ps(data + i);
         __m256 vy = _mm256_max_ps(vx, vzero);
         _mm256_storeu_ps(data + i, vy);
     }
 #endif
     // Scalar fallback
     for (; i < n; ++i) {
         float x = data[i];
         if (x < 0.0f) {
             data[i] = 0.0f;
         }
     }
 }
relu_forward_inplace_bf16()
void relu_forward_inplace_bf16 (uint16_t * data, size_t n)
Definition at line 18 of file relu_kernels_bf16.c.
 {
     if (!data) {
         return;
     }
     for (size_t i = 0; i < n; ++i) {
         float x = bf16_to_float(data[i]);
         data[i] = float_to_bf16(x > 0.0f ? x : 0.0f);
     }
 }
References bf16_to_float(), and float_to_bf16().
rmsnorm_backward()
void rmsnorm_backward (const float * d_output, const float * input, const float * gamma, const float * rstd_cache, float * d_input, float * d_gamma, int tokens, int d_model, int aligned_embed_dim)
Definition at line 157 of file rmsnorm_kernels.c.
 {
     int T = tokens;
     int D = d_model;
     int aligned = aligned_embed_dim;
     // Zero parameter gradients
 #if defined(__AVX512F__)
     {
         int d = 0;
         for (; d + 16 <= D; d += 16) {
             _mm512_storeu_ps(&d_gamma[d], _mm512_setzero_ps());
         }
         for (; d < D; ++d) {
             d_gamma[d] = 0.0f;
         }
     }
 #elif defined(__AVX__)
     {
         int d = 0;
         for (; d + 8 <= D; d += 8) {
             _mm256_storeu_ps(&d_gamma[d], _mm256_setzero_ps());
         }
         for (; d < D; ++d) {
             d_gamma[d] = 0.0f;
         }
     }
 #else
     for (int d = 0; d < D; ++d) {
         d_gamma[d] = 0.0f;
     }
 #endif
     for (int t = 0; t < T; ++t) {
         const float *x = input + (size_t)t * aligned;
         const float *dY = d_output + (size_t)t * aligned;
         float *dX = d_input + (size_t)t * aligned;
         float rstd = rstd_cache[t];
 #if defined(__AVX512F__)
         // Compute m = (1/D) * sum_j (dY_j * gamma_j * x_hat_j)
         __m512 rstd_vec = _mm512_set1_ps(rstd);
         __m512 sum_vec = _mm512_setzero_ps();
         int d = 0;
         for (; d + 16 <= D; d += 16) {
             __m512 xv = _mm512_loadu_ps(&x[d]);
             __m512 dyv = _mm512_loadu_ps(&dY[d]);
             __m512 gv = _mm512_loadu_ps(&gamma[d]);
             __m512 x_hat = _mm512_mul_ps(xv, rstd_vec);
             // sum += dY * gamma * x_hat
             __m512 prod = _mm512_mul_ps(dyv, gv);
             sum_vec = _mm512_fmadd_ps(prod, x_hat, sum_vec);
         }
         float sum_dY_g_xhat = _mm512_reduce_add_ps(sum_vec);
         // Handle remaining elements
         for (; d < D; ++d) {
             float x_hat = x[d] * rstd;
             sum_dY_g_xhat += dY[d] * gamma[d] * x_hat;
         }
         float m = sum_dY_g_xhat / (float)D;
         // Compute dX and accumulate dGamma (vectorized)
         __m512 m_vec = _mm512_set1_ps(m);
         d = 0;
         for (; d + 16 <= D; d += 16) {
             __m512 xv = _mm512_loadu_ps(&x[d]);
             __m512 dyv = _mm512_loadu_ps(&dY[d]);
             __m512 gv = _mm512_loadu_ps(&gamma[d]);
             __m512 dgv = _mm512_loadu_ps(&d_gamma[d]);
             __m512 x_hat = _mm512_mul_ps(xv, rstd_vec);
             // dX = rstd * (dY * gamma - x_hat * m)
             __m512 dy_g = _mm512_mul_ps(dyv, gv);
             __m512 xhat_m = _mm512_mul_ps(x_hat, m_vec);
             __m512 diff = _mm512_sub_ps(dy_g, xhat_m);
             __m512 dxv = _mm512_mul_ps(rstd_vec, diff);
             _mm512_storeu_ps(&dX[d], dxv);
             // d_gamma += dY * x_hat
             dgv = _mm512_fmadd_ps(dyv, x_hat, dgv);
             _mm512_storeu_ps(&d_gamma[d], dgv);
         }
         // Handle remaining elements
         for (; d < D; ++d) {
             float x_hat = x[d] * rstd;
             float dy = dY[d];
             dX[d] = rstd * (dy * gamma[d] - x_hat * m);
             d_gamma[d] += dy * x_hat;
         }
 #elif defined(__AVX__)
         // Compute m = (1/D) * sum_j (dY_j * gamma_j * x_hat_j)
         __m256 rstd_vec = _mm256_set1_ps(rstd);
         __m256 sum_vec = _mm256_setzero_ps();
         int d = 0;
         for (; d + 8 <= D; d += 8) {
             __m256 xv = _mm256_loadu_ps(&x[d]);
             __m256 dyv = _mm256_loadu_ps(&dY[d]);
             __m256 gv = _mm256_loadu_ps(&gamma[d]);
             __m256 x_hat = _mm256_mul_ps(xv, rstd_vec);
             // sum += dY * gamma * x_hat (no FMA, use mul + mul + add)
             __m256 prod = _mm256_mul_ps(dyv, gv);
             __m256 prod2 = _mm256_mul_ps(prod, x_hat);
             sum_vec = _mm256_add_ps(sum_vec, prod2);
         }
         float sum_dY_g_xhat = hsum256_ps_rmsnorm(sum_vec);
         // Handle remaining elements
         for (; d < D; ++d) {
             float x_hat = x[d] * rstd;
             sum_dY_g_xhat += dY[d] * gamma[d] * x_hat;
         }
         float m = sum_dY_g_xhat / (float)D;
         // Compute dX and accumulate dGamma (vectorized)
         __m256 m_vec = _mm256_set1_ps(m);
         d = 0;
         for (; d + 8 <= D; d += 8) {
             __m256 xv = _mm256_loadu_ps(&x[d]);
             __m256 dyv = _mm256_loadu_ps(&dY[d]);
             __m256 gv = _mm256_loadu_ps(&gamma[d]);
             __m256 dgv = _mm256_loadu_ps(&d_gamma[d]);
             __m256 x_hat = _mm256_mul_ps(xv, rstd_vec);
             // dX = rstd * (dY * gamma - x_hat * m)
             __m256 dy_g = _mm256_mul_ps(dyv, gv);
             __m256 xhat_m = _mm256_mul_ps(x_hat, m_vec);
             __m256 diff = _mm256_sub_ps(dy_g, xhat_m);
             __m256 dxv = _mm256_mul_ps(rstd_vec, diff);
             _mm256_storeu_ps(&dX[d], dxv);
             // d_gamma += dY * x_hat
             __m256 dy_xhat = _mm256_mul_ps(dyv, x_hat);
             dgv = _mm256_add_ps(dgv, dy_xhat);
             _mm256_storeu_ps(&d_gamma[d], dgv);
         }
         // Handle remaining elements
         for (; d < D; ++d) {
             float x_hat = x[d] * rstd;
             float dy = dY[d];
             dX[d] = rstd * (dy * gamma[d] - x_hat * m);
             d_gamma[d] += dy * x_hat;
         }
 #else
         // Scalar fallback
         // Compute m = (1/D) * sum_j (dY_j * gamma_j * x_hat_j)
         double sum_dY_g_xhat = 0.0;
         for (int d = 0; d < D; ++d) {
             float x_hat = x[d] * rstd;
             sum_dY_g_xhat += (double)dY[d] * (double)gamma[d] * (double)x_hat;
         }
         float m = (float)(sum_dY_g_xhat / (double)D);
         // Compute dX and accumulate dGamma
         for (int d = 0; d < D; ++d) {
             float x_hat = x[d] * rstd;
             float dy = dY[d];
             dX[d] = rstd * (dy * gamma[d] - x_hat * m);
             d_gamma[d] += dy * x_hat;
         }
 #endif
         // Zero padding gradients (if any)
         for (int d = D; d < aligned; ++d) {
             dX[d] = 0.0f;
         }
     }
 }
Referenced by ck_layer_backward_rmsnorm_swiglu(), rmsnorm_backward_int4(), and rmsnorm_backward_int8().
rmsnorm_backward_bf16()
void rmsnorm_backward_bf16 (const uint16_t * d_output, const uint16_t * input, const float * gamma, const float * rstd_cache, uint16_t * d_input, float * d_gamma, int tokens, int d_model, int aligned_embed_dim)
Definition at line 97 of file rmsnorm_kernels_bf16.c.
 {
     int T = tokens;
     int D = d_model;
     int aligned = aligned_embed_dim;
     if (!d_output || !input || !gamma || !rstd_cache || !d_input || !d_gamma) {
         return;
     }
     // Zero parameter gradients
 #if defined(__AVX512F__)
     {
         int d = 0;
         for (; d + 16 <= D; d += 16) {
             _mm512_storeu_ps(&d_gamma[d], _mm512_setzero_ps());
         }
         for (; d < D; ++d) {
             d_gamma[d] = 0.0f;
         }
     }
 #else
     for (int d = 0; d < D; ++d) {
         d_gamma[d] = 0.0f;
     }
 #endif
     for (int t = 0; t < T; ++t) {
         const uint16_t *x_bf16 = input + (size_t)t * aligned;
         const uint16_t *dY_bf16 = d_output + (size_t)t * aligned;
         uint16_t *dX_bf16 = d_input + (size_t)t * aligned;
         float rstd = rstd_cache[t];
 #if defined(__AVX512F__)
         // Compute m = (1/D) * sum_j (dY_j * gamma_j * x_hat_j)
         __m512 rstd_vec = _mm512_set1_ps(rstd);
         __m512 sum_vec = _mm512_setzero_ps();
         int d = 0;
         for (; d + 16 <= D; d += 16) {
             __m512 xv = bf16_loadu_cvt_fp32(&x_bf16[d]);
             __m512 dyv = bf16_loadu_cvt_fp32(&dY_bf16[d]);
             __m512 gv = _mm512_loadu_ps(&gamma[d]);
             __m512 x_hat = _mm512_mul_ps(xv, rstd_vec);
             // sum += dY * gamma * x_hat
             __m512 prod = _mm512_mul_ps(dyv, gv);
             sum_vec = _mm512_fmadd_ps(prod, x_hat, sum_vec);
         }
         float sum_dY_g_xhat = _mm512_reduce_add_ps(sum_vec);
         // Handle remaining elements
         for (; d < D; ++d) {
             float x = bf16_to_float(x_bf16[d]);
             float x_hat = x * rstd;
             float dy = bf16_to_float(dY_bf16[d]);
             sum_dY_g_xhat += dy * gamma[d] * x_hat;
         }
         float m = sum_dY_g_xhat / (float)D;
         // Compute dX and accumulate dGamma (vectorized)
         __m512 m_vec = _mm512_set1_ps(m);
         d = 0;
         for (; d + 16 <= D; d += 16) {
             __m512 xv = bf16_loadu_cvt_fp32(&x_bf16[d]);
             __m512 dyv = bf16_loadu_cvt_fp32(&dY_bf16[d]);
             __m512 gv = _mm512_loadu_ps(&gamma[d]);
             __m512 dgv = _mm512_loadu_ps(&d_gamma[d]);
             __m512 x_hat = _mm512_mul_ps(xv, rstd_vec);
             // dX = rstd * (dY * gamma - x_hat * m)
             __m512 dy_g = _mm512_mul_ps(dyv, gv);
             __m512 xhat_m = _mm512_mul_ps(x_hat, m_vec);
             __m512 diff = _mm512_sub_ps(dy_g, xhat_m);
             __m512 dxv = _mm512_mul_ps(rstd_vec, diff);
             fp32_cvt_storeu_bf16(&dX_bf16[d], dxv);
             // d_gamma += dY * x_hat
             dgv = _mm512_fmadd_ps(dyv, x_hat, dgv);
             _mm512_storeu_ps(&d_gamma[d], dgv);
         }
         // Handle remaining elements
         for (; d < D; ++d) {
             float x = bf16_to_float(x_bf16[d]);
             float x_hat = x * rstd;
             float dy = bf16_to_float(dY_bf16[d]);
             float dx = rstd * (dy * gamma[d] - x_hat * m);
             dX_bf16[d] = float_to_bf16(dx);
             d_gamma[d] += dy * x_hat;
         }
 #else
         // Scalar fallback
         double sum_dY_g_xhat = 0.0;
         for (int d = 0; d < D; ++d) {
             float x = bf16_to_float(x_bf16[d]);
             float x_hat = x * rstd;
             float dy = bf16_to_float(dY_bf16[d]);
             sum_dY_g_xhat += (double)dy * (double)gamma[d] * (double)x_hat;
         }
         float m = (float)(sum_dY_g_xhat / (double)D);
         for (int d = 0; d < D; ++d) {
             float x = bf16_to_float(x_bf16[d]);
             float x_hat = x * rstd;
             float dy = bf16_to_float(dY_bf16[d]);
             float dx = rstd * (dy * gamma[d] - x_hat * m);
             dX_bf16[d] = float_to_bf16(dx);
             d_gamma[d] += dy * x_hat;
         }
 #endif
         // Zero padding gradients
         for (int d = D; d < aligned; ++d) {
             dX_bf16[d] = 0;
         }
     }
 }
References bf16_to_float(), and float_to_bf16().
rmsnorm_backward_int4()
void rmsnorm_backward_int4 (const uint8_t * d_output, const uint8_t * input, const float * gamma, const float * rstd_cache, uint8_t * d_input, float * d_gamma, int tokens, int d_model, int aligned_embed_dim)
Definition at line 102 of file rmsnorm_kernels_int4.c.
 {
     if (!d_output || !input || !gamma || !rstd_cache || !d_input || !d_gamma) {
         return;
     }
     size_t total = (size_t)tokens * (size_t)aligned_embed_dim;
     float *d_output_f = alloc_float_buffer(total);
     float *input_f = alloc_float_buffer(total);
     float *d_input_f = alloc_float_buffer(total);
     if (!d_output_f || !input_f || !d_input_f) {
         free_float_buffer(d_output_f);
         free_float_buffer(input_f);
         free_float_buffer(d_input_f);
         return;
     }
     convert_int4_to_float(d_output, d_output_f, total);
     convert_int4_to_float(input, input_f, total);
     for (int d = 0; d < d_model; ++d) {
         d_gamma[d] = 0.0f;
     }
     rmsnorm_backward(d_output_f,
                      input_f,
                      gamma,
                      rstd_cache,
                      d_input_f,
                      d_gamma,
                      tokens,
                      d_model,
                      aligned_embed_dim);
     convert_float_to_int4(d_input_f, d_input, total);
     free_float_buffer(d_output_f);
     free_float_buffer(input_f);
     free_float_buffer(d_input_f);
 }
References alloc_float_buffer(), convert_float_to_int4(), convert_int4_to_float(), free_float_buffer(), and rmsnorm_backward().
rmsnorm_backward_int8()
void rmsnorm_backward_int8 (const int8_t * d_output, const int8_t * input, const float * gamma, const float * rstd_cache, int8_t * d_input, float * d_gamma, int tokens, int d_model, int aligned_embed_dim)
Definition at line 82 of file rmsnorm_kernels_int8.c.
 {
     if (!d_output || !input || !gamma || !rstd_cache || !d_input || !d_gamma) {
         return;
     }
     size_t total = (size_t)tokens * (size_t)aligned_embed_dim;
     float *d_output_f = alloc_float_buffer(total);
     float *input_f = alloc_float_buffer(total);
     float *d_input_f = alloc_float_buffer(total);
     if (!d_output_f || !input_f || !d_input_f) {
         free_float_buffer(d_output_f);
         free_float_buffer(input_f);
         free_float_buffer(d_input_f);
         return;
     }
     convert_int8_to_float(d_output, d_output_f, total);
     convert_int8_to_float(input, input_f, total);
     // Zero gamma gradient before accumulation.
     for (int d = 0; d < d_model; ++d) {
         d_gamma[d] = 0.0f;
     }
     rmsnorm_backward(d_output_f,
                      input_f,
                      gamma,
                      rstd_cache,
                      d_input_f,
                      d_gamma,
                      tokens,
                      d_model,
                      aligned_embed_dim);
     convert_float_to_int8(d_input_f, d_input, total);
     free_float_buffer(d_output_f);
     free_float_buffer(input_f);
     free_float_buffer(d_input_f);
 }
References alloc_float_buffer(), convert_float_to_int8(), convert_int8_to_float(), free_float_buffer(), and rmsnorm_backward().
rmsnorm_forward()
void rmsnorm_forward (const float * input, const float * gamma, float * output, float * rstd_cache, int tokens, int d_model, int aligned_embed_dim, float eps)
Definition at line 30 of file rmsnorm_kernels.c.
 {
     int T = tokens;
     int D = d_model;
     int aligned = aligned_embed_dim;
     for (int t = 0; t < T; ++t) {
         const float *x = input + (size_t)t * aligned;
         float *y = output + (size_t)t * aligned;
 #if defined(__AVX512F__)
         // AVX-512: Process 16 floats at a time
         __m512 sum_sq_vec = _mm512_setzero_ps();
         int d = 0;
         // Vectorized sum of squares
         for (; d + 16 <= D; d += 16) {
             __m512 xv = _mm512_loadu_ps(&x[d]);
             sum_sq_vec = _mm512_fmadd_ps(xv, xv, sum_sq_vec);
         }
         float sum_sq = _mm512_reduce_add_ps(sum_sq_vec);
         // Handle remaining elements
         for (; d < D; ++d) {
             sum_sq += x[d] * x[d];
         }
         float mean_sq = sum_sq / (float)D;
         float rstd = 1.0f / sqrtf(mean_sq + eps);
         rstd_cache[t] = rstd;
         // Apply normalization and scale (vectorized)
         __m512 rstd_vec = _mm512_set1_ps(rstd);
         d = 0;
         for (; d + 16 <= D; d += 16) {
             __m512 xv = _mm512_loadu_ps(&x[d]);
             __m512 gv = _mm512_loadu_ps(&gamma[d]);
             __m512 x_hat = _mm512_mul_ps(xv, rstd_vec);
             __m512 yv = _mm512_mul_ps(x_hat, gv);
             _mm512_storeu_ps(&y[d], yv);
         }
         // Handle remaining elements
         for (; d < D; ++d) {
             y[d] = x[d] * rstd * gamma[d];
         }
 #elif defined(__AVX__)
         // AVX: Process 8 floats at a time
         __m256 sum_sq_vec = _mm256_setzero_ps();
         int d = 0;
         // Vectorized sum of squares (no FMA in AVX1, use mul + add)
         for (; d + 8 <= D; d += 8) {
             __m256 xv = _mm256_loadu_ps(&x[d]);
             __m256 xv_sq = _mm256_mul_ps(xv, xv);
             sum_sq_vec = _mm256_add_ps(sum_sq_vec, xv_sq);
         }
         float sum_sq = hsum256_ps_rmsnorm(sum_sq_vec);
         // Handle remaining elements
         for (; d < D; ++d) {
             sum_sq += x[d] * x[d];
         }
         float mean_sq = sum_sq / (float)D;
         float rstd = 1.0f / sqrtf(mean_sq + eps);
         rstd_cache[t] = rstd;
         // Apply normalization and scale (vectorized)
         __m256 rstd_vec = _mm256_set1_ps(rstd);
         d = 0;
         for (; d + 8 <= D; d += 8) {
             __m256 xv = _mm256_loadu_ps(&x[d]);
             __m256 gv = _mm256_loadu_ps(&gamma[d]);
             __m256 x_hat = _mm256_mul_ps(xv, rstd_vec);
             __m256 yv = _mm256_mul_ps(x_hat, gv);
             _mm256_storeu_ps(&y[d], yv);
         }
         // Handle remaining elements
         for (; d < D; ++d) {
             y[d] = x[d] * rstd * gamma[d];
         }
 #else
         // Scalar fallback
         double sum_sq = 0.0;
         for (int d = 0; d < D; ++d) {
             double v = (double)x[d];
             sum_sq += v * v;
         }
         double mean_sq = sum_sq / (double)D;
         double r = sqrt(mean_sq + (double)eps);
         float rstd = (float)(1.0 / r);
         rstd_cache[t] = rstd;
         // Apply normalization and scale
         for (int d = 0; d < D; ++d) {
             float x_hat = x[d] * rstd;
             y[d] = x_hat * gamma[d];
         }
 #endif
         // Zero padding (if any)
         for (int d = D; d < aligned; ++d) {
             y[d] = 0.0f;
         }
     }
 }
Referenced by ck_layer_forward_rmsnorm_swiglu(), ck_layer_forward_rmsnorm_swiglu_decode(), ck_layer_forward_rmsnorm_swiglu_decode_fused(), ck_layer_forward_rmsnorm_swiglu_decode_fused_attn_impl(), ck_layer_forward_rmsnorm_swiglu_decode_q4_k(), ck_layer_forward_rmsnorm_swiglu_decode_quant(), ck_layer_forward_rmsnorm_swiglu_q4_k(), ck_layer_forward_rmsnorm_swiglu_quant(), ck_layer_forward_rmsnorm_swiglu_ref(), rmsnorm_forward_int4(), and rmsnorm_forward_int8().
rmsnorm_forward_bf16()
void rmsnorm_forward_bf16 (const uint16_t * input, const float * gamma, uint16_t * output, float * rstd_cache, int tokens, int d_model, int aligned_embed_dim, float eps)
Definition at line 8 of file rmsnorm_kernels_bf16.c.
 {
     int T = tokens;
     int D = d_model;
     int aligned = aligned_embed_dim;
     for (int t = 0; t < T; ++t) {
         const uint16_t *x_bf16 = input + (size_t)t * aligned;
         float *rstd_ptr = rstd_cache ? (rstd_cache + t) : NULL;
         uint16_t *out_bf16 = output + (size_t)t * aligned;
 #if defined(__AVX512F__)
         // AVX-512: Process 16 floats at a time
         __m512 sum_sq_vec = _mm512_setzero_ps();
         int d = 0;
         // Vectorized sum of squares
         for (; d + 16 <= D; d += 16) {
             __m512 xv = bf16_loadu_cvt_fp32(&x_bf16[d]);
             sum_sq_vec = _mm512_fmadd_ps(xv, xv, sum_sq_vec);
         }
         float sum_sq = _mm512_reduce_add_ps(sum_sq_vec);
         // Handle remaining elements
         for (; d < D; ++d) {
             float x = bf16_to_float(x_bf16[d]);
             sum_sq += x * x;
         }
         float mean_sq = sum_sq / (float)D;
         float rstd = 1.0f / sqrtf(mean_sq + eps);
         if (rstd_ptr) {
             *rstd_ptr = rstd;
         }
         // Apply normalization and scale (vectorized)
         __m512 rstd_vec = _mm512_set1_ps(rstd);
         d = 0;
         for (; d + 16 <= D; d += 16) {
             __m512 xv = bf16_loadu_cvt_fp32(&x_bf16[d]);
             __m512 gv = _mm512_loadu_ps(&gamma[d]);
             __m512 x_hat = _mm512_mul_ps(xv, rstd_vec);
             __m512 yv = _mm512_mul_ps(x_hat, gv);
             fp32_cvt_storeu_bf16(&out_bf16[d], yv);
         }
         // Handle remaining elements
         for (; d < D; ++d) {
             float x = bf16_to_float(x_bf16[d]);
             float y = x * rstd * gamma[d];
             out_bf16[d] = float_to_bf16(y);
         }
 #else
         // Scalar fallback
         double sum_sq = 0.0;
         for (int d = 0; d < D; ++d) {
             float x = bf16_to_float(x_bf16[d]);
             sum_sq += (double)x * (double)x;
         }
         double mean_sq = sum_sq / (double)D;
         double r = sqrt(mean_sq + (double)eps);
         float rstd = (float)(1.0 / r);
         if (rstd_ptr) {
             *rstd_ptr = rstd;
         }
         for (int d = 0; d < D; ++d) {
             float x = bf16_to_float(x_bf16[d]);
             float x_hat = x * rstd;
             float y = x_hat * gamma[d];
             out_bf16[d] = float_to_bf16(y);
         }
 #endif
         // Zero padding
         for (int d = D; d < aligned; ++d) {
             out_bf16[d] = 0;
         }
     }
 }
References bf16_to_float(), and float_to_bf16().
rmsnorm_forward_int4()
void rmsnorm_forward_int4 (const uint8_t * input, const float * gamma, uint8_t * output, float * rstd_cache, int tokens, int d_model, int aligned_embed_dim, float eps)
Definition at line 71 of file rmsnorm_kernels_int4.c.
 {
     if (!input || !gamma || !output) {
         return;
     }
     size_t total = (size_t)tokens * (size_t)aligned_embed_dim;
     float *input_f = alloc_float_buffer(total);
     float *output_f = alloc_float_buffer(total);
     if (!input_f || !output_f) {
         free_float_buffer(input_f);
         free_float_buffer(output_f);
         return;
     }
     convert_int4_to_float(input, input_f, total);
     rmsnorm_forward(input_f, gamma, output_f, rstd_cache,
                     tokens, d_model, aligned_embed_dim, eps);
     convert_float_to_int4(output_f, output, total);
     free_float_buffer(input_f);
     free_float_buffer(output_f);
 }
References alloc_float_buffer(), convert_float_to_int4(), convert_int4_to_float(), free_float_buffer(), and rmsnorm_forward().
rmsnorm_forward_int8()
void rmsnorm_forward_int8 (const int8_t * input, const float * gamma, int8_t * output, float * rstd_cache, int tokens, int d_model, int aligned_embed_dim, float eps)
Definition at line 51 of file rmsnorm_kernels_int8.c.
 {
     if (!input || !gamma || !output) {
         return;
     }
     size_t total = (size_t)tokens * (size_t)aligned_embed_dim;
     float *input_f = alloc_float_buffer(total);
     float *output_f = alloc_float_buffer(total);
     if (!input_f || !output_f) {
         free_float_buffer(input_f);
         free_float_buffer(output_f);
         return;
     }
     convert_int8_to_float(input, input_f, total);
     rmsnorm_forward(input_f, gamma, output_f, rstd_cache,
                     tokens, d_model, aligned_embed_dim, eps);
     convert_float_to_int8(output_f, output, total);
     free_float_buffer(input_f);
     free_float_buffer(output_f);
 }
References alloc_float_buffer(), convert_float_to_int8(), convert_int8_to_float(), free_float_buffer(), and rmsnorm_forward().
rope_backward()
void rope_backward (const float * d_out, float * d_x, const float * cos_cache, const float * sin_cache, int num_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset)
Definition at line 181 of file rope_kernels.c.
 {
     size_t head_stride = (size_t)num_tokens * (size_t)aligned_head_dim;
     int half_dim = head_dim / 2;
     for (int h = 0; h < num_heads; ++h) {
         for (int t = 0; t < num_tokens; ++t) {
             int pos = pos_offset + t;
             const float *cos_row = cos_cache + pos * half_dim;
             const float *sin_row = sin_cache + pos * half_dim;
             size_t idx = h * head_stride + (size_t)t * (size_t)aligned_head_dim;
             const float *d_out_row = d_out + idx;
             float *d_x_row = d_x + idx;
 #if defined(__AVX512F__)
             int i = 0;
             for (; i + 16 <= half_dim; i += 16) {
                 __m512 d0 = _mm512_loadu_ps(&d_out_row[i]);
                 __m512 d1 = _mm512_loadu_ps(&d_out_row[i + half_dim]);
                 __m512 c = _mm512_loadu_ps(&cos_row[i]);
                 __m512 s = _mm512_loadu_ps(&sin_row[i]);
                 // Inverse: d_x[i] = d0 * c + d1 * s
                 __m512 r0 = _mm512_fmadd_ps(d0, c, _mm512_mul_ps(d1, s));
                 // Inverse: d_x[i+half] = -d0 * s + d1 * c
                 __m512 r1 = _mm512_fmsub_ps(d1, c, _mm512_mul_ps(d0, s));
                 _mm512_storeu_ps(&d_x_row[i], r0);
                 _mm512_storeu_ps(&d_x_row[i + half_dim], r1);
             }
             for (; i < half_dim; ++i) {
                 float d0 = d_out_row[i];
                 float d1 = d_out_row[i + half_dim];
                 float c = cos_row[i];
                 float s = sin_row[i];
                 d_x_row[i] = d0 * c + d1 * s;
                 d_x_row[i + half_dim] = -d0 * s + d1 * c;
             }
 #elif defined(__AVX__)
             int i = 0;
             for (; i + 8 <= half_dim; i += 8) {
                 __m256 d0 = _mm256_loadu_ps(&d_out_row[i]);
                 __m256 d1 = _mm256_loadu_ps(&d_out_row[i + half_dim]);
                 __m256 c = _mm256_loadu_ps(&cos_row[i]);
                 __m256 s = _mm256_loadu_ps(&sin_row[i]);
                 // Inverse: d_x[i] = d0 * c + d1 * s
                 __m256 d0c = _mm256_mul_ps(d0, c);
                 __m256 d1s = _mm256_mul_ps(d1, s);
                 __m256 r0 = _mm256_add_ps(d0c, d1s);
                 // Inverse: d_x[i+half] = -d0 * s + d1 * c = d1 * c - d0 * s
                 __m256 d1c = _mm256_mul_ps(d1, c);
                 __m256 d0s = _mm256_mul_ps(d0, s);
                 __m256 r1 = _mm256_sub_ps(d1c, d0s);
                 _mm256_storeu_ps(&d_x_row[i], r0);
                 _mm256_storeu_ps(&d_x_row[i + half_dim], r1);
             }
             for (; i < half_dim; ++i) {
                 float d0 = d_out_row[i];
                 float d1 = d_out_row[i + half_dim];
                 float c = cos_row[i];
                 float s = sin_row[i];
                 d_x_row[i] = d0 * c + d1 * s;
                 d_x_row[i + half_dim] = -d0 * s + d1 * c;
             }
 #else
             for (int i = 0; i < half_dim; ++i) {
                 float d0 = d_out_row[i];
                 float d1 = d_out_row[i + half_dim];
                 float c = cos_row[i];
                 float s = sin_row[i];
                 // Inverse rotation: rotate by -θ
                 d_x_row[i] = d0 * c + d1 * s;
                 d_x_row[i + half_dim] = -d0 * s + d1 * c;
             }
 #endif
             for (int i = head_dim; i < aligned_head_dim; ++i) {
                 d_x_row[i] = 0.0f;
             }
         }
     }
 }
Referenced by rope_backward_bf16(), and rope_backward_qk().
rope_backward_bf16()
void rope_backward_bf16 (const uint16_t * d_out, uint16_t * d_x, const float * cos_cache, const float * sin_cache, int num_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset)
Definition at line 44 of file rope_kernels_bf16.c.
 {
     size_t total = (size_t)num_heads * (size_t)num_tokens * (size_t)aligned_head_dim;
     float *d_out_f = alloc_float_buffer(total);
     float *d_x_f = alloc_float_buffer(total);
     if (!d_out_f || !d_x_f) {
         free_float_buffer(d_out_f);
         free_float_buffer(d_x_f);
         return;
     }
     bf16_tensor_to_float(d_out, d_out_f, total);
     rope_backward(d_out_f, d_x_f, cos_cache, sin_cache,
                   num_heads, num_tokens, head_dim, aligned_head_dim, pos_offset);
     float_tensor_to_bf16(d_x_f, d_x, total);
     free_float_buffer(d_out_f);
     free_float_buffer(d_x_f);
 }
References alloc_float_buffer(), bf16_tensor_to_float(), float_tensor_to_bf16(), free_float_buffer(), and rope_backward().
Referenced by rope_backward_qk_bf16().
rope_backward_inplace()
void rope_backward_inplace (float * d_x, const float * cos_cache, const float * sin_cache, int num_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset)
Definition at line 281 of file rope_kernels.c.
 {
     size_t head_stride = (size_t)num_tokens * (size_t)aligned_head_dim;
     int half_dim = head_dim / 2;
     for (int h = 0; h < num_heads; ++h) {
         for (int t = 0; t < num_tokens; ++t) {
             int pos = pos_offset + t;
             const float *cos_row = cos_cache + pos * half_dim;
             const float *sin_row = sin_cache + pos * half_dim;
             float *d_row = d_x + h * head_stride + (size_t)t * (size_t)aligned_head_dim;
 #if defined(__AVX512F__)
             int i = 0;
             for (; i + 16 <= half_dim; i += 16) {
                 __m512 d0 = _mm512_loadu_ps(&d_row[i]);
                 __m512 d1 = _mm512_loadu_ps(&d_row[i + half_dim]);
                 __m512 c = _mm512_loadu_ps(&cos_row[i]);
                 __m512 s = _mm512_loadu_ps(&sin_row[i]);
                 __m512 r0 = _mm512_fmadd_ps(d0, c, _mm512_mul_ps(d1, s));
                 __m512 r1 = _mm512_fmsub_ps(d1, c, _mm512_mul_ps(d0, s));
                 _mm512_storeu_ps(&d_row[i], r0);
                 _mm512_storeu_ps(&d_row[i + half_dim], r1);
             }
             for (; i < half_dim; ++i) {
                 float d0 = d_row[i];
                 float d1 = d_row[i + half_dim];
                 float c = cos_row[i];
                 float s = sin_row[i];
                 d_row[i] = d0 * c + d1 * s;
                 d_row[i + half_dim] = -d0 * s + d1 * c;
             }
 #elif defined(__AVX__)
             int i = 0;
             for (; i + 8 <= half_dim; i += 8) {
                 __m256 d0 = _mm256_loadu_ps(&d_row[i]);
                 __m256 d1 = _mm256_loadu_ps(&d_row[i + half_dim]);
                 __m256 c = _mm256_loadu_ps(&cos_row[i]);
                 __m256 s = _mm256_loadu_ps(&sin_row[i]);
                 __m256 d0c = _mm256_mul_ps(d0, c);
                 __m256 d1s = _mm256_mul_ps(d1, s);
                 __m256 r0 = _mm256_add_ps(d0c, d1s);
                 __m256 d1c = _mm256_mul_ps(d1, c);
                 __m256 d0s = _mm256_mul_ps(d0, s);
                 __m256 r1 = _mm256_sub_ps(d1c, d0s);
                 _mm256_storeu_ps(&d_row[i], r0);
                 _mm256_storeu_ps(&d_row[i + half_dim], r1);
             }
             for (; i < half_dim; ++i) {
                 float d0 = d_row[i];
                 float d1 = d_row[i + half_dim];
                 float c = cos_row[i];
                 float s = sin_row[i];
                 d_row[i] = d0 * c + d1 * s;
                 d_row[i + half_dim] = -d0 * s + d1 * c;
             }
 #else
             for (int i = 0; i < half_dim; ++i) {
                 float d0 = d_row[i];
                 float d1 = d_row[i + half_dim];
                 float c = cos_row[i];
                 float s = sin_row[i];
                 // Inverse rotation: rotate by -θ
                 d_row[i] = d0 * c + d1 * s;
                 d_row[i + half_dim] = -d0 * s + d1 * c;
             }
 #endif
             for (int i = head_dim; i < aligned_head_dim; ++i) {
                 d_row[i] = 0.0f;
             }
         }
     }
 }
rope_backward_qk()
void rope_backward_qk (const float * d_q_out, const float * d_k_out, float * d_q, float * d_k, const float * cos_cache, const float * sin_cache, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset)
Definition at line 391 of file rope_kernels.c.
 {
     rope_backward(d_q_out, d_q, cos_cache, sin_cache, num_heads, num_tokens, head_dim, aligned_head_dim, pos_offset);
     rope_backward(d_k_out, d_k, cos_cache, sin_cache, num_kv_heads, num_tokens, head_dim, aligned_head_dim, pos_offset);
 }
References rope_backward().
Referenced by ck_layer_backward_rmsnorm_swiglu().
rope_backward_qk_bf16()
void rope_backward_qk_bf16 (const uint16_t * d_q_out, const uint16_t * d_k_out, uint16_t * d_q, uint16_t * d_k, const float * cos_cache, const float * sin_cache, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset)
Definition at line 93 of file rope_kernels_bf16.c.
 {
     if (!d_q_out || !d_k_out || !d_q || !d_k) {
         return;
     }
     rope_backward_bf16(d_q_out, d_q, cos_cache, sin_cache,
                        num_heads, num_tokens, head_dim, aligned_head_dim, pos_offset);
     rope_backward_bf16(d_k_out, d_k, cos_cache, sin_cache,
                        num_kv_heads, num_tokens, head_dim, aligned_head_dim, pos_offset);
 }
References rope_backward_bf16().
rope_forward()
void rope_forward (float * x, const float * cos_cache, const float * sin_cache, int num_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset)
Definition at line 155 of file rope_kernels.c.
 {
     size_t head_stride = (size_t)num_tokens * (size_t)aligned_head_dim;
     for (int h = 0; h < num_heads; ++h) {
         rope_apply_head(x + h * head_stride,
                         cos_cache, sin_cache,
                         num_tokens, head_dim, aligned_head_dim, pos_offset);
     }
 }
References rope_apply_head().
Referenced by rope_forward_bf16(), and rope_forward_qk().
rope_forward_bf16()
void rope_forward_bf16 (uint16_t * x, const float * cos_cache, const float * sin_cache, int num_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset)
Definition at line 21 of file rope_kernels_bf16.c.
 {
     size_t total = (size_t)num_heads * (size_t)num_tokens * (size_t)aligned_head_dim;
     float *tmp = alloc_float_buffer(total);
     if (!tmp) {
         return;
     }
     bf16_tensor_to_float(x, tmp, total);
     rope_forward(tmp, cos_cache, sin_cache,
                  num_heads, num_tokens, head_dim, aligned_head_dim, pos_offset);
     float_tensor_to_bf16(tmp, x, total);
     free_float_buffer(tmp);
 }
References alloc_float_buffer(), bf16_tensor_to_float(), float_tensor_to_bf16(), free_float_buffer(), and rope_forward().
Referenced by rope_forward_qk_bf16().
rope_forward_qk()
void rope_forward_qk (float * q, float * k, const float * cos_cache, const float * sin_cache, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset)
Definition at line 375 of file rope_kernels.c.
 {
     rope_forward(q, cos_cache, sin_cache, num_heads, num_tokens, head_dim, aligned_head_dim, pos_offset);
     rope_forward(k, cos_cache, sin_cache, num_kv_heads, num_tokens, head_dim, aligned_head_dim, pos_offset);
 }
References rope_forward().
Referenced by ck_layer_forward_rmsnorm_swiglu(), ck_layer_forward_rmsnorm_swiglu_decode(), ck_layer_forward_rmsnorm_swiglu_decode_fused(), ck_layer_forward_rmsnorm_swiglu_decode_fused_attn_impl(), ck_layer_forward_rmsnorm_swiglu_decode_q4_k(), ck_layer_forward_rmsnorm_swiglu_decode_quant(), ck_layer_forward_rmsnorm_swiglu_q4_k(), ck_layer_forward_rmsnorm_swiglu_quant(), and ck_layer_forward_rmsnorm_swiglu_ref().
rope_forward_qk_bf16()
void rope_forward_qk_bf16 (uint16_t * q, uint16_t * k, const float * cos_cache, const float * sin_cache, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset)
Definition at line 72 of file rope_kernels_bf16.c.
 {
     if (!q || !k) {
         return;
     }
     rope_forward_bf16(q, cos_cache, sin_cache,
                       num_heads, num_tokens, head_dim, aligned_head_dim, pos_offset);
     rope_forward_bf16(k, cos_cache, sin_cache,
                       num_kv_heads, num_tokens, head_dim, aligned_head_dim, pos_offset);
 }
References rope_forward_bf16().
rope_precompute_cache()
void rope_precompute_cache (float * cos_cache, float * sin_cache, int max_seq_len, int head_dim, float base)
Definition at line 34 of file rope_kernels.c.
 {
     int half_dim = head_dim / 2;
     long double base_ld = (long double)base;
     long double head_dim_ld = (long double)head_dim;
     long double log_base = logl(base_ld);
     for (int pos = 0; pos < max_seq_len; ++pos) {
         for (int i = 0; i < half_dim; ++i) {
             long double exponent = ((long double)(2 * i)) / head_dim_ld;
             long double freq = expl(-exponent * log_base);
             float freq_f = (float)freq;
             float angle_f = (float)pos * freq_f;
             cos_cache[pos * half_dim + i] = cosf(angle_f);
             sin_cache[pos * half_dim + i] = sinf(angle_f);
         }
     }
 }
sigmoid_backward()
void sigmoid_backward (const float * input, const float * d_output, float * d_input, size_t n)
Definition at line 123 of file sigmoid_kernels.c.
 {
 #if defined(__AVX512F__)
     sigmoid_backward_avx512(input, d_output, d_input, n);
 #else
     for (size_t i = 0; i < n; ++i) {
         float x = input[i];
         float s = sigmoid_scalar(x);
         float s_prime = s * (1.0f - s);
         d_input[i] = d_output[i] * s_prime;
     }
 #endif
 }
References sigmoid_scalar().
Referenced by sigmoid_backward_bf16().
sigmoid_backward_bf16()
void sigmoid_backward_bf16 (const uint16_t * input, const uint16_t * d_output, uint16_t * d_input, size_t n)
Definition at line 37 of file sigmoid_kernels_bf16.c.
 {
     if (!input || !d_output || !d_input || n == 0) {
         return;
     }
     float *input_f = alloc_float_buffer(n);
     float *d_output_f = alloc_float_buffer(n);
     float *d_input_f = alloc_float_buffer(n);
     if (!input_f || !d_output_f || !d_input_f) {
         free(input_f);
         free(d_output_f);
         free(d_input_f);
         return;
     }
     bf16_tensor_to_float(input, input_f, n);
     bf16_tensor_to_float(d_output, d_output_f, n);
     sigmoid_backward(input_f, d_output_f, d_input_f, n);
     float_tensor_to_bf16(d_input_f, d_input, n);
     free(input_f);
     free(d_output_f);
     free(d_input_f);
 }
References alloc_float_buffer(), bf16_tensor_to_float(), float_tensor_to_bf16(), and sigmoid_backward().
sigmoid_forward()
void sigmoid_forward (const float * input, float * output, size_t n)
Definition at line 107 of file sigmoid_kernels.c.
 {
 #if defined(__AVX512F__)
     sigmoid_forward_avx512(input, output, n);
 #else
     for (size_t i = 0; i < n; ++i) {
         output[i] = sigmoid_scalar(input[i]);
     }
 #endif
 }
References sigmoid_scalar().
Referenced by sigmoid_forward_bf16().
sigmoid_forward_bf16()
void sigmoid_forward_bf16 (const uint16_t * input, uint16_t * output, size_t n)
Definition at line 13 of file sigmoid_kernels_bf16.c.
 {
     if (!input || !output || n == 0) {
         return;
     }
     float *input_f = alloc_float_buffer(n);
     float *output_f = alloc_float_buffer(n);
     if (!input_f || !output_f) {
         free(input_f);
         free(output_f);
         return;
     }
     bf16_tensor_to_float(input, input_f, n);
     sigmoid_forward(input_f, output_f, n);
     float_tensor_to_bf16(output_f, output, n);
     free(input_f);
     free(output_f);
 }
References alloc_float_buffer(), bf16_tensor_to_float(), float_tensor_to_bf16(), and sigmoid_forward().
sigmoid_scalar()
float sigmoid_scalar (float x)
Definition at line 11 of file sigmoid_kernels.c.
 {
     return 1.0f / (1.0f + expf(-x));
 }
Referenced by sigmoid_backward(), sigmoid_forward(), swiglu_backward(), swiglu_backward_bf16(), swiglu_backward_exact(), swiglu_forward(), swiglu_forward_bf16(), and swiglu_forward_exact().
softmax_cross_entropy_loss()
void softmax_cross_entropy_loss (const float * logits, const int32_t * targets, int tokens, int vocab_size, float * d_logits, float * loss_out)
Definition at line 5 of file loss_kernels.c.
 {
     if (!logits || !targets || !d_logits || tokens <= 0 || vocab_size <= 0) {
         if (loss_out) {
             *loss_out = 0.0f;
         }
         return;
     }
     double total_loss = 0.0;
     for (int t = 0; t < tokens; ++t) {
         const float *row = logits + (size_t)t * (size_t)vocab_size;
         float *drow = d_logits + (size_t)t * (size_t)vocab_size;
         int target = targets[t];
         float max_logit = row[0];
         for (int v = 1; v < vocab_size; ++v) {
             if (row[v] > max_logit) {
                 max_logit = row[v];
             }
         }
         double sum_exp = 0.0;
         for (int v = 0; v < vocab_size; ++v) {
             float e = expf(row[v] - max_logit);
             drow[v] = e;
             sum_exp += e;
         }
         float inv_sum = 1.0f / (float)sum_exp;
         for (int v = 0; v < vocab_size; ++v) {
             drow[v] *= inv_sum;
         }
         if (target >= 0 && target < vocab_size) {
             total_loss += -logf(drow[target] + 1e-10f);
             drow[target] -= 1.0f;
         }
         float scale = 1.0f / (float)tokens;
         for (int v = 0; v < vocab_size; ++v) {
             drow[v] *= scale;
         }
     }
     if (loss_out) {
         *loss_out = (float)(total_loss / (double)tokens);
     }
 }
Referenced by softmax_cross_entropy_loss_bf16().
softmax_cross_entropy_loss_bf16()
void softmax_cross_entropy_loss_bf16 (const uint16_t * logits, const int32_t * targets, int tokens, int vocab_size, uint16_t * d_logits, float * loss_out)
Definition at line 8 of file loss_kernels_bf16.c.
 {
     if (!logits || !targets || !d_logits || tokens <= 0 || vocab_size <= 0) {
         if (loss_out) {
             *loss_out = 0.0f;
         }
         return;
     }
     const size_t count = (size_t)tokens * (size_t)vocab_size;
     float *logits_f = (float *)malloc(count * sizeof(float));
     float *d_logits_f = (float *)malloc(count * sizeof(float));
     if (!logits_f || !d_logits_f) {
         free(logits_f);
         free(d_logits_f);
         if (loss_out) {
             *loss_out = 0.0f;
         }
         return;
     }
     bf16_tensor_to_float(logits, logits_f, count);
     softmax_cross_entropy_loss(logits_f, targets, tokens, vocab_size, d_logits_f, loss_out);
     float_tensor_to_bf16(d_logits_f, d_logits, count);
     free(logits_f);
     free(d_logits_f);
 }
References bf16_tensor_to_float(), float_tensor_to_bf16(), and softmax_cross_entropy_loss().
swiglu_backward()
void swiglu_backward (const float * input, const float * d_output, float * d_input, int tokens, int dim)
Definition at line 192 of file swiglu_kernels.c.
 {
     int T = tokens;
     int D = dim;
     for (int t = 0; t < T; ++t) {
         const float *row = input + (size_t)t * (2 * D);
         const float *dy_row = d_output + (size_t)t * D;
         float *dx_row = d_input + (size_t)t * (2 * D);
         int d = 0;
 #if defined(__AVX512F__)
         // AVX-512: Process 16 floats at a time
         __m512 one = _mm512_set1_ps(1.0f);
         for (; d + 16 <= D; d += 16) {
             __m512 a = _mm512_loadu_ps(&row[d]);         // gate
             __m512 b = _mm512_loadu_ps(&row[D + d]);     // value
             __m512 dy = _mm512_loadu_ps(&dy_row[d]);
             __m512 s = sigmoid512_fast(a);              // sigmoid(a)
             __m512 silu = _mm512_mul_ps(a, s);          // silu(a) = a * s
             __m512 s_prime = _mm512_mul_ps(s, _mm512_sub_ps(one, s)); // s * (1 - s)
             __m512 silu_prime = _mm512_fmadd_ps(a, s_prime, s);       // s + a * s_prime
             // dA = dy * b * silu_prime
             __m512 dA = _mm512_mul_ps(dy, _mm512_mul_ps(b, silu_prime));
             // dB = dy * silu
             __m512 dB = _mm512_mul_ps(dy, silu);
             _mm512_storeu_ps(&dx_row[d], dA);
             _mm512_storeu_ps(&dx_row[D + d], dB);
         }
 #elif defined(__AVX2__)
         // AVX2: Process 8 floats at a time
         __m256 one = _mm256_set1_ps(1.0f);
         for (; d + 8 <= D; d += 8) {
             __m256 a = _mm256_loadu_ps(&row[d]);         // gate
             __m256 b = _mm256_loadu_ps(&row[D + d]);     // value
             __m256 dy = _mm256_loadu_ps(&dy_row[d]);
             __m256 s = sigmoid256_fast(a);              // sigmoid(a)
             __m256 silu = _mm256_mul_ps(a, s);          // silu(a) = a * s
             __m256 s_prime = _mm256_mul_ps(s, _mm256_sub_ps(one, s)); // s * (1 - s)
             __m256 silu_prime = _mm256_fmadd_ps(a, s_prime, s);       // s + a * s_prime
             // dA = dy * b * silu_prime
             __m256 dA = _mm256_mul_ps(dy, _mm256_mul_ps(b, silu_prime));
             // dB = dy * silu
             __m256 dB = _mm256_mul_ps(dy, silu);
             _mm256_storeu_ps(&dx_row[d], dA);
             _mm256_storeu_ps(&dx_row[D + d], dB);
         }
 #elif defined(__AVX__)
         // AVX1: Vectorize arithmetic, use scalar sigmoid
         __m256 one = _mm256_set1_ps(1.0f);
         float a_arr[8] __attribute__((aligned(32)));
         float s_arr[8] __attribute__((aligned(32)));
         for (; d + 8 <= D; d += 8) {
             __m256 a = _mm256_loadu_ps(&row[d]);         // gate
             __m256 b = _mm256_loadu_ps(&row[D + d]);     // value
             __m256 dy = _mm256_loadu_ps(&dy_row[d]);
             // Compute sigmoid scalarly
             _mm256_store_ps(a_arr, a);
             for (int j = 0; j < 8; ++j) {
                 s_arr[j] = sigmoid_scalar(a_arr[j]);
             }
             __m256 s = _mm256_load_ps(s_arr);
             __m256 silu = _mm256_mul_ps(a, s);                        // silu(a) = a * s
             __m256 s_prime = _mm256_mul_ps(s, _mm256_sub_ps(one, s)); // s * (1 - s)
             // silu_prime = s + a * s_prime (no FMA in AVX1)
             __m256 a_s_prime = _mm256_mul_ps(a, s_prime);
             __m256 silu_prime = _mm256_add_ps(s, a_s_prime);
             // dA = dy * b * silu_prime
             __m256 dA = _mm256_mul_ps(dy, _mm256_mul_ps(b, silu_prime));
             // dB = dy * silu
             __m256 dB = _mm256_mul_ps(dy, silu);
             _mm256_storeu_ps(&dx_row[d], dA);
             _mm256_storeu_ps(&dx_row[D + d], dB);
         }
 #endif
         // Scalar fallback for remaining elements
         for (; d < D; ++d) {
             float a = row[d];       // gate
             float b = row[D + d];   // value
             float dy = dy_row[d];
             float s = sigmoid_scalar(a);               // sigmoid(a)
             float silu = a * s;                       // silu(a)
             float s_prime = s * (1.0f - s);           // sigmoid'(a)
             float silu_prime = s + a * s_prime;       // silu'(a)
             float dA = dy * b * silu_prime;
             float dB = dy * silu;
             dx_row[d] = dA;
             dx_row[D + d] = dB;
         }
     }
 }
References __attribute__(), and sigmoid_scalar().
Referenced by ck_layer_backward_rmsnorm_swiglu().
swiglu_backward_bf16()
void swiglu_backward_bf16 (const uint16_t * input, const uint16_t * d_output, uint16_t * d_input, int tokens, int dim)
Definition at line 92 of file swiglu_kernels_bf16.c.
 {
     if (!input || !d_output || !d_input || tokens <= 0 || dim <= 0) {
         return;
     }
     const int T = tokens;
     const int D = dim;
     for (int t = 0; t < T; ++t) {
         const uint16_t *row = input + (size_t)t * (size_t)(2 * D);
         const uint16_t *dy_row = d_output + (size_t)t * (size_t)D;
         uint16_t *dx_row = d_input + (size_t)t * (size_t)(2 * D);
         int d = 0;
 #if defined(__AVX512F__)
         // AVX-512: Process 16 floats at a time
         __m512 one = _mm512_set1_ps(1.0f);
         for (; d + 16 <= D; d += 16) {
             __m512 a = bf16_loadu_cvt_fp32(&row[d]);         // gate
             __m512 b = bf16_loadu_cvt_fp32(&row[D + d]);     // value
             __m512 dy = bf16_loadu_cvt_fp32(&dy_row[d]);
             __m512 s = sigmoid512_fast_bf16(a);             // sigmoid(a)
             __m512 silu = _mm512_mul_ps(a, s);              // silu(a) = a * s
             __m512 s_prime = _mm512_mul_ps(s, _mm512_sub_ps(one, s)); // s * (1 - s)
             __m512 silu_prime = _mm512_fmadd_ps(a, s_prime, s);       // s + a * s_prime
             // dA = dy * b * silu_prime
             __m512 dA = _mm512_mul_ps(dy, _mm512_mul_ps(b, silu_prime));
             // dB = dy * silu
             __m512 dB = _mm512_mul_ps(dy, silu);
             fp32_cvt_storeu_bf16(&dx_row[d], dA);
             fp32_cvt_storeu_bf16(&dx_row[D + d], dB);
         }
 #endif
         // Scalar fallback for remaining elements
         for (; d < D; ++d) {
             float a = bf16_to_float(row[d]);
             float b = bf16_to_float(row[D + d]);
             float dy = bf16_to_float(dy_row[d]);
             float s = sigmoid_scalar(a);
             float silu = a * s;
             float s_prime = s * (1.0f - s);
             float silu_prime = s + a * s_prime;
             float dA = dy * b * silu_prime;
             float dB = dy * silu;
             dx_row[d] = float_to_bf16(dA);
             dx_row[D + d] = float_to_bf16(dB);
         }
     }
 }
References bf16_to_float(), float_to_bf16(), and sigmoid_scalar().
swiglu_backward_exact()
void swiglu_backward_exact (const float * input, const float * d_output, float * d_input, int tokens, int dim)
Definition at line 334 of file swiglu_kernels.c.
 {
     int T = tokens;
     int D = dim;
     for (int t = 0; t < T; ++t) {
         const float *row = input + (size_t)t * (2 * D);
         const float *dy_row = d_output + (size_t)t * D;
         float *dx_row = d_input + (size_t)t * (2 * D);
         for (int d = 0; d < D; ++d) {
             float a = row[d];       // gate
             float b = row[D + d];   // value
             float dy = dy_row[d];
             // Use standard library expf via sigmoid_scalar
             float s = sigmoid_scalar(a);               // sigmoid(a)
             float silu = a * s;                       // silu(a)
             float s_prime = s * (1.0f - s);           // sigmoid'(a)
             float silu_prime = s + a * s_prime;       // silu'(a)
             float dA = dy * b * silu_prime;
             float dB = dy * silu;
             dx_row[d] = dA;
             dx_row[D + d] = dB;
         }
     }
 }
References sigmoid_scalar().
swiglu_forward()
void swiglu_forward (const float * input, float * output, int tokens, int dim)
Definition at line 111 of file swiglu_kernels.c.
 {
     int T = tokens;
     int D = dim;
     for (int t = 0; t < T; ++t) {
         const float *row = input + (size_t)t * (2 * D);
         float *out_row = output + (size_t)t * D;
         int d = 0;
 #if defined(__AVX512F__)
         // AVX-512: Process 16 floats at a time
         for (; d + 16 <= D; d += 16) {
             __m512 a = _mm512_loadu_ps(&row[d]);         // gate
             __m512 b = _mm512_loadu_ps(&row[D + d]);     // value
             __m512 s = sigmoid512_fast(a);              // sigmoid(a)
             __m512 silu = _mm512_mul_ps(a, s);          // silu(a) = a * sigmoid(a)
             __m512 y = _mm512_mul_ps(silu, b);          // y = silu(a) * b
             _mm512_storeu_ps(&out_row[d], y);
         }
 #elif defined(__AVX2__)
         // AVX2: Process 8 floats at a time
         for (; d + 8 <= D; d += 8) {
             __m256 a = _mm256_loadu_ps(&row[d]);         // gate
             __m256 b = _mm256_loadu_ps(&row[D + d]);     // value
             __m256 s = sigmoid256_fast(a);              // sigmoid(a)
             __m256 silu = _mm256_mul_ps(a, s);          // silu(a) = a * sigmoid(a)
             __m256 y = _mm256_mul_ps(silu, b);          // y = silu(a) * b
             _mm256_storeu_ps(&out_row[d], y);
         }
 #elif defined(__AVX__)
         // AVX1: Vectorize arithmetic, use scalar sigmoid
         float a_arr[8] __attribute__((aligned(32)));
         float s_arr[8] __attribute__((aligned(32)));
         for (; d + 8 <= D; d += 8) {
             __m256 a = _mm256_loadu_ps(&row[d]);         // gate
             __m256 b = _mm256_loadu_ps(&row[D + d]);     // value
             // Compute sigmoid scalarly
             _mm256_store_ps(a_arr, a);
             for (int j = 0; j < 8; ++j) {
                 s_arr[j] = sigmoid_scalar(a_arr[j]);
             }
             __m256 s = _mm256_load_ps(s_arr);
             __m256 silu = _mm256_mul_ps(a, s);          // silu(a) = a * sigmoid(a)
             __m256 y = _mm256_mul_ps(silu, b);          // y = silu(a) * b
             _mm256_storeu_ps(&out_row[d], y);
         }
 #endif
         // Scalar fallback for remaining elements
         for (; d < D; ++d) {
             float a = row[d];       // gate
             float b = row[D + d];   // value
             float s = sigmoid_scalar(a);         // sigmoid(a)
             float silu = a * s;                  // silu(a) = a * sigmoid(a)
             out_row[d] = silu * b;
         }
     }
 }
References __attribute__(), and sigmoid_scalar().
Referenced by ck_mlp_swiglu_forward(), ck_mlp_swiglu_forward_q4_k(), ck_mlp_swiglu_forward_q4_k_q8_k(), ck_mlp_swiglu_forward_quant(), and ck_mlp_swiglu_forward_ref().
swiglu_forward_bf16()
void swiglu_forward_bf16 (const uint16_t * input, uint16_t * output, int tokens, int dim)
Definition at line 50 of file swiglu_kernels_bf16.c.
 {
     if (!input || !output || tokens <= 0 || dim <= 0) {
         return;
     }
     const int T = tokens;
     const int D = dim;
     for (int t = 0; t < T; ++t) {
         const uint16_t *row = input + (size_t)t * (size_t)(2 * D);
         uint16_t *out_row = output + (size_t)t * (size_t)D;
         int d = 0;
 #if defined(__AVX512F__)
         // AVX-512: Process 16 floats at a time
         for (; d + 16 <= D; d += 16) {
             __m512 a = bf16_loadu_cvt_fp32(&row[d]);         // gate
             __m512 b = bf16_loadu_cvt_fp32(&row[D + d]);     // value
             __m512 s = sigmoid512_fast_bf16(a);             // sigmoid(a)
             __m512 silu = _mm512_mul_ps(a, s);              // silu(a) = a * sigmoid(a)
             __m512 y = _mm512_mul_ps(silu, b);              // y = silu(a) * b
             fp32_cvt_storeu_bf16(&out_row[d], y);
         }
 #endif
         // Scalar fallback for remaining elements
         for (; d < D; ++d) {
             float a = bf16_to_float(row[d]);
             float b = bf16_to_float(row[D + d]);
             float s = sigmoid_scalar(a);
             float silu = a * s;
             out_row[d] = float_to_bf16(silu * b);
         }
     }
 }
References bf16_to_float(), float_to_bf16(), and sigmoid_scalar().
swiglu_forward_exact()
void swiglu_forward_exact (const float * input, float * output, int tokens, int dim)
Definition at line 308 of file swiglu_kernels.c.
 {
     int T = tokens;
     int D = dim;
     for (int t = 0; t < T; ++t) {
         const float *row = input + (size_t)t * (2 * D);
         float *out_row = output + (size_t)t * D;
         for (int d = 0; d < D; ++d) {
             float a = row[d];       // gate
             float b = row[D + d];   // value
             // Use standard library expf via sigmoid_scalar
             float s = sigmoid_scalar(a);         // sigmoid(a) = 1/(1+expf(-a))
             float silu = a * s;                  // silu(a) = a * sigmoid(a)
             out_row[d] = silu * b;
         }
     }
 }
References sigmoid_scalar().