ckernel_quant.h File Reference
CK ← Back to C-Kernel-Engine Docs Doxygen Source Documentation
ckernel_quant.h File Reference
Quantization block structures for weight-only quantization.
#include <stdint.h>
#include <stddef.h>
#include "ckernel_dtype.h"
Data Structures
struct block_q4_0
struct block_q4_K
struct block_q6_K
struct block_q8_0
struct block_q8_K
Macros
#define CK_FP16_TO_FP32(x) ck_fp16_to_fp32(x)
#define CK_FP32_TO_FP16(x) ck_fp32_to_fp16(x)
#define ggml_fp16_to_fp32 ck_fp16_to_fp32
#define GGML_FP16_TO_FP32 CK_FP16_TO_FP32
#define ggml_fp32_to_fp16 ck_fp32_to_fp16
#define GGML_FP32_TO_FP16 CK_FP32_TO_FP16
#define K_SCALE_SIZE 12
#define QK4_0 32
#define QK8_0 32
#define QK_K 256
Typedefs
typedef uint16_t ck_half
typedef ck_half ggml_half
Functions
static float ck_fp16_to_fp32 (ck_half h)
Convert FP16 (ck_half) to FP32.
static ck_half ck_fp32_to_fp16 (float f)
Convert FP32 to FP16 (ck_half)
static size_t ck_quant_block_size (int type)
Get the block size (number of weights per block) for a quant type.
static size_t ck_quant_row_size (int type, int64_t n_elements)
Calculate total bytes needed for n_elements with given quant type.
static size_t ck_quant_type_size (int type)
Get the byte size per block for a quant type.
static void unpack_q4_k_scales (const uint8_t *scales, uint8_t *sc, uint8_t *m)
Unpack Q4_K sub-block scales and mins.
Detailed Description
Quantization block structures for weight-only quantization.
Defines block structures for various quantization formats used in LLM inference. Primary focus on Q4_K_M which is commonly used for LLM weight compression.
Block structures are compatible with llama.cpp/GGML for model loading.
Definition in file ckernel_quant.h.
Macro Definition Documentation
CK_FP16_TO_FP32
#define CK_FP16_TO_FP32 (x) ck_fp16_to_fp32(x)
Definition at line 264 of file ckernel_quant.h.
CK_FP32_TO_FP16
#define CK_FP32_TO_FP16 (x) ck_fp32_to_fp16(x)
Definition at line 265 of file ckernel_quant.h.
ggml_fp16_to_fp32
#define ggml_fp16_to_fp32 ck_fp16_to_fp32
Definition at line 269 of file ckernel_quant.h.
GGML_FP16_TO_FP32
#define GGML_FP16_TO_FP32 CK_FP16_TO_FP32
Definition at line 271 of file ckernel_quant.h.
ggml_fp32_to_fp16
#define ggml_fp32_to_fp16 ck_fp32_to_fp16
Definition at line 270 of file ckernel_quant.h.
GGML_FP32_TO_FP16
#define GGML_FP32_TO_FP16 CK_FP32_TO_FP16
Definition at line 272 of file ckernel_quant.h.
K_SCALE_SIZE
#define K_SCALE_SIZE 12
Definition at line 70 of file ckernel_quant.h.
QK4_0
#define QK4_0 32
Definition at line 35 of file ckernel_quant.h.
QK8_0
#define QK8_0 32
Definition at line 50 of file ckernel_quant.h.
QK_K
#define QK_K 256
Definition at line 69 of file ckernel_quant.h.
Typedef Documentation
ck_half
typedef uint16_t ck_half
Definition at line 26 of file ckernel_quant.h.
ggml_half
typedef ck_half ggml_half
Definition at line 268 of file ckernel_quant.h.
Function Documentation
ck_fp16_to_fp32()
static float ck_fp16_to_fp32 (ck_half h) inline static
Convert FP16 (ck_half) to FP32.
Definition at line 198 of file ckernel_quant.h.
{
     /*
      * FP16: 1 sign + 5 exponent + 10 mantissa
      * FP32: 1 sign + 8 exponent + 23 mantissa
      */
     uint32_t sign = (h & 0x8000) << 16;
     uint32_t exp = (h >> 10) & 0x1F;
     uint32_t mant = h & 0x3FF;
     uint32_t result;
     if (exp == 0) {
         if (mant == 0) {
             /* Zero */
             result = sign;
         } else {
             /* Denormalized - convert to normalized FP32 */
             exp = 1;
             while ((mant & 0x400) == 0) {
                 mant <<= 1;
                 exp--;
             }
             mant &= 0x3FF;
             result = sign | ((exp + 127 - 15) << 23) | (mant << 13);
         }
     } else if (exp == 31) {
         /* Inf or NaN */
         result = sign | 0x7F800000 | (mant << 13);
     } else {
         /* Normalized */
         result = sign | ((exp + 127 - 15) << 23) | (mant << 13);
     }
     union { uint32_t u; float f; } u;
     u.u = result;
     return u.f;
 }
ck_fp32_to_fp16()
static ck_half ck_fp32_to_fp16 (float f) inline static
Convert FP32 to FP16 (ck_half)
Definition at line 239 of file ckernel_quant.h.
{
     union { uint32_t u; float f; } u;
     u.f = f;
     uint32_t sign = (u.u >> 16) & 0x8000;
     int32_t exp = ((u.u >> 23) & 0xFF) - 127 + 15;
     uint32_t mant = (u.u >> 13) & 0x3FF;
     if (exp <= 0) {
         if (exp < -10) {
             /* Underflow to zero */
             return sign;
         }
         /* Denormalized */
         mant = (mant | 0x400) >> (1 - exp);
         return sign | mant;
     } else if (exp >= 31) {
         /* Overflow to infinity */
         return sign | 0x7C00;
     }
     return sign | (exp << 10) | mant;
 }
ck_quant_block_size()
static size_t ck_quant_block_size (int type) inline static
Get the block size (number of weights per block) for a quant type.
Definition at line 115 of file ckernel_quant.h.
{
     switch (type) {
         case 0: return QK4_0;    /* Q4_0 */
         case 1: return QK8_0;    /* Q8_0 */
         case 2: return QK_K;     /* Q4_K */
         case 3: return QK_K;     /* Q8_K */
         case CK_DT_Q6_K: return QK_K;
         default: return 1;
     }
 }
References CK_DT_Q6_K, QK4_0, QK8_0, and QK_K.
Referenced by ck_quant_row_size().
ck_quant_row_size()
static size_t ck_quant_row_size (int type, int64_t n_elements) inline static
Calculate total bytes needed for n_elements with given quant type.
Definition at line 143 of file ckernel_quant.h.
{
     size_t block_size = ck_quant_block_size(type);
     size_t type_size = ck_quant_type_size(type);
     return (n_elements / block_size) * type_size;
 }
References ck_quant_block_size(), and ck_quant_type_size().
ck_quant_type_size()
static size_t ck_quant_type_size (int type) inline static
Get the byte size per block for a quant type.
Definition at line 129 of file ckernel_quant.h.
{
     switch (type) {
         case 0: return sizeof(block_q4_0);
         case 1: return sizeof(block_q8_0);
         case 2: return sizeof(block_q4_K);
         case 3: return sizeof(block_q8_K);
         case CK_DT_Q6_K: return sizeof(block_q6_K);
         default: return 4; /* FP32 */
     }
 }
References CK_DT_Q6_K.
Referenced by ck_quant_row_size().
unpack_q4_k_scales()
static void unpack_q4_k_scales (const uint8_t * scales, uint8_t * sc, uint8_t * m) inline static
Unpack Q4_K sub-block scales and mins.
Parameters
scales The packed scales[12] array from block_q4_K
sc Output: 8 unpacked scale values (multiply by super-block d)
m Output: 8 unpacked min values (multiply by super-block dmin)
Definition at line 163 of file ckernel_quant.h.
{
     /*
      * The 12-byte scales array encodes 8 scales and 8 mins in 6-bit each.
      * Each 6-bit value is split across byte boundaries.
      */
     /* Unpack scales (sc[0..7]) from bytes 0-5 */
     sc[0] = (scales[0] & 0x3F);
     sc[1] = (scales[0] >> 6) | ((scales[1] & 0x0F) << 2);
     sc[2] = (scales[1] >> 4) | ((scales[2] & 0x03) << 4);
     sc[3] = (scales[2] >> 2);
     sc[4] = (scales[3] & 0x3F);
     sc[5] = (scales[3] >> 6) | ((scales[4] & 0x0F) << 2);
     sc[6] = (scales[4] >> 4) | ((scales[5] & 0x03) << 4);
     sc[7] = (scales[5] >> 2);
     /* Unpack mins (m[0..7]) from bytes 6-11 */
     m[0] = (scales[6] & 0x3F);
     m[1] = (scales[6] >> 6) | ((scales[7] & 0x0F) << 2);
     m[2] = (scales[7] >> 4) | ((scales[8] & 0x03) << 4);
     m[3] = (scales[8] >> 2);
     m[4] = (scales[9] & 0x3F);
     m[5] = (scales[9] >> 6) | ((scales[10] & 0x0F) << 2);
     m[6] = (scales[10] >> 4) | ((scales[11] & 0x03) << 4);
     m[7] = (scales[11] >> 2);
 }
Referenced by dequant_q4_k_block(), dot_q4_k_q8_k_ref(), gemv_q4_k_backward_ref(), gemv_q4_k_q8_k_avx2(), gemv_q4_k_q8_k_vnni(), and gemv_q4_k_ref().