ckernel_alloc.c File Reference
CK ← Back to C-Kernel-Engine Docs Doxygen Source Documentation
ckernel_alloc.c File Reference
#include "ckernel_alloc.h"
#include <errno.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/types.h>
#include <unistd.h>
Macros
#define _GNU_SOURCE
#define HUGE_PAGE_SIZE (2UL * 1024UL * 1024UL)
Functions
static size_t align_up_bytes (size_t n, size_t align)
void * ck_huge_alloc (size_t bytes)
void ck_huge_free (void *ptr, size_t bytes)
static ck_huge_alloc_entry_t * detach_allocation (void *ptr)
static int record_allocation (void *ptr, size_t len, int was_mmap)
Variables
static ck_huge_alloc_entry_t * g_alloc_list = NULL
static pthread_mutex_t g_alloc_mutex = PTHREAD_MUTEX_INITIALIZER
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file ckernel_alloc.c.
HUGE_PAGE_SIZE
#define HUGE_PAGE_SIZE (2UL * 1024UL * 1024UL)
Definition at line 15 of file ckernel_alloc.c.
Function Documentation
align_up_bytes()
static size_t align_up_bytes (size_t n, size_t align) static
Definition at line 28 of file ckernel_alloc.c.
 {
     if (align == 0) return n;
     return (n + align - 1) & ~(align - 1);
 }
Referenced by ck_huge_alloc().
ck_huge_alloc()
void* ck_huge_alloc (size_t bytes)
Allocate a large, contiguous memory region for model weights/activations.
Implementation strategy:
Try to allocate 2MB-aligned memory backed by huge pages where possible.
Fall back to aligned_alloc + madvise(MADV_HUGEPAGE) when explicit huge pages are not available.
Returns NULL on failure.
Definition at line 67 of file ckernel_alloc.c.
 {
     size_t len = align_up_bytes(bytes, HUGE_PAGE_SIZE);
     /* First, try explicit huge pages via mmap + MAP_HUGETLB. */
     void *p = mmap(NULL, len,
                    PROT_READ | PROT_WRITE,
                    MAP_PRIVATE | MAP_ANONYMOUS | MAP_HUGETLB,
                    -1, 0);
     if (p != MAP_FAILED) {
         if (!record_allocation(p, len, 1)) {
             munmap(p, len);
             return NULL;
         }
         return p;
     }
     /* Fallback: aligned_alloc with transparent hugepage hint. */
     void *q = aligned_alloc(HUGE_PAGE_SIZE, len);
     if (!q) {
         fprintf(stderr, "ck_huge_alloc: aligned_alloc failed for %zu bytes: %s\n",
                 len, strerror(errno));
         return NULL;
     }
     /* Best-effort hint; ignore errors. */
     (void)madvise(q, len, MADV_HUGEPAGE);
     if (!record_allocation(q, len, 0)) {
         free(q);
         return NULL;
     }
     return q;
 }
References align_up_bytes(), HUGE_PAGE_SIZE, and record_allocation().
ck_huge_free()
void ck_huge_free (void * ptr, size_t bytes)
Free memory allocated by ck_huge_alloc.
The bytes parameter should be the same size passed to ck_huge_alloc.
Definition at line 101 of file ckernel_alloc.c.
 {
     if (!ptr || bytes == 0) {
         return;
     }
     ck_huge_alloc_entry_t *entry = detach_allocation(ptr);
     if (!entry) {
         /* Fall back to malloc/free if the allocation wasn't tracked. */
         free(ptr);
         return;
     }
     if (entry->was_mmap) {
         munmap(ptr, entry->len);
     } else {
         free(ptr);
     }
     free(entry);
 }
References detach_allocation().
detach_allocation()
static ck_huge_alloc_entry_t* detach_allocation (void * ptr) static
Definition at line 50 of file ckernel_alloc.c.
 {
     pthread_mutex_lock(&g_alloc_mutex);
     ck_huge_alloc_entry_t **node = &g_alloc_list;
     while (*node) {
         if ((*node)->ptr == ptr) {
             ck_huge_alloc_entry_t *entry = *node;
             *node = entry->next;
             pthread_mutex_unlock(&g_alloc_mutex);
             return entry;
         }
         node = &(*node)->next;
     }
     pthread_mutex_unlock(&g_alloc_mutex);
     return NULL;
 }
References g_alloc_list, and g_alloc_mutex.
Referenced by ck_huge_free().
record_allocation()
static int record_allocation (void * ptr, size_t len, int was_mmap) static
Definition at line 34 of file ckernel_alloc.c.
 {
     ck_huge_alloc_entry_t *entry = malloc(sizeof(*entry));
     if (!entry) {
         return 0;
     }
     entry->ptr = ptr;
     entry->len = len;
     entry->was_mmap = was_mmap;
     pthread_mutex_lock(&g_alloc_mutex);
     entry->next = g_alloc_list;
     g_alloc_list = entry;
     pthread_mutex_unlock(&g_alloc_mutex);
     return 1;
 }
References g_alloc_list, and g_alloc_mutex.
Referenced by ck_huge_alloc().
Variable Documentation
g_alloc_list
ck_huge_alloc_entry_t* g_alloc_list = NULL static
Definition at line 26 of file ckernel_alloc.c.
Referenced by detach_allocation(), and record_allocation().
g_alloc_mutex
pthread_mutex_t g_alloc_mutex = PTHREAD_MUTEX_INITIALIZER static
Definition at line 25 of file ckernel_alloc.c.
Referenced by detach_allocation(), and record_allocation().