ckernel_registry.c File Reference
CK ← Back to C-Kernel-Engine Docs Doxygen Source Documentation
ckernel_registry.c File Reference
#include "ckernel_registry.h"
#include <stdio.h>
Functions
int ck_ir_validate_supported (const CKIRGraph *graph)
static const char * ck_op_name (CKOpType op)
int ck_op_supported (CKOpType op)
Function Documentation
ck_ir_validate_supported()
int ck_ir_validate_supported (const CKIRGraph * graph)
Definition at line 42 of file ckernel_registry.c.
 {
     if (!graph || !graph->nodes || graph->num_nodes <= 0) {
         return -1;
     }
     for (int i = 0; i < graph->num_nodes; ++i) {
         CKOpType op = graph->nodes[i].op;
         if (!ck_op_supported(op)) {
             fprintf(stderr,
                     "Unsupported op in IR: %s (layer=%u node=%u)\n",
                     ck_op_name(op),
                     (unsigned)graph->nodes[i].id.layer,
                     (unsigned)graph->nodes[i].id.node);
             return -1;
         }
     }
     return 0;
 }
References ck_op_name(), ck_op_supported(), CKIRNode::id, CKKernelId::layer, CKKernelId::node, CKIRGraph::nodes, CKIRGraph::num_nodes, and CKIRNode::op.
Referenced by ck_codegen_emit_runtime().
ck_op_name()
static const char* ck_op_name (CKOpType op) static
Definition at line 5 of file ckernel_registry.c.
 {
     switch (op) {
     case CK_OP_RMSNORM:        return "RMSNORM";
     case CK_OP_LINEAR_QKV:     return "LINEAR_QKV";
     case CK_OP_ATTENTION:      return "ATTENTION";
     case CK_OP_ADD:            return "ADD";
     case CK_OP_LINEAR:         return "LINEAR";
     case CK_OP_SPLIT:          return "SPLIT";
     case CK_OP_SWIGLU:         return "SWIGLU";
     case CK_OP_RMSNORM_BWD:    return "RMSNORM_BWD";
     case CK_OP_LINEAR_QKV_BWD: return "LINEAR_QKV_BWD";
     case CK_OP_ATTENTION_BWD:  return "ATTENTION_BWD";
     case CK_OP_ADD_BWD:        return "ADD_BWD";
     case CK_OP_LINEAR_BWD:     return "LINEAR_BWD";
     case CK_OP_SPLIT_BWD:      return "SPLIT_BWD";
     case CK_OP_SWIGLU_BWD:     return "SWIGLU_BWD";
     default:                   return "UNKNOWN";
     }
 }
References CK_OP_ADD, CK_OP_ADD_BWD, CK_OP_ATTENTION, CK_OP_ATTENTION_BWD, CK_OP_LINEAR, CK_OP_LINEAR_BWD, CK_OP_LINEAR_QKV, CK_OP_LINEAR_QKV_BWD, CK_OP_RMSNORM, CK_OP_RMSNORM_BWD, CK_OP_SPLIT, CK_OP_SPLIT_BWD, CK_OP_SWIGLU, and CK_OP_SWIGLU_BWD.
Referenced by ck_ir_validate_supported().
ck_op_supported()
int ck_op_supported (CKOpType op)
Definition at line 26 of file ckernel_registry.c.
 {
     switch (op) {
     case CK_OP_RMSNORM:
     case CK_OP_LINEAR_QKV:
     case CK_OP_ATTENTION:
     case CK_OP_ADD:
     case CK_OP_LINEAR:
     case CK_OP_SPLIT:
     case CK_OP_SWIGLU:
         return 1;
     default:
         return 0;
     }
 }
References CK_OP_ADD, CK_OP_ATTENTION, CK_OP_LINEAR, CK_OP_LINEAR_QKV, CK_OP_RMSNORM, CK_OP_SPLIT, and CK_OP_SWIGLU.
Referenced by ck_ir_validate_supported().