cpu_features.h File Reference
CK ← Back to C-Kernel-Engine Docs Doxygen Source Documentation
cpu_features.h File Reference
#include <stdint.h>
#include <stddef.h>
Data Structures
struct CPUInfo
struct GEMMParams
Functions
void cpu_features_init (void)
const CPUInfo * get_cpu_info (void)
const GEMMParams * get_gemm_params (void)
void print_cpu_info (void)
Variables
CPUInfo g_cpu_info
int g_cpu_initialized
GEMMParams g_gemm_params
Function Documentation
cpu_features_init()
void cpu_features_init (void)
Definition at line 344 of file cpu_features.c.
{
     if (g_cpu_initialized) return;
     memset(&g_cpu_info, 0, sizeof(g_cpu_info));
     memset(&g_gemm_params, 0, sizeof(g_gemm_params));
     // Detect SIMD features
 #ifdef X86_CPU
     detect_x86_features(&g_cpu_info);
     detect_x86_cache_sizes(&g_cpu_info);
 #endif
     // Linux sysfs fallback for cache sizes
 #if defined(__linux__)
     if (g_cpu_info.l1d_size == 0) {
         detect_linux_cache_sizes(&g_cpu_info);
     }
 #endif
     // Detect physical cores
     g_cpu_info.num_cores = detect_physical_cores();
     // Compute GEMM parameters based on detected hardware
     compute_gemm_params(&g_cpu_info, &g_gemm_params);
     g_cpu_initialized = 1;
 }
References compute_gemm_params(), detect_physical_cores(), g_cpu_info, g_cpu_initialized, g_gemm_params, CPUInfo::l1d_size, and CPUInfo::num_cores.
Referenced by get_cpu_info(), get_gemm_params(), and print_cpu_info().
get_cpu_info()
const CPUInfo* get_cpu_info (void)
Definition at line 377 of file cpu_features.c.
{
     if (!g_cpu_initialized) cpu_features_init();
     return &g_cpu_info;
 }
References cpu_features_init(), g_cpu_info, and g_cpu_initialized.
Referenced by gemm_init_threads().
get_gemm_params()
const GEMMParams* get_gemm_params (void)
Definition at line 372 of file cpu_features.c.
{
     if (!g_cpu_initialized) cpu_features_init();
     return &g_gemm_params;
 }
References cpu_features_init(), g_cpu_initialized, and g_gemm_params.
print_cpu_info()
void print_cpu_info (void)
Definition at line 382 of file cpu_features.c.
{
     if (!g_cpu_initialized) cpu_features_init();
     printf("=== CPU Info ===\n");
     printf("Physical cores: %d\n", g_cpu_info.num_cores);
     printf("L1 Data Cache:  %zu KB\n", g_cpu_info.l1d_size / 1024);
     printf("L2 Cache:       %zu KB\n", g_cpu_info.l2_size / 1024);
     printf("L3 Cache:       %zu MB\n", g_cpu_info.l3_size / (1024 * 1024));
     printf("Cache line:     %zu bytes\n", g_cpu_info.l1_line_size);
     printf("AVX:            %s\n", g_cpu_info.has_avx ? "yes" : "no");
     printf("AVX2:           %s\n", g_cpu_info.has_avx2 ? "yes" : "no");
     printf("AVX-512F:       %s\n", g_cpu_info.has_avx512f ? "yes" : "no");
     printf("FMA:            %s\n", g_cpu_info.has_fma ? "yes" : "no");
     printf("\n=== GEMM Blocking Parameters ===\n");
     printf("MR (microkernel rows): %d\n", g_gemm_params.MR);
     printf("NR (microkernel cols): %d\n", g_gemm_params.NR);
     printf("MC (M block):          %d\n", g_gemm_params.MC);
     printf("NC (N block):          %d\n", g_gemm_params.NC);
     printf("KC (K block):          %d\n", g_gemm_params.KC);
     printf("\n");
 }
References cpu_features_init(), g_cpu_info, g_cpu_initialized, g_gemm_params, CPUInfo::has_avx, CPUInfo::has_avx2, CPUInfo::has_avx512f, CPUInfo::has_fma, GEMMParams::KC, CPUInfo::l1_line_size, CPUInfo::l1d_size, CPUInfo::l2_size, CPUInfo::l3_size, GEMMParams::MC, GEMMParams::MR, GEMMParams::NC, GEMMParams::NR, and CPUInfo::num_cores.
Variable Documentation
g_cpu_info
CPUInfo g_cpu_info extern
CPU Feature Detection and Cache-Aware Parameter Tuning
Detects CPU features, cache sizes, and core counts at runtime. Computes optimal GEMM blocking parameters based on actual hardware.
Definition at line 28 of file cpu_features.c.
Referenced by cpu_features_init(), get_cpu_info(), and print_cpu_info().
g_cpu_initialized
int g_cpu_initialized extern
Definition at line 30 of file cpu_features.c.
Referenced by cpu_features_init(), get_cpu_info(), get_gemm_params(), and print_cpu_info().
g_gemm_params
GEMMParams g_gemm_params extern
Definition at line 29 of file cpu_features.c.
Referenced by cpu_features_init(), get_gemm_params(), and print_cpu_info().