gemm_kernels.c File Reference
CK ← Back to C-Kernel-Engine Docs Doxygen Source Documentation
gemm_kernels.c File Reference
#include "ckernel_engine.h"
#include <immintrin.h>
#include <omp.h>
Functions
static int ck_min (int a, int b)
void gemm_avx512_parallel (const float *A, const float *B, const float *bias, float *C, int M, int N, int K)
void gemm_blocked_serial (const float *A, const float *B, const float *bias, float *C, int M, int N, int K)
void gemm_fine_grained_parallel (const float *A, const float *B, const float *bias, float *C, int M, int N, int K)
void gemm_naive_parallel (const float *A, const float *B, const float *bias, float *C, int M, int N, int K)
Function Documentation
ck_min()
static int ck_min (int a, int b) inline static
Definition at line 5 of file gemm_kernels.c.
 { return a < b ? a : b; }
Referenced by gemm_blocked_serial(), and gemm_fine_grained_parallel().
gemm_avx512_parallel()
void gemm_avx512_parallel (const float * A, const float * B, const float * bias, float * C, int M, int N, int K)
Definition at line 28 of file gemm_kernels.c.
 {
 #pragma omp parallel for
     for (int i = 0; i < M; i++) {
         for (int j = 0; j < N; j++) {
             __m512 sum_vec = _mm512_setzero_ps();
             int k;
             for (k = 0; k <= K - 16; k += 16) {
                 __m512 a_vec = _mm512_loadu_ps(&A[i * K + k]);
                 __m512 b_vec = _mm512_loadu_ps(&B[j * K + k]);
                 sum_vec = _mm512_fmadd_ps(a_vec, b_vec, sum_vec);
             }
             float sum = _mm512_reduce_add_ps(sum_vec);
             for (; k < K; k++) {
                 sum += A[i * K + k] * B[j * K + k];
             }
             float bias_val = bias ? bias[j] : 0.0f;
             C[i * N + j] = sum + bias_val;
         }
     }
 }
gemm_blocked_serial()
void gemm_blocked_serial (const float * A, const float * B, const float * bias, float * C, int M, int N, int K)
Definition at line 99 of file gemm_kernels.c.
 {
     const int block_size = 64;
     for (int i = 0; i < M; i++) {
         for (int j = 0; j < N; j++) {
             C[i * N + j] = bias ? bias[j] : 0.0f;
         }
     }
     for (int ii = 0; ii < M; ii += block_size) {
         for (int jj = 0; jj < N; jj += block_size) {
             for (int kk = 0; kk < K; kk += block_size) {
                 int i_end = ck_min(ii + block_size, M);
                 int j_end = ck_min(jj + block_size, N);
                 int k_end = ck_min(kk + block_size, K);
                 for (int i = ii; i < i_end; i++) {
                     for (int j = jj; j < j_end; j++) {
                         __m512 sum_vec = _mm512_setzero_ps();
                         int k;
                         for (k = kk; k <= k_end - 16; k += 16) {
                             __m512 a_vec = _mm512_loadu_ps(&A[i * K + k]);
                             __m512 b_vec = _mm512_loadu_ps(&B[j * K + k]);
                             sum_vec = _mm512_fmadd_ps(a_vec, b_vec, sum_vec);
                         }
                         float partial_sum = _mm512_reduce_add_ps(sum_vec);
                         for (; k < k_end; k++) {
                             partial_sum += A[i * K + k] * B[j * K + k];
                         }
                         C[i * N + j] += partial_sum;
                     }
                 }
             }
         }
     }
 }
References ck_min().
Referenced by ck_attention_project_head_major(), ck_mlp_swiglu_forward(), ck_qkv_project_head_major(), ckernel_sgemm_native(), and mlp_token_parallel().
gemm_fine_grained_parallel()
void gemm_fine_grained_parallel (const float * A, const float * B, const float * bias, float * C, int M, int N, int K)
Definition at line 55 of file gemm_kernels.c.
 {
     const int block_size = 64;
 #pragma omp parallel for
     for (int i = 0; i < M; i++) {
         for (int j = 0; j < N; j++) {
             C[i * N + j] = bias ? bias[j] : 0.0f;
         }
     }
 #pragma omp parallel for collapse(3)
     for (int ii = 0; ii < M; ii += block_size) {
         for (int jj = 0; jj < N; jj += block_size) {
             for (int kk = 0; kk < K; kk += block_size) {
                 int i_end = ck_min(ii + block_size, M);
                 int j_end = ck_min(jj + block_size, N);
                 int k_end = ck_min(kk + block_size, K);
                 for (int i = ii; i < i_end; i++) {
                     for (int j = jj; j < j_end; j++) {
                         __m512 sum_vec = _mm512_setzero_ps();
                         int k;
                         for (k = kk; k <= k_end - 16; k += 16) {
                             __m512 a_vec = _mm512_loadu_ps(&A[i * K + k]);
                             __m512 b_vec = _mm512_loadu_ps(&B[j * K + k]);
                             sum_vec = _mm512_fmadd_ps(a_vec, b_vec, sum_vec);
                         }
                         float partial_sum = _mm512_reduce_add_ps(sum_vec);
                         for (; k < k_end; k++) {
                             partial_sum += A[i * K + k] * B[j * K + k];
                         }
 #pragma omp atomic
                         C[i * N + j] += partial_sum;
                     }
                 }
             }
         }
     }
 }
References ck_min().
gemm_naive_parallel()
void gemm_naive_parallel (const float * A, const float * B, const float * bias, float * C, int M, int N, int K)
Definition at line 8 of file gemm_kernels.c.
 {
 #pragma omp parallel for
     for (int i = 0; i < M; i++) {
         for (int j = 0; j < N; j++) {
             float sum = 0.0f;
             for (int k = 0; k < K; k++) {
                 sum += A[i * K + k] * B[j * K + k];
             }
             float bias_val = bias ? bias[j] : 0.0f;
             C[i * N + j] = sum + bias_val;
         }
     }
 }