gemm_kernels_q8_0.c File Reference
CK ← Back to C-Kernel-Engine Docs Doxygen Source Documentation
gemm_kernels_q8_0.c File Reference
GEMM/GEMV kernels with Q8_0 quantized weights.
#include <stdint.h>
#include <stddef.h>
#include <string.h>
#include "ckernel_quant.h"
Functions
float dot_q8_0 (const void *w_q8_0, const float *x, int K)
void gemm_q8_0 (float *Y, const void *W, const float *X, int M, int N, int K)
Matrix-matrix multiply with Q8_0 weights.
void gemm_q8_0_backward (float *dX, const void *W, const float *dY, int M, int N, int K)
Batched backward pass.
void gemv_q8_0 (float *y, const void *W, const float *x, int M, int K)
Auto-dispatch GEMV.
void gemv_q8_0_backward (float *dX, const void *W, const float *dY, int M, int K)
Auto-dispatch backward.
void gemv_q8_0_backward_ref (float *dX, const void *W, const float *dY, int M, int K)
Backward pass: compute input gradient (scalar reference)
void gemv_q8_0_ref (float *y, const void *W, const float *x, int M, int K)
Matrix-vector multiply with Q8_0 weights (scalar reference)
Detailed Description
GEMM/GEMV kernels with Q8_0 quantized weights.
Q8_0 Format:
32 weights per block
1 FP16 scale per block
34 bytes per 32 weights = 8.5 bits/weight
Weights stored as signed 8-bit integers
Operations: Forward: Y = W @ X (W is Q8_0, X and Y are FP32) Backward: dX = W^T @ dY (gradient w.r.t. input)
Note: Q8_0 is often used for activation quantization or as an intermediate format. Higher precision than Q4_0/Q4_K.
Definition in file gemm_kernels_q8_0.c.
Function Documentation
dot_q8_0()
float dot_q8_0 (const void * w_q8_0, const float * x, int K)
Definition at line 256 of file gemm_kernels_q8_0.c.
 {
     float result;
     gemv_q8_0(&result, w_q8_0, x, 1, K);
     return result;
 }
References gemv_q8_0().
gemm_q8_0()
void gemm_q8_0 (float * Y, const void * W, const float * X, int M, int N, int K)
Matrix-matrix multiply with Q8_0 weights.
Definition at line 132 of file gemm_kernels_q8_0.c.
 {
     for (int n = 0; n < N; n++) {
         gemv_q8_0(&Y[n * M], W, &X[n * K], M, K);
     }
 }
References gemv_q8_0().
gemm_q8_0_backward()
void gemm_q8_0_backward (float * dX, const void * W, const float * dY, int M, int N, int K)
Batched backward pass.
Definition at line 242 of file gemm_kernels_q8_0.c.
 {
     for (int n = 0; n < N; n++) {
         gemv_q8_0_backward(&dX[n * K], W, &dY[n * M], M, K);
     }
 }
References gemv_q8_0_backward().
gemv_q8_0()
void gemv_q8_0 (float * y, const void * W, const float * x, int M, int K)
Auto-dispatch GEMV.
Definition at line 113 of file gemm_kernels_q8_0.c.
 {
 #ifdef __AVX512F__
     gemv_q8_0_avx512(y, W, x, M, K);
 #else
     gemv_q8_0_ref(y, W, x, M, K);
 #endif
 }
References gemv_q8_0_ref().
Referenced by dot_q8_0(), and gemm_q8_0().
gemv_q8_0_backward()
void gemv_q8_0_backward (float * dX, const void * W, const float * dY, int M, int K)
Auto-dispatch backward.
Definition at line 227 of file gemm_kernels_q8_0.c.
 {
 #ifdef __AVX512F__
     gemv_q8_0_backward_avx512(dX, W, dY, M, K);
 #else
     gemv_q8_0_backward_ref(dX, W, dY, M, K);
 #endif
 }
References gemv_q8_0_backward_ref().
Referenced by gemm_q8_0_backward().
gemv_q8_0_backward_ref()
void gemv_q8_0_backward_ref (float * dX, const void * W, const float * dY, int M, int K)
Backward pass: compute input gradient (scalar reference)
Parameters
dX Output gradient w.r.t. input [K]
W Weight matrix in Q8_0 format [M x K]
dY Gradient w.r.t. output [M]
M Number of output rows
K Number of columns (input dimension)
Definition at line 155 of file gemm_kernels_q8_0.c.
 {
     const block_q8_0 *blocks = (const block_q8_0 *)W;
     const int blocks_per_row = K / QK8_0;
     /* Zero output gradient */
     memset(dX, 0, K * sizeof(float));
     /* Accumulate: dX += W^T @ dY */
     for (int row = 0; row < M; row++) {
         const float dy = dY[row];
         for (int b = 0; b < blocks_per_row; b++) {
             const block_q8_0 *block = &blocks[row * blocks_per_row + b];
             const float d = CK_FP16_TO_FP32(block->d);
             float *dxp = &dX[b * QK8_0];
             for (int i = 0; i < QK8_0; i++) {
                 dxp[i] += d * (float)block->qs[i] * dy;
             }
         }
     }
 }
References CK_FP16_TO_FP32, block_q8_0::d, QK8_0, and block_q8_0::qs.
Referenced by gemv_q8_0_backward().
gemv_q8_0_ref()
void gemv_q8_0_ref (float * y, const void * W, const float * x, int M, int K)
Matrix-vector multiply with Q8_0 weights (scalar reference)
Parameters
y Output vector [M]
W Weight matrix in Q8_0 format [M x K]
x Input vector [K]
M Number of output rows
K Number of columns (must be multiple of 32)
Definition at line 41 of file gemm_kernels_q8_0.c.
 {
     const block_q8_0 *blocks = (const block_q8_0 *)W;
     const int blocks_per_row = K / QK8_0;
     for (int row = 0; row < M; row++) {
         float sum = 0.0f;
         for (int b = 0; b < blocks_per_row; b++) {
             const block_q8_0 *block = &blocks[row * blocks_per_row + b];
             const float d = CK_FP16_TO_FP32(block->d);
             const float *xp = &x[b * QK8_0];
             for (int i = 0; i < QK8_0; i++) {
                 sum += d * (float)block->qs[i] * xp[i];
             }
         }
         y[row] = sum;
     }
 }
References CK_FP16_TO_FP32, block_q8_0::d, QK8_0, and block_q8_0::qs.
Referenced by gemv_q8_0().