gemm_kernels_q4k_q8k_avx2.c File Reference
CK ← Back to C-Kernel-Engine Docs Doxygen Source Documentation
gemm_kernels_q4k_q8k_avx2.c File Reference
AVX2 Q4_K x Q8_K matvec kernel (inference only)
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include "ckernel_quant.h"
Functions
void gemv_q4_k_q8_k_avx2 (float *y, const void *W, const void *x_q8, int M, int K)
void gemv_q4_k_q8_k_ref (float *y, const void *W, const void *x_q8, int M, int K)
Detailed Description
AVX2 Q4_K x Q8_K matvec kernel (inference only)
Definition in file gemm_kernels_q4k_q8k_avx2.c.
Function Documentation
gemv_q4_k_q8_k_avx2()
void gemv_q4_k_q8_k_avx2 (float * y, const void * W, const void * x_q8, int M, int K)
Definition at line 78 of file gemm_kernels_q4k_q8k_avx2.c.
 {
 #if defined(__AVX2__)
     if (!y || !W || !x_q8 || M <= 0 || K <= 0) {
         return;
     }
     const block_q4_K *blocks = (const block_q4_K *)W;
     const block_q8_K *x = (const block_q8_K *)x_q8;
     const int blocks_per_row = K / QK_K;
     for (int row = 0; row < M; ++row) {
         const block_q4_K *w_row = blocks + (size_t)row * (size_t)blocks_per_row;
         float sumf = 0.0f;
         for (int i = 0; i < blocks_per_row; ++i) {
             uint8_t sc[8], m[8];
             unpack_q4_k_scales(w_row[i].scales, sc, m);
             int32_t sum_scale = 0;
             int32_t sum_min = 0;
             for (int sub = 0; sub < 8; ++sub) {
                 const uint8_t *qs = &w_row[i].qs[sub * 16];
                 const int8_t *q8 = &x[i].qs[sub * 32];
                 const int32_t sum_q4q8 = dot_q4_q8_32_avx2(qs, q8);
                 const int32_t sum_q8 = (int32_t)x[i].bsums[sub * 2] +
                                        (int32_t)x[i].bsums[sub * 2 + 1];
                 sum_scale += (int32_t)sc[sub] * (sum_q4q8 - 8 * sum_q8);
                 sum_min += (int32_t)m[sub] * sum_q8;
             }
             const float d = CK_FP16_TO_FP32(w_row[i].d) * x[i].d;
             const float dmin = CK_FP16_TO_FP32(w_row[i].dmin) * x[i].d;
             sumf += d * (float)sum_scale;
             sumf += dmin * (float)sum_min;
         }
         y[row] = sumf;
     }
 #else
     gemv_q4_k_q8_k_ref(y, W, x_q8, M, K);
 #endif
 }
References block_q8_K::bsums, CK_FP16_TO_FP32, block_q8_K::d, gemv_q4_k_q8_k_ref(), QK_K, block_q4_K::qs, block_q8_K::qs, and unpack_q4_k_scales().
Referenced by gemv_q4_k_q8_k(), and gemv_q4_k_q8_k_vnni().
gemv_q4_k_q8_k_ref()
void gemv_q4_k_q8_k_ref (float * y, const void * W, const void * x_q8, int M, int K)
Definition at line 128 of file gemm_kernels_q4k_q8k.c.
 {
     if (!y || !W || !x_q8 || M <= 0 || K <= 0) {
         return;
     }
     const block_q4_K *blocks = (const block_q4_K *)W;
     const block_q8_K *x = (const block_q8_K *)x_q8;
     const int blocks_per_row = K / QK_K;
     for (int row = 0; row < M; ++row) {
         const block_q4_K *w_row = blocks + (size_t)row * (size_t)blocks_per_row;
         y[row] = dot_q4_k_q8_k_ref(w_row, x, K);
     }
 }
Referenced by gemv_q4_k_q8_k_avx2().