kv_cache_kernels.c File Reference
CK ← Back to C-Kernel-Engine Docs Doxygen Source Documentation
kv_cache_kernels.c File Reference
#include "ckernel_engine.h"
#include <stddef.h>
#include <string.h>
Functions
void kv_cache_repack_head_major_inplace (float *buf, int num_heads, int tokens, int cache_capacity, int aligned_head_dim)
void kv_cache_write_head_major (const float *k_token, const float *v_token, float *k_cache, float *v_cache, int num_kv_heads, int token_index, int cache_capacity, int head_dim, int aligned_head_dim)
Function Documentation
kv_cache_repack_head_major_inplace()
void kv_cache_repack_head_major_inplace (float * buf, int num_heads, int tokens, int cache_capacity, int aligned_head_dim)
Definition at line 16 of file kv_cache_kernels.c.
 {
     if (!buf) {
         return;
     }
     if (num_heads <= 0 || tokens <= 0 || cache_capacity <= 0 || aligned_head_dim <= 0) {
         return;
     }
     if (tokens > cache_capacity) {
         tokens = cache_capacity;
     }
     if (tokens == cache_capacity) {
         return;
     }
     const size_t old_head_stride = (size_t)tokens * (size_t)aligned_head_dim;
     const size_t new_head_stride = (size_t)cache_capacity * (size_t)aligned_head_dim;
     const size_t bytes = (size_t)tokens * (size_t)aligned_head_dim * sizeof(float);
     // Move head blocks from high to low to avoid overwriting source data
     // for heads that have not yet been moved.
     for (int h = num_heads - 1; h >= 0; --h) {
         float *src = buf + (size_t)h * old_head_stride;
         float *dst = buf + (size_t)h * new_head_stride;
         memmove(dst, src, bytes);
     }
 }
kv_cache_write_head_major()
void kv_cache_write_head_major (const float * k_token, const float * v_token, float * k_cache, float * v_cache, int num_kv_heads, int token_index, int cache_capacity, int head_dim, int aligned_head_dim)
Definition at line 48 of file kv_cache_kernels.c.
 {
     if (!k_token || !v_token || !k_cache || !v_cache) {
         return;
     }
     if (num_kv_heads <= 0 || token_index < 0 || cache_capacity <= 0) {
         return;
     }
     if (token_index >= cache_capacity || head_dim <= 0 || aligned_head_dim <= 0) {
         return;
     }
     const size_t head_stride = (size_t)cache_capacity * (size_t)aligned_head_dim;
     const size_t token_stride = (size_t)aligned_head_dim;
     for (int h = 0; h < num_kv_heads; ++h) {
         const float *k_src = k_token + (size_t)h * token_stride;
         const float *v_src = v_token + (size_t)h * token_stride;
         float *k_dst = k_cache + (size_t)h * head_stride + (size_t)token_index * token_stride;
         float *v_dst = v_cache + (size_t)h * head_stride + (size_t)token_index * token_stride;
         if (head_dim == aligned_head_dim) {
             memcpy(k_dst, k_src, (size_t)aligned_head_dim * sizeof(float));
             memcpy(v_dst, v_src, (size_t)aligned_head_dim * sizeof(float));
         } else {
             for (int d = 0; d < head_dim; ++d) {
                 k_dst[d] = k_src[d];
                 v_dst[d] = v_src[d];
             }
             for (int d = head_dim; d < aligned_head_dim; ++d) {
                 k_dst[d] = 0.0f;
                 v_dst[d] = 0.0f;
             }
         }
     }
 }
Referenced by ck_layer_forward_rmsnorm_swiglu_decode(), ck_layer_forward_rmsnorm_swiglu_decode_fused(), ck_layer_forward_rmsnorm_swiglu_decode_fused_attn_impl(), and ck_layer_forward_rmsnorm_swiglu_decode_q4_k().