relu_kernels_bf16.c File Reference
CK ← Back to C-Kernel-Engine Docs Doxygen Source Documentation
relu_kernels_bf16.c File Reference
#include <stddef.h>
#include <stdint.h>
#include "bf16_utils.h"
#include "ckernel_engine.h"
Functions
void relu_backward_bf16 (const uint16_t *input, const uint16_t *d_output, uint16_t *d_input, size_t n)
void relu_forward_bf16 (const uint16_t *input, uint16_t *output, size_t n)
void relu_forward_inplace_bf16 (uint16_t *data, size_t n)
Function Documentation
relu_backward_bf16()
void relu_backward_bf16 (const uint16_t * input, const uint16_t * d_output, uint16_t * d_input, size_t n)
Definition at line 29 of file relu_kernels_bf16.c.
 {
     if (!input || !d_output || !d_input) {
         return;
     }
     for (size_t i = 0; i < n; ++i) {
         float x = bf16_to_float(input[i]);
         float dy = bf16_to_float(d_output[i]);
         d_input[i] = float_to_bf16(x > 0.0f ? dy : 0.0f);
     }
 }
References bf16_to_float(), and float_to_bf16().
relu_forward_bf16()
void relu_forward_bf16 (const uint16_t * input, uint16_t * output, size_t n)
Definition at line 7 of file relu_kernels_bf16.c.
 {
     if (!input || !output) {
         return;
     }
     for (size_t i = 0; i < n; ++i) {
         float x = bf16_to_float(input[i]);
         output[i] = float_to_bf16(x > 0.0f ? x : 0.0f);
     }
 }
References bf16_to_float(), and float_to_bf16().
relu_forward_inplace_bf16()
void relu_forward_inplace_bf16 (uint16_t * data, size_t n)
Definition at line 18 of file relu_kernels_bf16.c.
 {
     if (!data) {
         return;
     }
     for (size_t i = 0; i < n; ++i) {
         float x = bf16_to_float(data[i]);
         data[i] = float_to_bf16(x > 0.0f ? x : 0.0f);
     }
 }
References bf16_to_float(), and float_to_bf16().