rmsnorm_kernels_int8.c File Reference
CK ← Back to C-Kernel-Engine Docs Doxygen Source Documentation
rmsnorm_kernels_int8.c File Reference
#include <math.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include "ckernel_engine.h"
Functions
static float * alloc_float_buffer (size_t count)
static int8_t clamp_int8 (float value)
static void convert_float_to_int8 (const float *src, int8_t *dst, size_t count)
static void convert_int8_to_float (const int8_t *src, float *dst, size_t count)
static void free_float_buffer (float *buf)
void rmsnorm_backward_int8 (const int8_t *d_output, const int8_t *input, const float *gamma, const float *rstd_cache, int8_t *d_input, float *d_gamma, int tokens, int d_model, int aligned_embed_dim)
void rmsnorm_forward_int8 (const int8_t *input, const float *gamma, int8_t *output, float *rstd_cache, int tokens, int d_model, int aligned_embed_dim, float eps)
Function Documentation
alloc_float_buffer()
static float* alloc_float_buffer (size_t count) static
Definition at line 41 of file rmsnorm_kernels_int8.c.
 {
     return (float *)malloc(count * sizeof(float));
 }
Referenced by rmsnorm_backward_int8(), and rmsnorm_forward_int8().
clamp_int8()
static int8_t clamp_int8 (float value) static
Definition at line 21 of file rmsnorm_kernels_int8.c.
 {
     int32_t q = (int32_t)lrintf(value);
     if (q > INT8_MAX) {
         q = INT8_MAX;
     } else if (q < INT8_MIN) {
         q = INT8_MIN;
     }
     return (int8_t)q;
 }
Referenced by convert_float_to_int8().
convert_float_to_int8()
static void convert_float_to_int8 (const float * src, int8_t * dst, size_t count) static
Definition at line 32 of file rmsnorm_kernels_int8.c.
 {
     for (size_t i = 0; i < count; ++i) {
         dst[i] = clamp_int8(src[i]);
     }
 }
References clamp_int8().
Referenced by rmsnorm_backward_int8(), and rmsnorm_forward_int8().
convert_int8_to_float()
static void convert_int8_to_float (const int8_t * src, float * dst, size_t count) static
Definition at line 12 of file rmsnorm_kernels_int8.c.
 {
     for (size_t i = 0; i < count; ++i) {
         dst[i] = (float)src[i];
     }
 }
Referenced by rmsnorm_backward_int8(), and rmsnorm_forward_int8().
free_float_buffer()
static void free_float_buffer (float * buf) static
Definition at line 46 of file rmsnorm_kernels_int8.c.
 {
     free(buf);
 }
Referenced by rmsnorm_backward_int8(), and rmsnorm_forward_int8().
rmsnorm_backward_int8()
void rmsnorm_backward_int8 (const int8_t * d_output, const int8_t * input, const float * gamma, const float * rstd_cache, int8_t * d_input, float * d_gamma, int tokens, int d_model, int aligned_embed_dim)
Definition at line 82 of file rmsnorm_kernels_int8.c.
 {
     if (!d_output || !input || !gamma || !rstd_cache || !d_input || !d_gamma) {
         return;
     }
     size_t total = (size_t)tokens * (size_t)aligned_embed_dim;
     float *d_output_f = alloc_float_buffer(total);
     float *input_f = alloc_float_buffer(total);
     float *d_input_f = alloc_float_buffer(total);
     if (!d_output_f || !input_f || !d_input_f) {
         free_float_buffer(d_output_f);
         free_float_buffer(input_f);
         free_float_buffer(d_input_f);
         return;
     }
     convert_int8_to_float(d_output, d_output_f, total);
     convert_int8_to_float(input, input_f, total);
     // Zero gamma gradient before accumulation.
     for (int d = 0; d < d_model; ++d) {
         d_gamma[d] = 0.0f;
     }
     rmsnorm_backward(d_output_f,
                      input_f,
                      gamma,
                      rstd_cache,
                      d_input_f,
                      d_gamma,
                      tokens,
                      d_model,
                      aligned_embed_dim);
     convert_float_to_int8(d_input_f, d_input, total);
     free_float_buffer(d_output_f);
     free_float_buffer(input_f);
     free_float_buffer(d_input_f);
 }
References alloc_float_buffer(), convert_float_to_int8(), convert_int8_to_float(), free_float_buffer(), and rmsnorm_backward().
rmsnorm_forward_int8()
void rmsnorm_forward_int8 (const int8_t * input, const float * gamma, int8_t * output, float * rstd_cache, int tokens, int d_model, int aligned_embed_dim, float eps)
Definition at line 51 of file rmsnorm_kernels_int8.c.
 {
     if (!input || !gamma || !output) {
         return;
     }
     size_t total = (size_t)tokens * (size_t)aligned_embed_dim;
     float *input_f = alloc_float_buffer(total);
     float *output_f = alloc_float_buffer(total);
     if (!input_f || !output_f) {
         free_float_buffer(input_f);
         free_float_buffer(output_f);
         return;
     }
     convert_int8_to_float(input, input_f, total);
     rmsnorm_forward(input_f, gamma, output_f, rstd_cache,
                     tokens, d_model, aligned_embed_dim, eps);
     convert_float_to_int8(output_f, output, total);
     free_float_buffer(input_f);
     free_float_buffer(output_f);
 }
References alloc_float_buffer(), convert_float_to_int8(), convert_int8_to_float(), free_float_buffer(), and rmsnorm_forward().