rope_kernels_bf16.c File Reference
CK ← Back to C-Kernel-Engine Docs Doxygen Source Documentation
rope_kernels_bf16.c File Reference
#include <stdlib.h>
#include <stdint.h>
#include "bf16_utils.h"
#include "ckernel_engine.h"
Functions
static float * alloc_float_buffer (size_t count)
static void free_float_buffer (float *buf)
void rope_backward_bf16 (const uint16_t *d_out, uint16_t *d_x, const float *cos_cache, const float *sin_cache, int num_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset)
void rope_backward_qk_bf16 (const uint16_t *d_q_out, const uint16_t *d_k_out, uint16_t *d_q, uint16_t *d_k, const float *cos_cache, const float *sin_cache, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset)
void rope_forward_bf16 (uint16_t *x, const float *cos_cache, const float *sin_cache, int num_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset)
void rope_forward_qk_bf16 (uint16_t *q, uint16_t *k, const float *cos_cache, const float *sin_cache, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset)
Function Documentation
alloc_float_buffer()
static float* alloc_float_buffer (size_t count) static
Definition at line 11 of file rope_kernels_bf16.c.
 {
     return (float *)malloc(count * sizeof(float));
 }
Referenced by rope_backward_bf16(), and rope_forward_bf16().
free_float_buffer()
static void free_float_buffer (float * buf) static
Definition at line 16 of file rope_kernels_bf16.c.
 {
     free(buf);
 }
Referenced by rope_backward_bf16(), and rope_forward_bf16().
rope_backward_bf16()
void rope_backward_bf16 (const uint16_t * d_out, uint16_t * d_x, const float * cos_cache, const float * sin_cache, int num_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset)
Definition at line 44 of file rope_kernels_bf16.c.
 {
     size_t total = (size_t)num_heads * (size_t)num_tokens * (size_t)aligned_head_dim;
     float *d_out_f = alloc_float_buffer(total);
     float *d_x_f = alloc_float_buffer(total);
     if (!d_out_f || !d_x_f) {
         free_float_buffer(d_out_f);
         free_float_buffer(d_x_f);
         return;
     }
     bf16_tensor_to_float(d_out, d_out_f, total);
     rope_backward(d_out_f, d_x_f, cos_cache, sin_cache,
                   num_heads, num_tokens, head_dim, aligned_head_dim, pos_offset);
     float_tensor_to_bf16(d_x_f, d_x, total);
     free_float_buffer(d_out_f);
     free_float_buffer(d_x_f);
 }
References alloc_float_buffer(), bf16_tensor_to_float(), float_tensor_to_bf16(), free_float_buffer(), and rope_backward().
Referenced by rope_backward_qk_bf16().
rope_backward_qk_bf16()
void rope_backward_qk_bf16 (const uint16_t * d_q_out, const uint16_t * d_k_out, uint16_t * d_q, uint16_t * d_k, const float * cos_cache, const float * sin_cache, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset)
Definition at line 93 of file rope_kernels_bf16.c.
 {
     if (!d_q_out || !d_k_out || !d_q || !d_k) {
         return;
     }
     rope_backward_bf16(d_q_out, d_q, cos_cache, sin_cache,
                        num_heads, num_tokens, head_dim, aligned_head_dim, pos_offset);
     rope_backward_bf16(d_k_out, d_k, cos_cache, sin_cache,
                        num_kv_heads, num_tokens, head_dim, aligned_head_dim, pos_offset);
 }
References rope_backward_bf16().
rope_forward_bf16()
void rope_forward_bf16 (uint16_t * x, const float * cos_cache, const float * sin_cache, int num_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset)
Definition at line 21 of file rope_kernels_bf16.c.
 {
     size_t total = (size_t)num_heads * (size_t)num_tokens * (size_t)aligned_head_dim;
     float *tmp = alloc_float_buffer(total);
     if (!tmp) {
         return;
     }
     bf16_tensor_to_float(x, tmp, total);
     rope_forward(tmp, cos_cache, sin_cache,
                  num_heads, num_tokens, head_dim, aligned_head_dim, pos_offset);
     float_tensor_to_bf16(tmp, x, total);
     free_float_buffer(tmp);
 }
References alloc_float_buffer(), bf16_tensor_to_float(), float_tensor_to_bf16(), free_float_buffer(), and rope_forward().
Referenced by rope_forward_qk_bf16().
rope_forward_qk_bf16()
void rope_forward_qk_bf16 (uint16_t * q, uint16_t * k, const float * cos_cache, const float * sin_cache, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset)
Definition at line 72 of file rope_kernels_bf16.c.
 {
     if (!q || !k) {
         return;
     }
     rope_forward_bf16(q, cos_cache, sin_cache,
                       num_heads, num_tokens, head_dim, aligned_head_dim, pos_offset);
     rope_forward_bf16(k, cos_cache, sin_cache,
                       num_kv_heads, num_tokens, head_dim, aligned_head_dim, pos_offset);
 }
References rope_forward_bf16().